"""Failing tests for T-021 — embeddings: provider adapter, content-hash cache,
fp16 store, brute-force cosine.

Encodes tickets/T-021.md AC-1..AC-8. These tests are FROZEN after the Test
Agent hands off: do not edit this file to make an implementation pass — fix
the implementation (new file `onrecord/rag/embeddings.py`) instead.

Run with:
    uv run pytest tests/unit/rag/ -v

MODULE-PRESENCE GUARD (why every test starts with `_module()`)
--------------------------------------------------------------
`onrecord.rag.embeddings` is THIS ticket's target module and does not exist
yet. A module-scope `import onrecord.rag.embeddings` would blow the whole
file up as a pytest COLLECTION ERROR, which pollutes other in-flight
tickets' regression baselines (`uv run pytest -q` is run by the orchestrator
at any time). So, mirroring tests/unit/test_api.py's established idiom,
`_require_module_spec(...)` + `pytest.fail(...)` turns "module missing" into
a clean per-test RED failure. numpy and httpx are real pyproject deps
(numpy>=2.1, httpx>=0.27) so they import at module scope with no guard, and
this ticket adds NO dependencies.

ZERO NETWORK, ZERO KEYS
-----------------------
Every provider interaction goes through a `FakeProvider`/`ScriptedProvider`
(the Protocol boundary) or `httpx.MockTransport` (the OpenAI wire shape).
No test reads a real key: key-sensitive tests always `monkeypatch.delenv`
or `monkeypatch.setenv` a sentinel first, so neither branch is
"environmentally lucky" (plan-review I-5).

CONTRACTS PINNED HERE (from the ticket's Context section)
---------------------------------------------------------
* Content-hash key — `sha256(f"{model}\\n{dim}\\n{text}".encode("utf-8"))`
  hexdigest. The tests compute this THEMSELVES (`_content_hash`) and feed
  the result to `rows_for` / `entry_for`, which freezes the exact formula
  including the newline separators and the presence of `dim` in the key
  (plan-review M-9: a model whose `dimensions` parameter changes must not
  poison the cache at the same model name).
* `EmbeddingStore()` — no-arg construction yields an EMPTY store (model and
  dim come from the provider passed to `embed_corpus`, which is what the
  hash key is built from). `EmbeddingStore.load(dir)` is called on the
  CLASS and returns a store; `store.save(dir)` is called on an instance and
  creates `dir` if needed.
* On-disk layout under a store dir: `matrix.npy` (N x dim, **float16**,
  L2-normalized rows) + `entries.json` (a JSON object mapping
  hash -> `{"row": int, "chunk_id": str}` — exactly those two keys; the
  AC-7 corrupt-store fixtures below are hand-written in that shape, so the
  format is load-bearing, not illustrative).
* **Alignment is ID-KEYED, never positional** (orchestrator adjudication of
  plan-review C-3). Row order is first-appearance order across ALL runs
  ever made against the store, so consumers resolve rows via hashes and
  verify the recorded `chunk_id`. Two adversarial tests encode this:
  `test_permuted_store_with_extra_rows_resolves_by_hash_not_position` and
  `test_swapped_chunk_ids_are_visible_through_entry_for` — in both, a
  length-equality check (`len(entries) == matrix.shape[0]`) PASSES while
  the id-level correspondence is wrong, which is precisely why length
  equality proves nothing.
* `embed_corpus(pairs, provider, checkpoint_dir=None, checkpoint_every=N)`
  — embeds only pairs whose hash is absent, appends, records `chunk_id`
  per row. When `checkpoint_dir` is set it saves after every
  `checkpoint_every` newly-embedded items; saving at that granularity
  requires calling the provider in batches of at most `checkpoint_every`
  items, which the AC-8 tests assert directly (that is what makes "the
  FakeProvider raises on its 3rd batch" in AC-8 well-defined).
* Secret hygiene (LESSONS.md T-014, 2026-08-11): the key must never appear
  in ANY log record — the AC-6 tests capture at the ROOT logger with all
  library loggers left free to propagate at INFO (httpx's own logger emits
  the full request URL at INFO; that is the verified leak vector from
  T-014), on BOTH the success and the error path — nor in exception or
  repr text.
"""

import contextlib
import hashlib
import importlib.util
import json
import logging
import time
from pathlib import Path

import httpx
import numpy as np
import pytest

FAKE_MODEL = "fake-embed-model"
SENTINEL_KEY = "SUPERSECRET-sentinel-openaikey-zzz9999"
OPENAI_MODEL = "text-embedding-3-small"

# Captured before any test monkeypatches numpy.save (see the atomic-save test).
_REAL_NP_SAVE = np.save


# --------------------------------------------------------------------------
# Guards / module access
# --------------------------------------------------------------------------


def _require_module_spec(name: str, fail_message: str):
    """Return the module spec for `name`, or fail cleanly via pytest.fail.

    Mirrors tests/unit/test_api.py's guard idiom: importlib.util.find_spec
    raises ModuleNotFoundError (rather than returning None) when a parent
    package in a dotted name is itself missing — `onrecord.rag` does not
    exist yet either — so both "not found" cases are normalized into one
    clean assertion-style failure, never an uncaught exception or a pytest
    collection error.
    """
    try:
        spec = importlib.util.find_spec(name)
    except ModuleNotFoundError:
        spec = None
    if spec is None:
        pytest.fail(fail_message)
    return spec


def _module():
    _require_module_spec(
        "onrecord.rag.embeddings",
        "onrecord.rag.embeddings missing (T-021 target module — expected RED "
        "until the Implementation Agent lands it)",
    )
    import onrecord.rag.embeddings as embeddings

    return embeddings


def _attr(name: str):
    mod = _module()
    if not hasattr(mod, name):
        pytest.fail(f"onrecord.rag.embeddings.{name} missing")
    return getattr(mod, name)


def _new_store():
    """An empty store — `EmbeddingStore()` takes no required arguments."""
    return _attr("EmbeddingStore")()


def _load_store(path: Path):
    return _attr("EmbeddingStore").load(path)


# --------------------------------------------------------------------------
# Deterministic test doubles for the provider boundary
# --------------------------------------------------------------------------


class ProviderBoom(RuntimeError):
    """Simulated mid-run provider failure (quota exhaustion / flaky host)."""


def _fake_vector(text: str, dim: int, model: str) -> np.ndarray:
    """Deterministic, hash-seeded pseudo-embedding — stable across runs."""
    digest = hashlib.sha256(f"{model}|{dim}|{text}".encode()).digest()
    seed = int.from_bytes(digest[:8], "big")
    rng = np.random.default_rng(seed)
    return rng.standard_normal(dim).astype(np.float32)


class FakeProvider:
    """Hash-seeded deterministic stand-in for a real EmbeddingProvider.

    `calls` records every batch the store ASKED for; `returned` records only
    the batches that actually produced vectors (a batch that raises appears
    in `calls` but not in `returned`) — the AC-8 "nothing is embedded twice"
    assertion is about successfully-embedded texts.
    """

    def __init__(
        self,
        dim: int = 4,
        model: str = FAKE_MODEL,
        fail_on_call: int | None = None,
    ):
        self.dim = dim
        self.model = model
        self.fail_on_call = fail_on_call
        self.calls: list[list[str]] = []
        self.returned: list[list[str]] = []

    def embed(self, texts: list[str]) -> np.ndarray:
        batch = list(texts)
        self.calls.append(batch)
        if self.fail_on_call is not None and len(self.calls) == self.fail_on_call:
            raise ProviderBoom(f"simulated provider failure on batch {self.fail_on_call}")
        self.returned.append(batch)
        if not batch:
            return np.zeros((0, self.dim), dtype=np.float32)
        rows = [_fake_vector(t, self.dim, self.model) for t in batch]
        return np.stack(rows).astype(np.float32)

    @property
    def texts_seen(self) -> list[str]:
        return [t for batch in self.calls for t in batch]

    @property
    def texts_returned(self) -> list[str]:
        return [t for batch in self.returned for t in batch]


class ScriptedProvider:
    """Returns exactly the vector scripted for each text (hand-computable)."""

    def __init__(self, vectors: dict[str, list[float]], model: str = "scripted-model"):
        self.vectors = {k: np.asarray(v, dtype=np.float32) for k, v in vectors.items()}
        self.dim = int(next(iter(self.vectors.values())).shape[0])
        self.model = model
        self.calls: list[list[str]] = []

    def embed(self, texts: list[str]) -> np.ndarray:
        batch = list(texts)
        self.calls.append(batch)
        return np.stack([self.vectors[t] for t in batch]).astype(np.float32)


# --------------------------------------------------------------------------
# Shared helpers
# --------------------------------------------------------------------------


def _content_hash(model: str, dim: int, text: str) -> str:
    """The frozen cache key: sha256("<model>\\n<dim>\\n<text>") hexdigest."""
    return hashlib.sha256(f"{model}\n{dim}\n{text}".encode()).hexdigest()


def _pairs(n: int, prefix: str = "t") -> list[tuple[str, str]]:
    return [(f"c{i}", f"{prefix} {i}") for i in range(n)]


def _hashes_for(pairs: list[tuple[str, str]], dim: int = 4, model: str = FAKE_MODEL) -> list[str]:
    return [_content_hash(model, dim, text) for _, text in pairs]


def _l2(vec: np.ndarray) -> np.ndarray:
    vec = np.asarray(vec, dtype=np.float32)
    return vec / np.linalg.norm(vec)


def _write_raw_store(path: Path, matrix: np.ndarray, entries: dict[str, dict]) -> None:
    """Write a store's two files by hand (AC-7 corrupt-store fixtures)."""
    path.mkdir(parents=True, exist_ok=True)
    np.save(path / "matrix.npy", matrix)
    (path / "entries.json").write_text(json.dumps(entries), encoding="utf-8")


def _valid_raw_store(path: Path, rows: int = 3, dim: int = 4) -> tuple[np.ndarray, dict]:
    matrix = np.stack([_l2(_fake_vector(f"t {i}", dim, FAKE_MODEL)) for i in range(rows)]).astype(
        np.float16
    )
    entries = {
        _content_hash(FAKE_MODEL, dim, f"t {i}"): {"row": i, "chunk_id": f"c{i}"}
        for i in range(rows)
    }
    _write_raw_store(path, matrix, entries)
    return matrix, entries


def _build_cosine_store(vectors: list[list[float]]):
    """A real EmbeddingStore holding exactly `vectors` (normalized, fp16)."""
    texts = [f"cos-text-{i}" for i in range(len(vectors))]
    provider = ScriptedProvider(dict(zip(texts, vectors, strict=True)))
    store = _new_store()
    store.embed_corpus([(f"cos-{i}", t) for i, t in enumerate(texts)], provider)
    return store


def _marker_value(text: str) -> float:
    """Recover the ordinal encoded in a `doc-<i>` text (0.0 if absent)."""
    tail = text.rsplit("-", 1)[-1]
    return float(tail) if tail.isdigit() else 0.0


def _openai_handler(
    dim: int,
    requests: list[httpx.Request],
    statuses: list[int] | None = None,
    reverse_data: bool = False,
):
    """MockTransport handler: records requests, replies OpenAI-shaped.

    Each returned embedding is `[<ordinal of the text>, 0.0, 0.0, ...]` so a
    row's identity is readable from its first component — that is how the
    "row order == input order" contract is asserted across a batch split.
    `statuses` is a queue of status codes (200 once exhausted).
    """
    queue = list(statuses or [])
    tail = [0.0] * (dim - 1)

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        status = queue.pop(0) if queue else 200
        if status != 200:
            return httpx.Response(status, json={"error": {"message": "upstream boom"}})
        payload = json.loads(request.content)
        texts = payload["input"]
        data = [
            {
                "object": "embedding",
                "index": i,
                "embedding": [_marker_value(text), *tail],
            }
            for i, text in enumerate(texts)
        ]
        if reverse_data:
            data = list(reversed(data))
        return httpx.Response(
            200,
            json={
                "object": "list",
                "data": data,
                "model": payload.get("model"),
                "usage": {"prompt_tokens": len(texts), "total_tokens": len(texts)},
            },
        )

    return handler


def _openai_provider(api_key: str, transport: httpx.MockTransport, model: str = OPENAI_MODEL):
    return _attr("OpenAIEmbeddingProvider")(model=model, api_key=api_key, transport=transport)


def _provider_dim(provider) -> int:
    dim = getattr(provider, "dim", None)
    if not isinstance(dim, int) or dim <= 0:
        pytest.fail(f"provider.dim must be a positive int per the Protocol, got {dim!r}")
    return dim


def _never_called(request: httpx.Request) -> httpx.Response:
    raise AssertionError(f"no HTTP request expected here: {request.method} {request.url}")


def _openai_dim(model: str = OPENAI_MODEL) -> int:
    """The adapter's own declared dim — mocked responses must match it, so a
    defensive `arr.shape[1] == self.dim` check in the adapter stays valid."""
    probe = _openai_provider(SENTINEL_KEY, httpx.MockTransport(_never_called), model)
    return _provider_dim(probe)


@contextlib.contextmanager
def _library_loggers_unmuted():
    """Reproduce the repo's own process-wide INFO logging (LESSONS T-014).

    onrecord's ingest entrypoints call `logging.basicConfig(level=INFO)`, and
    httpx's own logger is NOTSET by default so it inherits root — that is the
    exact condition under which httpx emitted a full keyed URL at INFO in
    T-014. The baseline is restored afterwards; an implementation that
    silences/redacts library loggers AROUND its own keyed request still wins,
    because that happens inside the call, after this setup.
    """
    root = logging.getLogger()
    previous_root = root.level
    library = [logging.getLogger(name) for name in ("httpx", "httpcore", "openai")]
    previous = [(lg, lg.level, lg.propagate) for lg in library]
    logging.basicConfig(level=logging.INFO)
    root.setLevel(logging.INFO)
    for lg in library:
        lg.setLevel(logging.NOTSET)
        lg.propagate = True
    try:
        yield
    finally:
        root.setLevel(previous_root)
        for lg, level, propagate in previous:
            lg.setLevel(level)
            lg.propagate = propagate


def _leaking_records(caplog, secret: str) -> list[tuple[str, str]]:
    return [(r.name, r.getMessage()) for r in caplog.records if secret in r.getMessage()]


# ==========================================================================
# AC-1 — cache hit: a second identical embed_corpus run makes ZERO provider
# calls and leaves the matrix untouched.
# ==========================================================================


def test_module_exposes_documented_public_api():
    # spec(T-021:AC-1)
    mod = _module()
    expected = [
        "EmbeddingProvider",
        "OpenAIEmbeddingProvider",
        "PROVIDERS",
        "get_provider",
        "ProviderNotConfigured",
        "EmbeddingStore",
        "CorruptStore",
        "cosine_top_k",
    ]
    missing = [name for name in expected if not hasattr(mod, name)]
    assert missing == [], f"onrecord.rag.embeddings is missing public API symbols: {missing}"


def test_second_embed_corpus_run_makes_zero_provider_calls():
    # spec(T-021:AC-1)
    pairs = _pairs(4)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())

    second = FakeProvider()
    store.embed_corpus(pairs, second)

    assert second.calls == [], (
        f"a fully-cached re-run must not call the provider at all (this is the "
        f"spec's content-hash cache requirement — a paid re-embed otherwise), "
        f"got {second.calls}"
    )


def test_second_embed_corpus_run_leaves_matrix_unchanged():
    # spec(T-021:AC-1)
    pairs = _pairs(4)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    before = np.array(store.matrix, copy=True)

    store.embed_corpus(pairs, FakeProvider())

    assert store.matrix.shape == before.shape, (
        f"a fully-cached re-run must not append rows: {before.shape} -> {store.matrix.shape}"
    )
    assert np.array_equal(store.matrix, before), "a fully-cached re-run must not alter any row"


def test_cache_hit_survives_save_load_round_trip(tmp_path):
    # spec(T-021:AC-1)
    pairs = _pairs(4)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    store.save(tmp_path / "store")

    reloaded = _load_store(tmp_path / "store")
    provider = FakeProvider()
    reloaded.embed_corpus(pairs, provider)

    assert provider.calls == [], (
        f"the cache must survive save/load — a re-freeze against a persisted "
        f"store must make zero provider calls, got {provider.calls}"
    )


# ==========================================================================
# AC-2 — incremental embed, id-keyed alignment, fp16 L2-normalized rows,
# dim-scoped cache keys (M-9).
# ==========================================================================


def test_incremental_run_sends_only_novel_texts_to_provider():
    # spec(T-021:AC-2)
    cached = _pairs(3)
    novel = [("c3", "brand new three"), ("c4", "brand new four")]
    store = _new_store()
    store.embed_corpus(cached, FakeProvider())

    provider = FakeProvider()
    store.embed_corpus(cached + novel, provider)

    assert provider.texts_seen == ["brand new three", "brand new four"], (
        f"only the 2 uncached texts may be sent, in first-appearance order; got "
        f"{provider.texts_seen}"
    )


def test_rows_for_maps_every_hash_to_its_own_row():
    # spec(T-021:AC-2)
    cached = _pairs(3)
    novel = [("c3", "brand new three"), ("c4", "brand new four")]
    store = _new_store()
    store.embed_corpus(cached, FakeProvider())
    store.embed_corpus(cached + novel, FakeProvider())

    rows = store.rows_for(_hashes_for(cached + novel))

    assert rows == [0, 1, 2, 3, 4], (
        f"rows are first-appearance order across ALL runs: the 3 cached pairs keep "
        f"rows 0..2 and the 2 novel pairs append at 3..4; got {rows}"
    )


def test_rows_for_returns_none_for_an_unknown_hash():
    # spec(T-021:AC-2)
    pairs = _pairs(2)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())

    unknown = _content_hash(FAKE_MODEL, 4, "never embedded")
    rows = store.rows_for([unknown, _content_hash(FAKE_MODEL, 4, "t 0")])

    assert rows == [None, 0], f"an absent hash maps to None, never to a bogus row: {rows}"


def test_entry_for_records_the_correct_chunk_id_per_hash():
    # spec(T-021:AC-2)
    pairs = _pairs(3) + [("c9", "extra nine")]
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())

    recorded = {
        chunk_id: store.entry_for(_content_hash(FAKE_MODEL, 4, text)) for chunk_id, text in pairs
    }

    assert recorded == {
        "c0": {"row": 0, "chunk_id": "c0"},
        "c1": {"row": 1, "chunk_id": "c1"},
        "c2": {"row": 2, "chunk_id": "c2"},
        "c9": {"row": 3, "chunk_id": "c9"},
    }, f"entry_for must return exactly {{'row', 'chunk_id'}} per hash; got {recorded}"


def test_stored_rows_are_l2_normalized_fp16_of_provider_vectors():
    # spec(T-021:AC-2)
    pairs = _pairs(3)
    provider = FakeProvider()
    store = _new_store()
    store.embed_corpus(pairs, provider)

    assert store.matrix.dtype == np.float16, (
        f"the packed matrix is fp16 (0.78 GB at 265K x 1536 — fp32 would double it): "
        f"got {store.matrix.dtype}"
    )
    for i, (_chunk_id, text) in enumerate(pairs):
        expected = _l2(_fake_vector(text, provider.dim, provider.model))
        row = store.matrix[i].astype(np.float32)
        assert np.allclose(row, expected, atol=1e-3), (
            f"row {i} must be the L2-normalized provider vector within fp16 tolerance: "
            f"{row} != {expected}"
        )
        assert float(np.linalg.norm(row)) == pytest.approx(1.0, abs=2e-3), (
            f"rows are normalized ONCE at ingest so cosine is a plain dot product; "
            f"row {i} has norm {float(np.linalg.norm(row))}"
        )


def test_cache_key_is_dim_scoped_so_a_dim_change_cannot_poison_it():
    # spec(T-021:AC-2)
    # plan-review M-9: same model name, different `dimensions` -> different key.
    text = "identical text at two dimensionalities"
    store = _new_store()
    store.embed_corpus([("c0", text)], FakeProvider(dim=4, model="shared-model"))

    hash_dim4 = _content_hash("shared-model", 4, text)
    hash_dim8 = _content_hash("shared-model", 8, text)

    assert store.rows_for([hash_dim4, hash_dim8]) == [0, None], (
        "the dim is part of the cache key, so the same text embedded at dim 8 must "
        "MISS against a dim-4 store instead of colliding onto its row"
    )


def test_permuted_store_with_extra_rows_resolves_by_hash_not_position():
    # spec(T-021:AC-2)
    # C-3 adversarial: same 4 texts, different insertion order, PLUS 2 extra
    # rows appended. Row order is first-appearance order across all runs, so
    # position is meaningless; only hash -> row -> chunk_id is authoritative.
    pairs = _pairs(4)
    reference = _new_store()
    reference.embed_corpus(pairs, FakeProvider())

    permuted_pairs = [pairs[2], pairs[0], pairs[3], pairs[1], ("c4", "t 4"), ("c5", "t 5")]
    permuted = _new_store()
    permuted.embed_corpus(permuted_pairs, FakeProvider())

    hashes = _hashes_for(pairs)
    assert reference.rows_for(hashes) == [0, 1, 2, 3]
    assert permuted.rows_for(hashes) == [1, 3, 0, 2], (
        f"rows must follow first-appearance order in THIS store, not the caller's "
        f"pair order; got {permuted.rows_for(hashes)}"
    )
    for (chunk_id, _text), h in zip(pairs, hashes, strict=True):
        entry = permuted.entry_for(h)
        assert entry["chunk_id"] == chunk_id, (
            f"hash -> chunk_id correspondence must survive a permuted, extended "
            f"store: {h[:8]} recorded {entry!r}, expected chunk_id {chunk_id}"
        )
        assert np.array_equal(
            permuted.matrix[entry["row"]], reference.matrix[reference.entry_for(h)["row"]]
        ), f"the vector reached via hash must be identical in both stores for {chunk_id}"
    assert not np.array_equal(permuted.matrix[0], reference.matrix[0]), (
        "the adversarial point: a consumer that indexed positionally (row i == "
        "pairs[i]) would silently read the WRONG chunk's vector here"
    )


def test_swapped_chunk_ids_are_visible_through_entry_for(tmp_path):
    # spec(T-021:AC-2)
    # C-3 adversarial: a store whose hashes all match and whose length checks
    # all pass, but whose recorded chunk_ids have drifted. `len(entries) ==
    # matrix.shape[0]` proves NOTHING — only id-level verification catches it.
    pairs = _pairs(6)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    path = tmp_path / "store"
    store.save(path)

    entries_path = path / "entries.json"
    entries = json.loads(entries_path.read_text(encoding="utf-8"))
    hashes = _hashes_for(pairs)
    entries[hashes[0]]["chunk_id"], entries[hashes[1]]["chunk_id"] = (
        entries[hashes[1]]["chunk_id"],
        entries[hashes[0]]["chunk_id"],
    )
    entries_path.write_text(json.dumps(entries), encoding="utf-8")

    reloaded = _load_store(path)

    assert len(entries) == reloaded.matrix.shape[0] == 6, (
        "precondition of the adversarial case: the store is structurally valid, "
        "so a length-equality check passes while the alignment is wrong"
    )
    assert reloaded.entry_for(hashes[0])["chunk_id"] == "c1", (
        "entry_for must report the chunk_id RECORDED on disk (not one silently "
        "reconstructed from position), which is what lets a consumer detect drift"
    )
    row = reloaded.matrix[reloaded.entry_for(hashes[0])["row"]].astype(np.float32)
    assert np.allclose(row, _l2(_fake_vector("t 0", 4, FAKE_MODEL)), atol=1e-3), (
        "the vector itself is still 't 0' — the chunk_id is the ONLY signal that "
        "the id-level correspondence broke"
    )


# ==========================================================================
# AC-3 — store round-trip, on-disk shape, atomic save.
# ==========================================================================


def test_save_load_round_trip_preserves_dtype_shape_and_entries(tmp_path):
    # spec(T-021:AC-3)
    pairs = _pairs(5)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    store.save(tmp_path / "store")

    reloaded = _load_store(tmp_path / "store")

    assert reloaded.matrix.dtype == np.float16
    assert reloaded.matrix.shape == store.matrix.shape == (5, 4)
    assert np.array_equal(reloaded.matrix, store.matrix)
    hashes = _hashes_for(pairs)
    assert [reloaded.entry_for(h) for h in hashes] == [store.entry_for(h) for h in hashes]
    assert sorted(reloaded.entry_for(h)["row"] for h in hashes) == [0, 1, 2, 3, 4], (
        "every row must be claimed by exactly one hash after a round-trip"
    )


def test_entries_json_on_disk_maps_hash_to_row_and_chunk_id(tmp_path):
    # spec(T-021:AC-3)
    pairs = _pairs(3)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    store.save(tmp_path / "store")

    entries = json.loads((tmp_path / "store" / "entries.json").read_text(encoding="utf-8"))

    assert entries == {
        _content_hash(FAKE_MODEL, 4, "t 0"): {"row": 0, "chunk_id": "c0"},
        _content_hash(FAKE_MODEL, 4, "t 1"): {"row": 1, "chunk_id": "c1"},
        _content_hash(FAKE_MODEL, 4, "t 2"): {"row": 2, "chunk_id": "c2"},
    }, f"entries.json is hash -> {{'row', 'chunk_id'}} exactly; got {entries}"


def test_saved_matrix_file_is_float16_on_disk(tmp_path):
    # spec(T-021:AC-3)
    # Adversarial: fp32 leaking into the packed store doubles a 0.78 GB
    # resident matrix and is invisible to any in-memory assertion that runs
    # before the save.
    pairs = _pairs(5)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    store.save(tmp_path / "store")

    raw = np.load(tmp_path / "store" / "matrix.npy")

    assert raw.dtype == np.float16, f"matrix.npy must be fp16 on disk, got {raw.dtype}"
    assert raw.shape == (5, 4)
    assert raw.nbytes == 5 * 4 * 2, (
        f"fp16 packing means exactly 2 bytes per component (N*dim*2 = 40), got {raw.nbytes}"
    )


def test_load_missing_directory_raises_file_not_found(tmp_path):
    # spec(T-021:AC-3)
    missing = tmp_path / "no-such-store"

    with pytest.raises(FileNotFoundError) as excinfo:
        _load_store(missing)

    assert "no-such-store" in str(excinfo.value), (
        f"the error must name the missing store path, got {excinfo.value!r}"
    )


def test_interrupted_save_leaves_the_previous_store_loadable(tmp_path, monkeypatch):
    # spec(T-021:AC-3)
    # Atomicity asserted by BEHAVIOR, not by spying on os.replace: whatever a
    # crashed save leaves behind, the previously-saved store must still load
    # intact and self-consistent.
    #
    # `np.save` here writes its file and THEN raises ("raising after the first
    # file", per AC-3) — the realistic mid-save crash, where the first file has
    # already hit the disk. That ordering is what makes this test bite in BOTH
    # in-place-write orders: matrix-first leaves a new matrix beside old
    # entries, entries-first leaves new entries beside an old matrix, and both
    # produce a store that is no longer the one this test saved. Only
    # temp-names-then-os.replace survives.
    path = tmp_path / "store"
    first_pairs = _pairs(3)
    first = _new_store()
    first.embed_corpus(first_pairs, FakeProvider())
    first.save(path)
    expected_matrix = np.array(first.matrix, copy=True)

    second = _new_store()
    second.embed_corpus(first_pairs + [("c7", "seven"), ("c8", "eight")], FakeProvider())
    monkeypatch.setattr(np, "save", _save_then_fail)
    with pytest.raises(OSError):
        second.save(path)
    monkeypatch.undo()

    reloaded = _load_store(path)
    assert np.array_equal(reloaded.matrix, expected_matrix), (
        "a save interrupted mid-write must leave the PREVIOUS store fully intact "
        "(write both files to temp names, then os.replace)"
    )
    assert [reloaded.entry_for(h) for h in _hashes_for(first_pairs)] == [
        {"row": 0, "chunk_id": "c0"},
        {"row": 1, "chunk_id": "c1"},
        {"row": 2, "chunk_id": "c2"},
    ]
    assert reloaded.rows_for(_hashes_for([("c7", "seven")])) == [None], (
        "the interrupted save must not have leaked the new run's entries onto the "
        "old matrix — that is exactly the silent mis-map the atomic contract bans"
    )


def _save_then_fail(*args, **kwargs):
    """Let np.save write its file, then blow up — see the test above."""
    _REAL_NP_SAVE(*args, **kwargs)
    raise OSError("simulated crash immediately after np.save wrote its file")


# ==========================================================================
# AC-4 — cosine_top_k on hand-computable vectors.
# ==========================================================================


def test_cosine_top_k_returns_hand_computed_order_and_scores():
    # spec(T-021:AC-4)
    store = _build_cosine_store([[1, 0, 0, 0], [0, 1, 0, 0], [1, 1, 0, 0], [-1, 0, 0, 0]])
    query = np.array([2, 0, 0, 0], dtype=np.float32)  # unnormalized on purpose

    results = _attr("cosine_top_k")(store, query, 4)

    assert [row for row, _ in results] == [0, 2, 1, 3], (
        f"expected order by cosine similarity 1.0 > 0.7071 > 0.0 > -1.0; got {results}"
    )
    expected_scores = [1.0, 0.7071067811865476, 0.0, -1.0]
    for (row, score), expected in zip(results, expected_scores, strict=True):
        assert score == pytest.approx(expected, abs=1e-3), (
            f"row {row}: cosine must be the dot product of L2-normalized vectors "
            f"(query normalized too), expected {expected}, got {score}"
        )


def test_cosine_top_k_breaks_ties_by_ascending_row_index():
    # spec(T-021:AC-4)
    store = _build_cosine_store([[1, 0, 0, 0], [0, 1, 0, 0], [1, 0, 0, 0], [0, 1, 0, 0]])
    query = np.array([1, 0, 0, 0], dtype=np.float32)

    results = _attr("cosine_top_k")(store, query, 4)

    assert [row for row, _ in results] == [0, 2, 1, 3], (
        f"equal scores must be ordered by ascending row index (deterministic ties); got {results}"
    )


def test_cosine_top_k_truncates_to_k():
    # spec(T-021:AC-4)
    store = _build_cosine_store([[1, 0, 0, 0], [0, 1, 0, 0], [1, 1, 0, 0], [-1, 0, 0, 0]])
    query = np.array([1, 0, 0, 0], dtype=np.float32)

    results = _attr("cosine_top_k")(store, query, 2)

    assert [row for row, _ in results] == [0, 2], f"k=2 must return the top 2 rows: {results}"


def test_cosine_top_k_with_k_larger_than_the_corpus_returns_every_row():
    # spec(T-021:AC-4)
    store = _build_cosine_store([[1, 0, 0, 0], [0, 1, 0, 0], [1, 1, 0, 0]])
    query = np.array([1, 0, 0, 0], dtype=np.float32)

    results = _attr("cosine_top_k")(store, query, 25)

    assert len(results) == 3, f"k > N must clamp to N rows, not pad or raise: {results}"


def test_cosine_top_k_blocked_path_matches_unblocked():
    # spec(T-021:AC-4)
    store = _build_cosine_store(
        [[1, 0, 0, 0], [0, 1, 0, 0], [1, 1, 0, 0], [-1, 0, 0, 0], [0, 0, 1, 0]]
    )
    query = np.array([0.5, 0.25, 0, 0], dtype=np.float32)
    cosine_top_k = _attr("cosine_top_k")

    blocked = cosine_top_k(store, query, 5, block_rows=2)
    unblocked = cosine_top_k(store, query, 5, block_rows=8192)

    assert [row for row, _ in blocked] == [row for row, _ in unblocked], (
        f"blocking is a memory bound, never a semantic change: {blocked} != {unblocked}"
    )
    for (_row, a), (_row2, b) in zip(blocked, unblocked, strict=True):
        assert a == pytest.approx(b, abs=1e-6)


# ==========================================================================
# AC-5 — OpenAI-shaped adapter over httpx.MockTransport (zero network) and
# the key-presence/key-absence branches (plan-review I-5).
# ==========================================================================


def test_openai_adapter_posts_model_url_and_bearer_header():
    # spec(T-021:AC-5)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    transport = httpx.MockTransport(_openai_handler(dim, requests))
    provider = _openai_provider(SENTINEL_KEY, transport)

    provider.embed(["doc-0", "doc-1", "doc-2"])

    assert len(requests) == 1
    request = requests[0]
    assert request.method == "POST"
    assert request.url.host == "api.openai.com"
    assert request.url.path == "/v1/embeddings"
    assert request.headers.get("authorization") == f"Bearer {SENTINEL_KEY}"
    body = json.loads(request.content)
    assert body["model"] == OPENAI_MODEL
    assert body["input"] == ["doc-0", "doc-1", "doc-2"], (
        f"the request must carry the texts unchanged and in order: {body.get('input')}"
    )


def test_openai_adapter_returns_float32_rows_in_input_order():
    # spec(T-021:AC-5)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    # The API returns `data` with an explicit `index` per row; this mock hands
    # it back REVERSED, so an adapter that trusts list order silently permutes
    # every embedding. Row order == input order is the Protocol's contract.
    transport = httpx.MockTransport(_openai_handler(dim, requests, reverse_data=True))
    provider = _openai_provider(SENTINEL_KEY, transport)

    out = provider.embed(["doc-0", "doc-1", "doc-2"])

    assert isinstance(out, np.ndarray)
    assert out.dtype == np.float32, f"the Protocol pins float32 output, got {out.dtype}"
    assert out.shape == (3, dim)
    assert [float(row[0]) for row in out] == [0.0, 1.0, 2.0], (
        "rows must be ordered by the response's `index` field (== input order), not "
        "by the order the objects happen to arrive in"
    )


def test_openai_adapter_splits_513_texts_into_two_requests():
    # spec(T-021:AC-5)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    transport = httpx.MockTransport(_openai_handler(dim, requests))
    provider = _openai_provider(SENTINEL_KEY, transport)
    texts = [f"doc-{i}" for i in range(513)]

    out = provider.embed(texts)

    sizes = [len(json.loads(r.content)["input"]) for r in requests]
    assert len(requests) == 2, f"513 texts must split into 2 requests, got sizes {sizes}"
    assert max(sizes) <= 512, f"no request may exceed the 512-text batch cap: {sizes}"
    assert sum(sizes) == 513
    assert out.shape == (513, dim)
    assert [float(row[0]) for row in out] == [float(i) for i in range(513)], (
        "batches must be concatenated back in input order"
    )


def test_openai_adapter_retries_429_then_succeeds(monkeypatch):
    # spec(T-021:AC-5)
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    transport = httpx.MockTransport(_openai_handler(dim, requests, statuses=[429]))
    provider = _openai_provider(SENTINEL_KEY, transport)

    out = provider.embed(["doc-0", "doc-1"])

    assert len(requests) == 2, (
        f"a 429 must be retried with backoff, not surfaced: {len(requests)} request(s) made"
    )
    assert out.shape == (2, dim)
    assert [float(row[0]) for row in out] == [0.0, 1.0]


def test_openai_adapter_raises_after_exhausting_retries_on_5xx(monkeypatch):
    # spec(T-021:AC-5)
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    transport = httpx.MockTransport(_openai_handler(dim, requests, statuses=[500] * 20))
    provider = _openai_provider(SENTINEL_KEY, transport)

    # The concrete exception type is the implementer's choice — only "fails
    # loudly, bounded" is frozen here.
    with pytest.raises(Exception) as excinfo:
        provider.embed(["doc-0"])

    assert not isinstance(excinfo.value, AssertionError)
    assert 2 <= len(requests) <= 5, (
        f"a permanently-500 batch must be retried (max 3) and then FAIL LOUDLY — "
        f"never silently return partial or zero vectors; requests made: {len(requests)}"
    )


def test_missing_openai_key_raises_provider_not_configured(monkeypatch):
    # spec(T-021:AC-5)
    # plan-review I-5: delenv(raising=False) so the branch is pinned whether or
    # not the ambient environment happens to have a key.
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    provider_not_configured = _attr("ProviderNotConfigured")

    with pytest.raises(provider_not_configured) as excinfo:
        _attr("OpenAIEmbeddingProvider")(model=OPENAI_MODEL)

    assert "OPENAI_API_KEY" in str(excinfo.value), (
        f"the error must be actionable — it names the env var to set; got {excinfo.value!r}"
    )


def test_present_openai_key_constructs_without_raising(monkeypatch):
    # spec(T-021:AC-5)
    # The mirrored branch of I-5: neither side may be environmentally lucky.
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)

    provider = _attr("OpenAIEmbeddingProvider")(model=OPENAI_MODEL)

    assert provider.model == OPENAI_MODEL
    assert _provider_dim(provider) > 0


def test_get_provider_defaults_to_the_openai_adapter(monkeypatch):
    # spec(T-021:AC-5)
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)
    monkeypatch.delenv("ONRECORD_EMBED_PROVIDER", raising=False)
    monkeypatch.delenv("ONRECORD_EMBED_MODEL", raising=False)

    provider = _attr("get_provider")()

    assert isinstance(provider, _attr("OpenAIEmbeddingProvider"))
    assert provider.model == OPENAI_MODEL, (
        f"default model is text-embedding-3-small; got {provider.model!r}"
    )


def test_get_provider_honors_the_model_override_env(monkeypatch):
    # spec(T-021:AC-5)
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)
    monkeypatch.setenv("ONRECORD_EMBED_PROVIDER", "openai")
    monkeypatch.setenv("ONRECORD_EMBED_MODEL", "text-embedding-3-large")

    provider = _attr("get_provider")()

    assert provider.model == "text-embedding-3-large", (
        f"ONRECORD_EMBED_MODEL overrides the adapter default; got {provider.model!r}"
    )


def test_get_provider_without_a_key_raises_instead_of_returning_a_fake(monkeypatch):
    # spec(T-021:AC-5)
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("ONRECORD_EMBED_PROVIDER", raising=False)

    with pytest.raises(_attr("ProviderNotConfigured")) as excinfo:
        _attr("get_provider")()

    assert "OPENAI_API_KEY" in str(excinfo.value), (
        "locked decision: an unconfigured provider raises an actionable error and "
        "NEVER silently returns a fake (fakes are test-injected only)"
    )


def test_providers_registry_holds_openai_and_no_speculative_voyage():
    # spec(T-021:AC-5)
    providers = _attr("PROVIDERS")

    assert isinstance(providers, dict)
    assert "openai" in providers, f"PROVIDERS must register the openai adapter: {providers}"
    assert "voyage" not in providers, (
        "the Voyage adapter is an OPEN QUESTION for the owner — it must not be "
        "implemented speculatively (ticket Out of Scope)"
    )


# ==========================================================================
# AC-6 — secret-leak sentinel at the ROOT logger (LESSONS.md T-014).
# ==========================================================================


def test_no_log_record_contains_the_api_key_on_the_success_path(caplog):
    # spec(T-021:AC-6)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    transport = httpx.MockTransport(_openai_handler(dim, requests))
    provider = _openai_provider(SENTINEL_KEY, transport)

    with _library_loggers_unmuted(), caplog.at_level(logging.INFO):  # root: EVERY logger
        provider.embed(["doc-0", "doc-1"])

    assert requests, "precondition: the mocked request must actually have been made"
    assert _leaking_records(caplog, SENTINEL_KEY) == [], (
        f"the API key must never reach ANY log record — root + library loggers, "
        f"httpx logs full request URLs at INFO (LESSONS T-014): "
        f"{_leaking_records(caplog, SENTINEL_KEY)}"
    )
    assert SENTINEL_KEY not in caplog.text


def test_no_log_record_contains_the_api_key_on_the_error_path(caplog, monkeypatch):
    # spec(T-021:AC-6)
    # Adversarial: error paths are where keys leak — a naive
    # `log.warning("embed failed: %s", exc)` re-emits httpx's request repr.
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    transport = httpx.MockTransport(_openai_handler(dim, requests, statuses=[401, 500, 500, 500]))
    provider = _openai_provider(SENTINEL_KEY, transport)

    with _library_loggers_unmuted(), caplog.at_level(logging.INFO):
        with pytest.raises(Exception) as excinfo:
            provider.embed(["doc-0"])

    assert not isinstance(excinfo.value, AssertionError)
    assert _leaking_records(caplog, SENTINEL_KEY) == [], (
        f"the API key must never reach ANY log record on a failing request either: "
        f"{_leaking_records(caplog, SENTINEL_KEY)}"
    )
    assert SENTINEL_KEY not in caplog.text
    assert SENTINEL_KEY not in str(excinfo.value), (
        "nor may it appear in exception text (it propagates into tracebacks and "
        "any caller's own logging)"
    )
    assert SENTINEL_KEY not in repr(excinfo.value)


def test_provider_repr_does_not_expose_the_api_key():
    # spec(T-021:AC-6)
    provider = _openai_provider(SENTINEL_KEY, httpx.MockTransport(_never_called))

    assert SENTINEL_KEY not in repr(provider)
    assert SENTINEL_KEY not in str(provider), (
        "a default dataclass/attrs repr embeds the key and lands it in every log "
        "line that interpolates the provider (LESSONS T-014)"
    )


# ==========================================================================
# AC-7 — CorruptStore validation at load (plan-review I-10c).
# ==========================================================================


def test_a_valid_store_loads_clean(tmp_path):
    # spec(T-021:AC-7)
    path = tmp_path / "store"
    matrix, entries = _valid_raw_store(path)

    store = _load_store(path)

    assert store.matrix.dtype == np.float16
    assert np.array_equal(store.matrix, matrix)
    for h, entry in entries.items():
        assert store.entry_for(h) == entry


def test_load_raises_corrupt_store_on_entry_row_count_mismatch(tmp_path):
    # spec(T-021:AC-7)
    path = tmp_path / "store"
    matrix, entries = _valid_raw_store(path, rows=3)
    entries.pop(next(iter(entries)))  # 2 entries vs a 3-row matrix
    _write_raw_store(path, matrix, entries)

    with pytest.raises(_attr("CorruptStore")) as excinfo:
        _load_store(path)

    message = str(excinfo.value)
    assert "entries" in message and "matrix" in message, (
        f"the error must name the mismatching files, got {message!r}"
    )


def test_load_raises_corrupt_store_on_a_duplicate_row_index(tmp_path):
    # spec(T-021:AC-7)
    path = tmp_path / "store"
    matrix, entries = _valid_raw_store(path, rows=3)
    keys = list(entries)
    entries[keys[1]]["row"] = 0  # two hashes claiming row 0
    _write_raw_store(path, matrix, entries)

    with pytest.raises(_attr("CorruptStore")) as excinfo:
        _load_store(path)

    message = str(excinfo.value).lower()
    assert "entries" in message, f"the error must name entries.json, got {message!r}"
    assert "duplicate" in message or "row" in message, (
        f"the error must name the defect (duplicate row index), got {message!r}"
    )


def test_load_raises_corrupt_store_on_an_out_of_range_row_index(tmp_path):
    # spec(T-021:AC-7)
    path = tmp_path / "store"
    matrix, entries = _valid_raw_store(path, rows=3)
    keys = list(entries)
    entries[keys[2]]["row"] = 7  # beyond the 3-row matrix
    _write_raw_store(path, matrix, entries)

    with pytest.raises(_attr("CorruptStore")) as excinfo:
        _load_store(path)

    message = str(excinfo.value).lower()
    assert "entries" in message
    assert "row" in message, f"the error must name the offending row index, got {message!r}"


def test_load_raises_corrupt_store_on_a_float32_matrix(tmp_path):
    # spec(T-021:AC-7)
    # Adversarial: fp32 leaking into the packed store must be rejected at the
    # door, not silently accepted (it doubles resident memory and breaks the
    # dtype half of the round-trip contract).
    path = tmp_path / "store"
    matrix, entries = _valid_raw_store(path, rows=3)
    _write_raw_store(path, matrix.astype(np.float32), entries)

    with pytest.raises(_attr("CorruptStore")) as excinfo:
        _load_store(path)

    message = str(excinfo.value).lower()
    assert "matrix" in message, f"the error must name matrix.npy, got {message!r}"
    assert "dtype" in message or "fp16" in message or "float16" in message, (
        f"the error must name the dtype defect, got {message!r}"
    )


# ==========================================================================
# AC-8 — crash-resume checkpointing (plan-review I-10b): a multi-hour,
# ~$30-80, 265K-item run must never pay twice for the same text.
# ==========================================================================


def test_checkpoint_is_written_after_every_checkpoint_every_items(tmp_path):
    # spec(T-021:AC-8)
    pairs = _pairs(6)
    checkpoint_dir = tmp_path / "ckpt"
    provider = FakeProvider(fail_on_call=3)
    store = _new_store()

    with pytest.raises(ProviderBoom):
        store.embed_corpus(pairs, provider, checkpoint_dir=checkpoint_dir, checkpoint_every=2)

    assert all(len(batch) <= 2 for batch in provider.calls), (
        f"checkpointing every N newly-embedded items requires provider batches of "
        f"at most N items; got batch sizes {[len(b) for b in provider.calls]}"
    )
    checkpoint = _load_store(checkpoint_dir)
    assert checkpoint.matrix.shape == (4, 4), (
        f"the 2 completed batches (4 items) must be on disk when batch 3 dies; "
        f"got {checkpoint.matrix.shape}"
    )
    assert checkpoint.rows_for(_hashes_for(pairs)) == [0, 1, 2, 3, None, None], (
        "the checkpoint holds exactly the successfully-embedded pairs, id-keyed"
    )


def test_resume_after_a_crash_embeds_only_the_missing_pairs(tmp_path):
    # spec(T-021:AC-8)
    pairs = _pairs(6)
    checkpoint_dir = tmp_path / "ckpt"
    store = _new_store()
    with pytest.raises(ProviderBoom):
        store.embed_corpus(
            pairs, FakeProvider(fail_on_call=3), checkpoint_dir=checkpoint_dir, checkpoint_every=2
        )

    resumed = _load_store(checkpoint_dir)
    provider = FakeProvider()
    resumed.embed_corpus(pairs, provider, checkpoint_dir=checkpoint_dir, checkpoint_every=2)

    assert provider.texts_seen == ["t 4", "t 5"], (
        f"resuming must re-embed ONLY the pairs the crash never stored — the "
        f"provider call count is the proof; got {provider.texts_seen}"
    )
    assert resumed.rows_for(_hashes_for(pairs)) == [0, 1, 2, 3, 4, 5]


def test_resume_never_re_embeds_an_already_stored_text(tmp_path):
    # spec(T-021:AC-8)
    # Adversarial: nothing that was successfully embedded and checkpointed may
    # be paid for twice. (The batch that died produced no vectors, so retrying
    # exactly those texts is correct — and is not double-embedding.)
    pairs = _pairs(6)
    checkpoint_dir = tmp_path / "ckpt"
    first = FakeProvider(fail_on_call=3)
    store = _new_store()
    with pytest.raises(ProviderBoom):
        store.embed_corpus(pairs, first, checkpoint_dir=checkpoint_dir, checkpoint_every=2)

    resumed = _load_store(checkpoint_dir)
    second = FakeProvider()
    resumed.embed_corpus(pairs, second, checkpoint_dir=checkpoint_dir, checkpoint_every=2)

    paid_twice = sorted(set(first.texts_returned) & set(second.texts_seen))
    assert paid_twice == [], (
        f"these texts were embedded successfully before the crash and sent again "
        f"after it — a duplicated spend on a ~$30-80 run: {paid_twice}"
    )


def test_resumed_store_equals_the_never_crashed_store(tmp_path):
    # spec(T-021:AC-8)
    pairs = _pairs(6)
    checkpoint_dir = tmp_path / "ckpt"
    crashed = _new_store()
    with pytest.raises(ProviderBoom):
        crashed.embed_corpus(
            pairs, FakeProvider(fail_on_call=3), checkpoint_dir=checkpoint_dir, checkpoint_every=2
        )
    resumed = _load_store(checkpoint_dir)
    resumed.embed_corpus(pairs, FakeProvider(), checkpoint_dir=checkpoint_dir, checkpoint_every=2)

    clean = _new_store()
    clean.embed_corpus(pairs, FakeProvider())

    assert resumed.matrix.shape == clean.matrix.shape == (6, 4)
    assert np.array_equal(resumed.matrix, clean.matrix), (
        "a resumed run must be byte-identical to an uninterrupted one — same rows, "
        "same first-appearance order"
    )
    hashes = _hashes_for(pairs)
    assert [resumed.entry_for(h) for h in hashes] == [clean.entry_for(h) for h in hashes]
