"""Failing tests for T-020 — RAG chunking + window/overlap recall sweep.

Encodes tickets/T-020.md AC-1..AC-7. These tests are FROZEN after the Test
Agent hands off: do not edit this file to make an implementation pass — fix
the implementation (`onrecord/rag/chunking.py`, `onrecord/rag/chunk_sweep.py`)
instead. Written adversarially: assumes nothing exists yet and nothing about
an implementer's good intentions.

Run with:
    uv run pytest tests/unit/rag/ -v

Zero network, zero keys, zero mocks of code under test: every assertion runs
real `onrecord.types.Doc` objects through the real `chunk_corpus` /
`chunk_sweep` and (except where the `retrieve_fn_factory` seam is the thing
under test) the real default BM25 retriever.

MODULE-PRESENCE GUARD (why every test starts with `_chunking()` /
`_sweep()`)
-------------------------------------------------------------------------
`onrecord/rag/chunking.py` and `onrecord/rag/chunk_sweep.py` are THIS
ticket's target files and do not exist yet — nor does the `onrecord.rag`
package. A module-level `import onrecord.rag.chunking` would blow this file
up with a pytest COLLECTION error, polluting every other in-flight ticket's
regression baseline. Instead `_require_module_spec(...)` +
`pytest.fail(...)` (the established idiom — see tests/unit/test_api.py,
tests/unit/test_scaffold.py, tests/unit/test_judgments.py) turns "module
missing" into one clean RED failure per test, never an uncaught
ImportError. `importlib.util.find_spec` RAISES ModuleNotFoundError (rather
than returning None) when a parent package in a dotted name is itself
missing, so both cases are normalized.

`tests/unit/rag/__init__.py` is an EMPTY shared file also created by T-021
in this wave (empty-`__init__` auto-merge precedent, wave 2 T-006/7/8) —
nothing may be put in it, so every helper below lives in this file.

=========================================================================
onrecord/rag/chunking.py — frozen contract
=========================================================================

    @dataclass(frozen=True)
    class Chunk:
        chunk_id: str
        doc_ids: list[str]
        text: str
        deep_link: str
        date: str
        source_type: str
        venue_type: str
        ticker: str | None
        jurisdiction: str | None
        speaker: str | None

    def chunk_corpus(docs: list[Doc], window: int = 1, overlap: int = 0)
            -> list[Chunk]: ...

Field ORDER is pinned (not just the name set): the ticket lists the fields
in exactly this order, and T-022/T-024 construct `Chunk`s against it.
Field DEFAULTS are deliberately NOT pinned — every construction below goes
through `chunk_corpus`.

**Validation** — `window >= 1` and `0 <= overlap < window`, else `ValueError`
whose message names the offending parameter ("window" / "overlap"). When
both rules are violated at once (e.g. `window=0, overlap=0`) the message
must name `window` — the window rule is checked first.

**Grouping** — a doc participates in windowing iff its id matches
`yt:<video>:seg<NNN>` (NNN = digits). Matching docs group per `<video>`,
are ordered by NNN NUMERICALLY (not by input-list order — input order is
arbitrary — and not lexicographically: ingest emits `f"seg{i:03d}"`, so a
long enough video yields `seg1000`, which string-sorts before `seg999`),
and merge into sliding windows of `window` segments with stride
`window - overlap`. Windows NEVER cross videos. ALL other docs — EDGAR
sections, and any `yt:`-ish id that does NOT match the pattern — pass
through as identity chunks UNCONDITIONALLY, at every (window, overlap)
setting (ticket Context + AC-3; they are already section-level).

**Window emission rule (Test Agent decision — the ticket's AC-2 example is
the spec, this is its general statement).** Windows start at offsets
`0, stride, 2*stride, ...` into a video's ordered segment list, and
emission STOPS after the first window whose end reaches the end of the list.
So for A(seg000..seg004) at window=3/overlap=1 (stride 2) the windows are
[0,1,2] and [2,3,4] — there is NO third window [4]: the tail is already
covered, and a redundant trailing window is the classic off-by-one here.
A genuinely uncovered short tail IS kept (n=4, window=3, overlap=0 → [0,1,2]
then [3]).

**chunk_id (Test Agent decision — the load-bearing one; ticket leaves the
singleton case open).**

    len(chunk.doc_ids) == 1  <=>  chunk.chunk_id == chunk.doc_ids[0]
    len(chunk.doc_ids) >  1   =>  chunk.chunk_id == f"{doc_ids[0]}+w{window}"

i.e. "identity chunk" is defined by the chunk covering exactly ONE doc, not
by the `window` argument. Rationale: (a) the ticket pins
`window=1, overlap=0` as the identity chunking for the ENTIRE corpus (every
chunk_id == doc_id), which this rule yields automatically; (b) a
single-segment video, or a single-doc tail window, at `window>1` is
observably indistinguishable from an identity chunk (same doc_ids, same
text, same metadata) — minting `X+w3` for it would give one doc two
different chunk ids for identical content; (c) T-022's `NonIdentityChunking`
guard is literally
`chunk.chunk_id == chunk.doc_ids[0] and len(chunk.doc_ids) == 1`, so this
rule makes that guard a total, unambiguous test of "single-doc chunk".
Note the `w{window}` suffix uses the WINDOW ARGUMENT, never
`len(doc_ids)` — B(seg000..seg001) at window=3 is `yt:B...:seg000+w3`
(ticket AC-2, verbatim).

**Doc ids are echoed VERBATIM** — `doc_ids` holds the exact input id
strings, in ascending segment order, never re-minted, re-cased, reshaped or
re-prefixed (the 49 judged `yt:VIDEO:segNNN` ids are the judgment set's
primary key — locked-decision).

**Text join** — `" ".join(doc.text for doc in constituent_docs)`, a single
space, no strip, no normalization (an empty constituent text therefore
contributes an empty segment to the join; pinned literally below).

**Metadata** — all 7 fields (`deep_link, date, source_type, venue_type,
ticker, jurisdiction, speaker`) come from the FIRST constituent doc,
verbatim.

**Chunk ORDER, deliberately NOT pinned:** the ticket pins no global output
ordering, so nothing here asserts where a video's chunks sit relative to
another video's or to the EDGAR identity chunks. What IS pinned: within one
video, windows appear in ascending start-segment order; and `chunk_corpus`
is deterministic (identical input -> identical output list, order included).

=========================================================================
onrecord/rag/chunk_sweep.py — frozen contract
=========================================================================

    def chunk_sweep(
        docs: list[Doc],
        judgments_path: str | Path,
        windows: tuple[int, ...] = (1, 2, 3, 4),
        overlaps: tuple[int, ...] = (0, 1),
        k_values: tuple[int, ...] = (5, 10),
        retrieve_fn_factory=None,
        min_grade: int = 1,
        manifest_dir: str | Path | None = None,
    ) -> dict: ...

`judgments_path` is the JSONL written by `onrecord.eval.judgments` — rows
`{"query_id", "query", "criterion", "doc_id", "grade"}`, grouped by
`query_id` exactly as `onrecord.eval.run._load_judgments` does.

**Grid** — the cartesian product of `windows` x `overlaps`, MINUS every
invalid cell (`overlap >= window`). At defaults that is 7 cells: (1,0),
(2,0), (2,1), (3,0), (3,1), (4,0), (4,1) — `(1,1)` is excluded, not an
error. Cell ORDER within `"cells"` is not pinned (the ticket pins none);
`best` is what must be deterministic.

**Coverage relevance** — per query, a CHUNK is coverage-relevant iff ANY of
its `doc_ids` carries `grade >= min_grade` in that query's judgments. This
is a different concept from T-025's answer-grade derivation (grade == 2) on
purpose; both thresholds are injected parameters so OQ-6 resolves by config
(plan-review I-6). A merged chunk covering two relevant docs is ONE
relevant chunk.

**recall@k** — per query: `|retrieved[:k] ∩ relevant_chunks| /
|relevant_chunks|`, then the arithmetic MEAN over judgment queries. A query
with ZERO coverage-relevant chunks contributes `0.0` and must never raise
(matches `onrecord.eval.metrics.recall_at_k`'s pinned convention).

**Default retrieval** — in-memory `InvertedIndex.build([...])` over
`Doc(id=chunk.chunk_id, text=chunk.text, <chunk metadata>)` + BM25
`ranked_search`, at a depth of at least `max(k_values)`. NOTHING is written
to disk — never `artifacts/index` (the real index stays corpus-doc-keyed).
`retrieve_fn_factory(chunks) -> retrieve_fn(query_text) -> list[chunk_id]`
is the injection seam (T-022+ re-runs the same sweep semantically); the
retrieve_fn is called with the judgment row's QUERY TEXT, not its query_id.

**Return / artifact shape** (exact top-level key set, all JSON-native so it
round-trips through `json.dumps`/`json.loads` unchanged):

    {"cells": [{"window": int, "overlap": int, "recall@5": float,
                "recall@10": float}, ...],   # one "recall@{k}" per k_value
     "best": <the winning cell dict>,
     "n_queries": int,
     "min_grade": int,
     "corpus_version": str,
     "retrieval": "bm25"}

`best` = max `"recall@10"`, ties broken by SMALLEST `(window, overlap)`
lexicographically — pinned against a scrambled `windows`/`overlaps` input
below, so it must be an explicit sort, not iteration luck. (`best` is only
exercised with a `k_values` containing 10; the ticket defines the tie-break
on `recall@10` and says nothing about a grid lacking it, so that case is
deliberately left unpinned.)

`corpus_version` — tolerant inline read of `<manifest_dir>/manifest.json`
(T-018's filename/`corpus_version` key): `manifest_dir=None`, a missing
dir, a missing file, corrupt JSON, or a manifest without the key all yield
`"unversioned"`.

`retrieval` is pinned to `"bm25"` for the DEFAULT retriever only — the
ticket names no other value, so nothing here pins what an injected
`retrieve_fn_factory` should report.

**Not frozen-tested, per the ticket:** the `main()` CLI (its flag set is not
specified by the ticket) and the `--plot` matplotlib path (dev dep;
font/renderer nondeterminism — same convention as T-019).
"""

from __future__ import annotations

import importlib.util
import json
from itertools import chain
from pathlib import Path

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from onrecord.types import Doc

# --------------------------------------------------------------------------
# Module-presence guards (see module docstring)
# --------------------------------------------------------------------------


def _require_module_spec(name: str, fail_message: str):
    """Return the module spec for `name`, or fail cleanly via pytest.fail."""
    try:
        spec = importlib.util.find_spec(name)
    except ModuleNotFoundError:
        spec = None
    if spec is None:
        pytest.fail(fail_message)
    return spec


def _chunking():
    _require_module_spec("onrecord.rag.chunking", "onrecord.rag.chunking missing")
    import onrecord.rag.chunking as chunking_module

    return chunking_module


def _sweep_module():
    _require_module_spec("onrecord.rag.chunk_sweep", "onrecord.rag.chunk_sweep missing")
    import onrecord.rag.chunk_sweep as sweep_module

    return sweep_module


def _chunk_corpus(docs, *args, **kwargs):
    return _chunking().chunk_corpus(docs, *args, **kwargs)


def _chunk_sweep(docs, judgments_path, **kwargs):
    return _sweep_module().chunk_sweep(docs, judgments_path, **kwargs)


# --------------------------------------------------------------------------
# Fixture builders (real Docs, no mocks)
# --------------------------------------------------------------------------

METADATA_FIELDS = (
    "deep_link",
    "date",
    "source_type",
    "venue_type",
    "ticker",
    "jurisdiction",
    "speaker",
)

CHUNK_FIELDS = ("chunk_id", "doc_ids", "text") + METADATA_FIELDS

VIDEO_A = "AAAAAAAAAAA"
VIDEO_B = "BBBBBBBBBBB"
VIDEO_C = "CCCCCCCCCCC"

DEFAULT_CELLS = ((1, 0), (2, 0), (2, 1), (3, 0), (3, 1), (4, 0), (4, 1))


def _yt_id(video: str, n: int) -> str:
    return f"yt:{video}:seg{n:03d}"


def _yt_doc(video: str, n: int, text: str | None = None, **overrides) -> Doc:
    """A caption-window Doc. `deep_link` and `speaker` deliberately VARY per
    segment so "metadata comes from the FIRST constituent doc" is provable
    (a real 75s window's deep_link carries its own start timestamp)."""
    fields = {
        "id": _yt_id(video, n),
        "text": text if text is not None else f"caption {video} window {n:03d}",
        "source_type": "youtube",
        "venue_type": "spoken",
        "date": "2024-03-01",
        "deep_link": f"https://www.youtube.com/watch?v={video}&t={n * 75}s",
        "ticker": None,
        "jurisdiction": "loudoun-county-va",
        "speaker": f"speaker-{n:03d}",
    }
    fields.update(overrides)
    return Doc(**fields)


def _edgar_doc(suffix: str, text: str | None = None, **overrides) -> Doc:
    """A section-level EDGAR Doc — never a windowing participant (AC-3)."""
    fields = {
        "id": f"edgar:0000320193-24-0001{suffix}:item1a",
        "text": text if text is not None else f"filing section {suffix} risk factors",
        "source_type": "filing",
        "venue_type": "written",
        "date": "2024-02-02",
        "deep_link": f"https://www.sec.gov/Archives/{suffix}.htm",
        "ticker": "AAPL",
        "jurisdiction": None,
        "speaker": None,
    }
    fields.update(overrides)
    return Doc(**fields)


def _mixed_corpus() -> list[Doc]:
    """yt (2 videos) + EDGAR, interleaved so nothing can rely on the yt docs
    being contiguous in the input list."""
    return [
        _yt_doc(VIDEO_A, 0),
        _edgar_doc("23"),
        _yt_doc(VIDEO_A, 1),
        _yt_doc(VIDEO_B, 0),
        _edgar_doc("24"),
        _yt_doc(VIDEO_A, 2),
        _yt_doc(VIDEO_B, 1),
    ]


def _by_id(chunks) -> dict:
    return {chunk.chunk_id: chunk for chunk in chunks}


def _doc_ids_map(chunks) -> dict:
    return {chunk.chunk_id: list(chunk.doc_ids) for chunk in chunks}


def _windows_of(chunks, video: str) -> list[tuple[str, ...]]:
    """Constituent-id tuples of the chunks belonging to `video`, in the order
    `chunk_corpus` emitted them (relative order WITHIN one video is pinned;
    the global list order is not)."""
    prefix = f"yt:{video}:"
    return [tuple(c.doc_ids) for c in chunks if c.doc_ids[0].startswith(prefix)]


def _seg_numbers(doc_ids) -> list[int]:
    return [int(doc_id.rsplit(":seg", 1)[1]) for doc_id in doc_ids]


def _judgment_row(query_id: str, query: str, doc_id: str, grade: int) -> dict:
    return {
        "query_id": query_id,
        "query": query,
        "criterion": "on-the-record discussion of the queried topic",
        "doc_id": doc_id,
        "grade": grade,
    }


def _write_judgments(path: Path, rows: list[dict]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        for row in rows:
            fh.write(json.dumps(row) + "\n")
    return path


# --------------------------------------------------------------------------
# Sweep fixtures, hand-computed (see each test for the arithmetic)
# --------------------------------------------------------------------------

# Video V: only seg000 carries the query term "substation", but seg001 is
# ALSO judged relevant. That is the whole point of the sweep: merging
# seg000+seg001 into one chunk makes the relevant material reachable by a
# query that only matches seg000.
MERGE_DOCS = [
    _yt_doc(VIDEO_C, 0, text="substation capacity"),
    _yt_doc(VIDEO_C, 1, text="the board discussed timelines"),
    _yt_doc(VIDEO_C, 2, text="unrelated budget talk"),
    _yt_doc(VIDEO_C, 3, text="adjourned for the evening"),
]

MERGE_JUDGMENTS = [
    _judgment_row("q1", "substation", _yt_id(VIDEO_C, 0), 2),
    _judgment_row("q1", "substation", _yt_id(VIDEO_C, 1), 1),
    _judgment_row("q1", "substation", _yt_id(VIDEO_C, 2), 0),
    _judgment_row("q1", "substation", _yt_id(VIDEO_C, 3), 0),
]

# Hand-computed recall for MERGE_DOCS + MERGE_JUDGMENTS at min_grade=1,
# default BM25 retrieval, k in {5, 10} (every cell has <= 4 chunks, so k
# never truncates here — only the chunking changes the numbers):
#   (1,0) chunks [0][1][2][3]      relevant {0,1}   retrieved {0}     -> 0.5
#   (2,0) chunks [0,1][2,3]        relevant {[0,1]} retrieved {[0,1]} -> 1.0
#   (2,1) chunks [0,1][1,2][2,3]   relevant {[0,1],[1,2]} retrieved {[0,1]} -> 0.5
#   (3,0) chunks [0,1,2][3]        relevant {[0,1,2]} retrieved {[0,1,2]}  -> 1.0
#   (3,1) chunks [0,1,2][2,3]      relevant {[0,1,2]} retrieved {[0,1,2]}  -> 1.0
#   (4,0) chunks [0,1,2,3]         relevant {[0..3]}  retrieved {[0..3]}   -> 1.0
#   (4,1) chunks [0,1,2,3]         relevant {[0..3]}  retrieved {[0..3]}   -> 1.0
MERGE_EXPECTED_RECALL = {
    (1, 0): 0.5,
    (2, 0): 1.0,
    (2, 1): 0.5,
    (3, 0): 1.0,
    (3, 1): 1.0,
    (4, 0): 1.0,
    (4, 1): 1.0,
}

# Coverage-relevance fixture: EDGAR sections only, so the chunking is
# identity in EVERY cell and the ONLY variable is `min_grade`.
#   sec-a  grade 2  contains "substation"      -> retrieved
#   sec-b  grade 1  does NOT contain the term  -> never retrieved
#   sec-c  grade 0  contains "substation"      -> retrieved but irrelevant
COVERAGE_DOCS = [
    _edgar_doc("a1", text="substation capacity request"),
    _edgar_doc("b2", text="transformer delivery schedule"),
    _edgar_doc("c3", text="substation maintenance window"),
]

COVERAGE_JUDGMENTS = [
    _judgment_row("q1", "substation", COVERAGE_DOCS[0].id, 2),
    _judgment_row("q1", "substation", COVERAGE_DOCS[1].id, 1),
    _judgment_row("q1", "substation", COVERAGE_DOCS[2].id, 0),
]


# ==========================================================================
# AC-1 — identity invariants (window=1, overlap=0 over mixed yt + EDGAR)
# ==========================================================================


def test_identity_chunking_yields_exactly_one_chunk_per_doc():
    # spec(T-020:AC-1)
    docs = _mixed_corpus()
    chunks = _chunk_corpus(docs, window=1, overlap=0)
    assert len(chunks) == len(docs)


def test_identity_chunk_id_equals_doc_id():
    # spec(T-020:AC-1) -- the locked invariant the shipped API path rests on.
    docs = _mixed_corpus()
    chunks = _chunk_corpus(docs, window=1, overlap=0)
    assert sorted(c.chunk_id for c in chunks) == sorted(d.id for d in docs)
    for chunk in chunks:
        assert chunk.chunk_id == chunk.doc_ids[0]


def test_identity_chunk_doc_ids_is_the_single_source_doc_id():
    # spec(T-020:AC-1)
    docs = _mixed_corpus()
    by_id = _by_id(_chunk_corpus(docs, window=1, overlap=0))
    for doc in docs:
        assert by_id[doc.id].doc_ids == [doc.id]


def test_identity_chunk_text_equals_source_doc_text():
    # spec(T-020:AC-1)
    docs = _mixed_corpus()
    by_id = _by_id(_chunk_corpus(docs, window=1, overlap=0))
    for doc in docs:
        assert by_id[doc.id].text == doc.text


def test_identity_chunk_passes_through_all_seven_metadata_fields():
    # spec(T-020:AC-1)
    docs = _mixed_corpus()
    by_id = _by_id(_chunk_corpus(docs, window=1, overlap=0))
    for doc in docs:
        chunk = by_id[doc.id]
        for field in METADATA_FIELDS:
            assert getattr(chunk, field) == getattr(doc, field), field


def test_chunk_is_a_frozen_dataclass_with_the_pinned_field_order():
    # spec(T-020:AC-1) -- T-022/T-024 construct Chunks against this order.
    import dataclasses

    chunk_cls = _chunking().Chunk
    assert dataclasses.is_dataclass(chunk_cls)
    assert tuple(f.name for f in dataclasses.fields(chunk_cls)) == CHUNK_FIELDS
    chunk = _chunk_corpus([_edgar_doc("23")], window=1, overlap=0)[0]
    with pytest.raises(dataclasses.FrozenInstanceError):
        chunk.chunk_id = "mutated"


def test_chunk_corpus_defaults_to_identity_chunking():
    # spec(T-020:AC-1) -- window=1/overlap=0 are the SHIPPED defaults.
    docs = _mixed_corpus()
    assert _chunk_corpus(docs) == _chunk_corpus(docs, window=1, overlap=0)


def test_chunk_corpus_accepts_window_and_overlap_positionally():
    # spec(T-020:AC-1) -- pins the parameter ORDER of the frozen signature.
    docs = _mixed_corpus()
    assert _chunk_corpus(docs, 3, 1) == _chunk_corpus(docs, window=3, overlap=1)


# ==========================================================================
# AC-2 — grouping, stride, tails, ids, metadata
# ==========================================================================


def _ac2_docs() -> list[Doc]:
    """Ticket AC-2's fixture: A(seg000..seg004), B(seg000..seg001)."""
    return [_yt_doc(VIDEO_A, n) for n in range(5)] + [_yt_doc(VIDEO_B, n) for n in range(2)]


def test_window3_overlap1_produces_the_windows_named_in_the_ticket():
    # spec(T-020:AC-2) -- stride 2, tail kept, never cross-video.
    chunks = _chunk_corpus(_ac2_docs(), window=3, overlap=1)
    assert _doc_ids_map(chunks) == {
        f"{_yt_id(VIDEO_A, 0)}+w3": [_yt_id(VIDEO_A, 0), _yt_id(VIDEO_A, 1), _yt_id(VIDEO_A, 2)],
        f"{_yt_id(VIDEO_A, 2)}+w3": [_yt_id(VIDEO_A, 2), _yt_id(VIDEO_A, 3), _yt_id(VIDEO_A, 4)],
        f"{_yt_id(VIDEO_B, 0)}+w3": [_yt_id(VIDEO_B, 0), _yt_id(VIDEO_B, 1)],
    }


def test_no_redundant_trailing_window_when_the_tail_is_already_covered():
    # spec(T-020:AC-2) -- the off-by-one: stride 2 over 5 segments would
    # otherwise emit a third window [seg004] already inside [seg002..004].
    chunks = _chunk_corpus([_yt_doc(VIDEO_A, n) for n in range(5)], window=3, overlap=1)
    assert len(chunks) == 2


def test_merged_chunk_id_suffix_uses_the_window_argument_not_the_chunk_size():
    # spec(T-020:AC-2) -- B has only 2 segments at window=3; the id is
    # "+w3" (ticket, verbatim), NOT "+w2".
    chunks = _chunk_corpus([_yt_doc(VIDEO_B, n) for n in range(2)], window=3, overlap=1)
    assert [c.chunk_id for c in chunks] == [f"{_yt_id(VIDEO_B, 0)}+w3"]


def test_merged_chunk_text_is_the_space_joined_constituent_texts_in_order():
    # spec(T-020:AC-2)
    docs = [_yt_doc(VIDEO_A, n, text=f"text-{n}") for n in range(3)]
    chunks = _chunk_corpus(docs, window=3, overlap=0)
    assert [c.text for c in chunks] == ["text-0 text-1 text-2"]


def test_merged_chunk_text_join_does_not_strip_empty_constituent_text():
    # spec(T-020:AC-2) -- "single space" is a literal " ".join, not a
    # normalize-and-compact (a caption window can legitimately be empty).
    docs = [_yt_doc(VIDEO_A, 0, text="opening"), _yt_doc(VIDEO_A, 1, text="")]
    chunks = _chunk_corpus(docs, window=2, overlap=0)
    assert [c.text for c in chunks] == [" ".join(["opening", ""])]


def test_merged_chunk_metadata_comes_from_the_first_constituent_doc():
    # spec(T-020:AC-2) -- the first window's deep_link timestamps the chunk
    # start; deep_link/speaker vary per segment in the fixture on purpose.
    docs = [_yt_doc(VIDEO_A, n) for n in range(3)]
    chunk = _chunk_corpus(docs, window=3, overlap=0)[0]
    for field in METADATA_FIELDS:
        assert getattr(chunk, field) == getattr(docs[0], field), field


def test_windows_never_cross_videos():
    # spec(T-020:AC-2)
    chunks = _chunk_corpus(_ac2_docs(), window=3, overlap=1)
    for chunk in chunks:
        videos = {doc_id.split(":")[1] for doc_id in chunk.doc_ids}
        assert len(videos) == 1


def test_windows_of_one_video_are_emitted_in_ascending_segment_order():
    # spec(T-020:AC-2)
    chunks = _chunk_corpus(_ac2_docs(), window=2, overlap=0)
    starts = [_seg_numbers(w)[0] for w in _windows_of(chunks, VIDEO_A)]
    assert starts == sorted(starts)


def test_segments_are_ordered_by_number_not_by_input_list_order():
    # spec(T-020:AC-2) -- the corpus does not guarantee segment-sorted input.
    ordered = [_yt_doc(VIDEO_A, n) for n in range(5)]
    scrambled = [ordered[3], ordered[0], ordered[4], ordered[2], ordered[1]]
    assert _doc_ids_map(_chunk_corpus(scrambled, window=3, overlap=1)) == _doc_ids_map(
        _chunk_corpus(ordered, window=3, overlap=1)
    )


def test_segments_are_ordered_numerically_across_the_zero_padding_boundary():
    # spec(T-020:AC-2) -- ingest emits f"seg{i:03d}" (onrecord/ingest/
    # youtube.py), so a >20h video legitimately produces "seg1000", which
    # sorts BEFORE "seg999" as a string. The ticket says "ordered by NNN":
    # NNN is a number, so 998, 999, 1000, 1001 must window in that order.
    docs = [_yt_doc(VIDEO_A, n) for n in (998, 999, 1000, 1001)]
    chunks = _chunk_corpus(docs, window=2, overlap=0)
    assert _windows_of(chunks, VIDEO_A) == [
        (_yt_id(VIDEO_A, 998), _yt_id(VIDEO_A, 999)),
        (_yt_id(VIDEO_A, 1000), _yt_id(VIDEO_A, 1001)),
    ]


def test_uncovered_short_tail_window_is_kept():
    # spec(T-020:AC-2) -- 4 segments, window=3, stride=3 -> [0,1,2] then [3].
    docs = [_yt_doc(VIDEO_A, n) for n in range(4)]
    chunks = _chunk_corpus(docs, window=3, overlap=0)
    assert _windows_of(chunks, VIDEO_A) == [
        (_yt_id(VIDEO_A, 0), _yt_id(VIDEO_A, 1), _yt_id(VIDEO_A, 2)),
        (_yt_id(VIDEO_A, 3),),
    ]


def test_exact_multiple_of_stride_emits_no_empty_trailing_window():
    # spec(T-020:AC-2) -- 4 segments, window=2, stride=2 -> exactly 2 windows.
    docs = [_yt_doc(VIDEO_A, n) for n in range(4)]
    chunks = _chunk_corpus(docs, window=2, overlap=0)
    assert _windows_of(chunks, VIDEO_A) == [
        (_yt_id(VIDEO_A, 0), _yt_id(VIDEO_A, 1)),
        (_yt_id(VIDEO_A, 2), _yt_id(VIDEO_A, 3)),
    ]


def test_overlapping_windows_repeat_the_boundary_segment_verbatim():
    # spec(T-020:AC-2) -- window=2/overlap=1 over 4 segments, stride 1.
    docs = [_yt_doc(VIDEO_A, n) for n in range(4)]
    chunks = _chunk_corpus(docs, window=2, overlap=1)
    assert _windows_of(chunks, VIDEO_A) == [
        (_yt_id(VIDEO_A, 0), _yt_id(VIDEO_A, 1)),
        (_yt_id(VIDEO_A, 1), _yt_id(VIDEO_A, 2)),
        (_yt_id(VIDEO_A, 2), _yt_id(VIDEO_A, 3)),
    ]


def test_single_segment_video_stays_an_identity_chunk_at_window_above_one():
    # spec(T-020:AC-2) -- single-doc channel: chunk_id == doc_id because the
    # chunk covers exactly one doc (module docstring, chunk_id rule).
    chunks = _chunk_corpus([_yt_doc(VIDEO_B, 0)], window=4, overlap=1)
    assert [(c.chunk_id, c.doc_ids) for c in chunks] == [(_yt_id(VIDEO_B, 0), [_yt_id(VIDEO_B, 0)])]


def test_single_doc_tail_window_is_an_identity_chunk():
    # spec(T-020:AC-2) -- same rule for the [seg003] tail of a 4-segment
    # video at window=3: no "+w3" suffix is minted for a one-doc chunk.
    docs = [_yt_doc(VIDEO_A, n) for n in range(4)]
    by_id = _by_id(_chunk_corpus(docs, window=3, overlap=0))
    assert by_id[_yt_id(VIDEO_A, 3)].doc_ids == [_yt_id(VIDEO_A, 3)]


def test_chunk_ids_are_unique_at_every_default_grid_cell():
    # spec(T-020:AC-2) -- ids key an in-memory index; collisions would
    # silently drop chunks from the sweep.
    docs = _mixed_corpus()
    for window, overlap in DEFAULT_CELLS:
        chunks = _chunk_corpus(docs, window=window, overlap=overlap)
        ids = [c.chunk_id for c in chunks]
        assert len(ids) == len(set(ids)), (window, overlap)


def test_empty_corpus_yields_no_chunks():
    # spec(T-020:AC-2) -- empty channel, at identity and at window>1.
    assert _chunk_corpus([], window=1, overlap=0) == []
    assert _chunk_corpus([], window=3, overlap=1) == []


# ==========================================================================
# AC-3 — non-yt docs are identity chunks at EVERY setting
# ==========================================================================


def test_edgar_docs_are_identity_chunks_at_every_default_grid_cell():
    # spec(T-020:AC-3) -- unconditional: they are already section-level.
    docs = [_edgar_doc("23"), _edgar_doc("24"), _edgar_doc("25")]
    for window, overlap in DEFAULT_CELLS:
        chunks = _chunk_corpus(docs, window=window, overlap=overlap)
        assert _doc_ids_map(chunks) == {d.id: [d.id] for d in docs}, (window, overlap)


def test_edgar_docs_keep_their_own_text_and_metadata_at_window_above_one():
    # spec(T-020:AC-3) -- never merged with a neighbouring yt segment even
    # when interleaved in the input list.
    docs = _mixed_corpus()
    edgar_ids = {d.id for d in docs if d.source_type == "filing"}
    by_id = _by_id(_chunk_corpus(docs, window=3, overlap=1))
    for doc in docs:
        if doc.id not in edgar_ids:
            continue
        assert by_id[doc.id].text == doc.text
        for field in METADATA_FIELDS:
            assert getattr(by_id[doc.id], field) == getattr(doc, field), field


def test_yt_prefixed_ids_that_do_not_match_the_segment_pattern_pass_through():
    # spec(T-020:AC-3) -- the pattern is yt:<video>:seg<NNN> with NNN
    # digits; a loose "startswith yt: and contains seg" test would wrongly
    # merge the two segABC/segDEF docs below.
    docs = [
        _edgar_doc("99", id="yt:VIDXXXXXXXX:segABC"),
        _edgar_doc("98", id="yt:VIDXXXXXXXX:segDEF"),
        _edgar_doc("97", id="yt:VIDYYYYYYYY"),
        _edgar_doc("96", id="ytx:VIDZZZZZZZ:seg001"),
    ]
    chunks = _chunk_corpus(docs, window=3, overlap=1)
    assert _doc_ids_map(chunks) == {d.id: [d.id] for d in docs}


# ==========================================================================
# AC-4 — doc ids echoed verbatim (hypothesis property tests)
# ==========================================================================


@st.composite
def _yt_corpus_and_params(draw):
    pairs = draw(
        st.lists(
            # The upper bound crosses ingest's f"seg{i:03d}" zero-padding
            # boundary on purpose, so "ascending segment order" is exercised
            # as a NUMERIC ordering, not a lexicographic one.
            st.tuples(st.sampled_from([VIDEO_A, VIDEO_B, VIDEO_C]), st.integers(0, 1200)),
            min_size=1,
            max_size=12,
            unique=True,
        )
    )
    window = draw(st.integers(1, 5))
    overlap = draw(st.integers(0, window - 1))
    return [_yt_doc(video, n) for video, n in pairs], window, overlap


@given(_yt_corpus_and_params())
@settings(max_examples=60, deadline=None)
def test_property_overlap_zero_preserves_the_input_id_multiset(case):
    # spec(T-020:AC-4) -- stride == window, so every input doc appears in
    # exactly one chunk, and no id is invented, dropped or duplicated.
    docs, window, _overlap = case
    chunks = _chunk_corpus(docs, window=window, overlap=0)
    constituents = list(chain.from_iterable(c.doc_ids for c in chunks))
    assert sorted(constituents) == sorted(d.id for d in docs)


@given(_yt_corpus_and_params())
@settings(max_examples=60, deadline=None)
def test_property_no_chunk_ever_contains_an_id_absent_from_the_input(case):
    # spec(T-020:AC-4) -- at ANY valid (window, overlap): verbatim echo,
    # never a re-minted, re-cased or reshaped doc id.
    docs, window, overlap = case
    input_ids = {d.id for d in docs}
    chunks = _chunk_corpus(docs, window=window, overlap=overlap)
    for chunk in chunks:
        assert set(chunk.doc_ids) <= input_ids
    assert input_ids <= set(chain.from_iterable(c.doc_ids for c in chunks))


@given(_yt_corpus_and_params())
@settings(max_examples=60, deadline=None)
def test_property_chunk_id_is_derivable_from_doc_ids_and_window(case):
    # spec(T-020:AC-4) -- chunk ids are DERIVED, never freshly minted:
    # single-doc chunk -> the doc id itself; merged -> "<first>+w<window>".
    docs, window, overlap = case
    for chunk in _chunk_corpus(docs, window=window, overlap=overlap):
        expected = chunk.doc_ids[0] if len(chunk.doc_ids) == 1 else f"{chunk.doc_ids[0]}+w{window}"
        assert chunk.chunk_id == expected


@given(_yt_corpus_and_params())
@settings(max_examples=60, deadline=None)
def test_property_constituents_share_one_video_in_ascending_segment_order(case):
    # spec(T-020:AC-4)
    docs, window, overlap = case
    for chunk in _chunk_corpus(docs, window=window, overlap=overlap):
        videos = {doc_id.split(":")[1] for doc_id in chunk.doc_ids}
        assert len(videos) == 1
        numbers = _seg_numbers(chunk.doc_ids)
        assert numbers == sorted(numbers)
        assert len(numbers) == len(set(numbers))


@given(_yt_corpus_and_params())
@settings(max_examples=60, deadline=None)
def test_property_chunk_size_is_between_one_and_window(case):
    # spec(T-020:AC-4)
    docs, window, overlap = case
    for chunk in _chunk_corpus(docs, window=window, overlap=overlap):
        assert 1 <= len(chunk.doc_ids) <= window


def test_chunk_corpus_is_deterministic_across_calls():
    # spec(T-020:AC-4) -- the chunk_id -> doc_ids mapping (and the emitted
    # order) must be reproducible; the sweep artifact depends on it.
    docs = _mixed_corpus()
    for window, overlap in DEFAULT_CELLS:
        first = _chunk_corpus(docs, window=window, overlap=overlap)
        second = _chunk_corpus(docs, window=window, overlap=overlap)
        assert first == second, (window, overlap)


# ==========================================================================
# AC-5 — coverage relevance, min_grade threshold, recall math, valid cells
# ==========================================================================


def _cells_by_setting(result) -> dict:
    return {(cell["window"], cell["overlap"]): cell for cell in result["cells"]}


def test_min_grade_1_treats_grade_1_and_grade_2_docs_as_coverage_relevant(tmp_path):
    # spec(T-020:AC-5) -- relevant chunks = {sec-a (g2), sec-b (g1)}; only
    # sec-a matches "substation", so recall = 1/2.
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", COVERAGE_JUDGMENTS)
    result = _chunk_sweep(COVERAGE_DOCS, judgments, min_grade=1)
    for setting, cell in _cells_by_setting(result).items():
        assert cell["recall@5"] == pytest.approx(0.5), setting


def test_min_grade_2_treats_only_grade_2_docs_as_coverage_relevant(tmp_path):
    # spec(T-020:AC-5) -- relevant chunks = {sec-a}; it IS retrieved, so
    # recall = 1/1. OQ-6 therefore resolves by config, not a re-freeze.
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", COVERAGE_JUDGMENTS)
    result = _chunk_sweep(COVERAGE_DOCS, judgments, min_grade=2)
    for setting, cell in _cells_by_setting(result).items():
        assert cell["recall@5"] == pytest.approx(1.0), setting


def test_grade_zero_docs_are_never_coverage_relevant(tmp_path):
    # spec(T-020:AC-5) -- a query whose every judged doc is grade 0 has no
    # relevant chunk at all: recall is 0.0, not a ZeroDivisionError.
    rows = [
        _judgment_row("q1", "substation", COVERAGE_DOCS[0].id, 0),
        _judgment_row("q1", "substation", COVERAGE_DOCS[2].id, 0),
    ]
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", rows)
    result = _chunk_sweep(COVERAGE_DOCS, judgments)
    for setting, cell in _cells_by_setting(result).items():
        assert cell["recall@5"] == 0.0, setting
        assert cell["recall@10"] == 0.0, setting


def test_merged_chunk_covering_two_relevant_docs_counts_as_one_relevant_chunk(tmp_path):
    # spec(T-020:AC-5) -- at (1,0) the two relevant docs are 2 relevant
    # chunks and only one is retrieved (0.5); at (2,0) they merge into a
    # SINGLE relevant chunk which IS retrieved (1.0).
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", MERGE_JUDGMENTS)
    cells = _cells_by_setting(_chunk_sweep(MERGE_DOCS, judgments))
    assert cells[(1, 0)]["recall@5"] == pytest.approx(0.5)
    assert cells[(2, 0)]["recall@5"] == pytest.approx(1.0)


def test_recall_values_match_hand_computation_for_every_default_cell(tmp_path):
    # spec(T-020:AC-5) -- the full hand-computed table (see
    # MERGE_EXPECTED_RECALL for the per-cell arithmetic).
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", MERGE_JUDGMENTS)
    cells = _cells_by_setting(_chunk_sweep(MERGE_DOCS, judgments))
    computed = {setting: cell["recall@5"] for setting, cell in cells.items()}
    assert computed == pytest.approx(MERGE_EXPECTED_RECALL)


def test_recall_is_the_arithmetic_mean_over_judgment_queries(tmp_path):
    # spec(T-020:AC-5) -- q1 recalls its only relevant doc (1.0); q2's only
    # relevant doc lacks the query term and is never retrieved (0.0).
    rows = [
        _judgment_row("q1", "substation", COVERAGE_DOCS[0].id, 2),
        _judgment_row("q2", "capacity", COVERAGE_DOCS[1].id, 1),
    ]
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", rows)
    result = _chunk_sweep(COVERAGE_DOCS, judgments)
    for setting, cell in _cells_by_setting(result).items():
        assert cell["recall@5"] == pytest.approx(0.5), setting


def test_invalid_cells_are_excluded_from_the_grid(tmp_path):
    # spec(T-020:AC-5) -- overlap >= window is skipped, never an error;
    # 7 valid cells at the default 4x2 grid.
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", MERGE_JUDGMENTS)
    result = _chunk_sweep(MERGE_DOCS, judgments)
    settings_seen = [(cell["window"], cell["overlap"]) for cell in result["cells"]]
    assert sorted(settings_seen) == sorted(DEFAULT_CELLS)


def test_every_cell_reports_a_finite_recall_in_the_unit_interval(tmp_path):
    # spec(T-020:AC-5)
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", MERGE_JUDGMENTS)
    result = _chunk_sweep(MERGE_DOCS, judgments)
    for cell in result["cells"]:
        for key in ("recall@5", "recall@10"):
            value = cell[key]
            assert isinstance(value, float)
            assert 0.0 <= value <= 1.0


def test_recall_truncates_the_retrieved_ranking_at_k(tmp_path):
    # spec(T-020:AC-5) -- injected ranking puts the single relevant chunk at
    # rank 8: invisible at k=5, found at k=10.
    docs = [_edgar_doc(f"{n:02d}") for n in range(12)]
    rows = [_judgment_row("q1", "anything", docs[7].id, 2)]
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", rows)

    def factory(chunks):
        ranking = [d.id for d in docs]

        def retrieve_fn(query):
            return ranking

        return retrieve_fn

    result = _chunk_sweep(docs, judgments, retrieve_fn_factory=factory)
    for setting, cell in _cells_by_setting(result).items():
        assert cell["recall@5"] == 0.0, setting
        assert cell["recall@10"] == pytest.approx(1.0), setting


def test_retrieve_fn_factory_receives_each_cells_own_chunks(tmp_path):
    # spec(T-020:AC-5) -- the seam T-022+ re-runs the sweep semantically
    # through: one chunking per valid cell, built by chunk_corpus.
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", MERGE_JUDGMENTS)
    seen = []

    def factory(chunks):
        seen.append(tuple(c.chunk_id for c in chunks))
        return lambda query: []

    _chunk_sweep(MERGE_DOCS, judgments, retrieve_fn_factory=factory)
    expected = {
        tuple(c.chunk_id for c in _chunk_corpus(MERGE_DOCS, window=w, overlap=o))
        for w, o in DEFAULT_CELLS
    }
    assert set(seen) == expected


def test_retrieve_fn_is_called_with_the_query_text_not_the_query_id(tmp_path):
    # spec(T-020:AC-5)
    rows = [_judgment_row("q1", "substation capacity", COVERAGE_DOCS[0].id, 2)]
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", rows)
    queries = []

    def factory(chunks):
        def retrieve_fn(query):
            queries.append(query)
            return []

        return retrieve_fn

    _chunk_sweep(COVERAGE_DOCS, judgments, retrieve_fn_factory=factory)
    assert set(queries) == {"substation capacity"}


# ==========================================================================
# AC-6 — artifact shape, best tie-break, min_grade echo, corpus_version
# ==========================================================================


def _default_sweep(tmp_path, **kwargs):
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", MERGE_JUDGMENTS)
    return _chunk_sweep(MERGE_DOCS, judgments, **kwargs)


def test_result_has_exactly_the_pinned_top_level_keys(tmp_path):
    # spec(T-020:AC-6)
    result = _default_sweep(tmp_path)
    assert set(result) == {
        "cells",
        "best",
        "n_queries",
        "min_grade",
        "corpus_version",
        "retrieval",
    }


def test_each_cell_has_exactly_the_pinned_keys_for_the_default_k_values(tmp_path):
    # spec(T-020:AC-6)
    result = _default_sweep(tmp_path)
    for cell in result["cells"]:
        assert set(cell) == {"window", "overlap", "recall@5", "recall@10"}


def test_cell_recall_keys_follow_the_requested_k_values(tmp_path):
    # spec(T-020:AC-6) -- the key template is f"recall@{k}".
    result = _default_sweep(tmp_path, k_values=(3, 10))
    for cell in result["cells"]:
        assert set(cell) == {"window", "overlap", "recall@3", "recall@10"}


def test_best_is_the_cell_with_the_highest_recall_at_10(tmp_path):
    # spec(T-020:AC-6)
    result = _default_sweep(tmp_path)
    assert result["best"]["recall@10"] == max(c["recall@10"] for c in result["cells"])
    assert result["best"] in result["cells"]


def test_best_breaks_ties_toward_the_smallest_window_overlap(tmp_path):
    # spec(T-020:AC-6) -- five cells tie at recall 1.0 on this fixture and
    # (1,0) scores lower, so the winner must be (2,0): a real tie-break, not
    # "the first cell". The scrambled windows/overlaps argument order forces
    # an explicit sort rather than iteration luck.
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", MERGE_JUDGMENTS)
    result = _chunk_sweep(MERGE_DOCS, judgments, windows=(4, 3, 1, 2), overlaps=(1, 0))
    assert (result["best"]["window"], result["best"]["overlap"]) == (2, 0)


def test_min_grade_is_echoed_into_the_artifact(tmp_path):
    # spec(T-020:AC-6)
    assert _default_sweep(tmp_path)["min_grade"] == 1
    assert _default_sweep(tmp_path, min_grade=2)["min_grade"] == 2


def test_n_queries_counts_distinct_judgment_queries(tmp_path):
    # spec(T-020:AC-6)
    rows = [
        _judgment_row("q1", "substation", COVERAGE_DOCS[0].id, 2),
        _judgment_row("q1", "substation", COVERAGE_DOCS[2].id, 0),
        _judgment_row("q2", "capacity", COVERAGE_DOCS[1].id, 1),
    ]
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", rows)
    assert _chunk_sweep(COVERAGE_DOCS, judgments)["n_queries"] == 2


def test_retrieval_field_names_the_default_bm25_retriever(tmp_path):
    # spec(T-020:AC-6)
    assert _default_sweep(tmp_path)["retrieval"] == "bm25"


def test_corpus_version_is_unversioned_without_a_manifest_dir(tmp_path):
    # spec(T-020:AC-6)
    assert _default_sweep(tmp_path, manifest_dir=None)["corpus_version"] == "unversioned"


def test_corpus_version_is_read_from_the_manifest(tmp_path):
    # spec(T-020:AC-6) -- T-018's <dir>/manifest.json, "corpus_version" key.
    manifest_dir = tmp_path / "index"
    manifest_dir.mkdir()
    (manifest_dir / "manifest.json").write_text(
        json.dumps({"corpus_version": "v2", "doc_count": 3}), encoding="utf-8"
    )
    assert _default_sweep(tmp_path, manifest_dir=manifest_dir)["corpus_version"] == "v2"


def test_corpus_version_accepts_a_string_manifest_dir(tmp_path):
    # spec(T-020:AC-6) -- signature says str | Path | None.
    manifest_dir = tmp_path / "index"
    manifest_dir.mkdir()
    (manifest_dir / "manifest.json").write_text(
        json.dumps({"corpus_version": "v2"}), encoding="utf-8"
    )
    assert _default_sweep(tmp_path, manifest_dir=str(manifest_dir))["corpus_version"] == "v2"


def test_corpus_version_is_unversioned_when_the_manifest_file_is_missing(tmp_path):
    # spec(T-020:AC-6) -- tolerant read, never an exception.
    manifest_dir = tmp_path / "index"
    manifest_dir.mkdir()
    assert _default_sweep(tmp_path, manifest_dir=manifest_dir)["corpus_version"] == "unversioned"


def test_corpus_version_is_unversioned_for_a_corrupt_manifest(tmp_path):
    # spec(T-020:AC-6)
    manifest_dir = tmp_path / "index"
    manifest_dir.mkdir()
    (manifest_dir / "manifest.json").write_text("{not json", encoding="utf-8")
    assert _default_sweep(tmp_path, manifest_dir=manifest_dir)["corpus_version"] == "unversioned"


def test_corpus_version_is_unversioned_when_the_manifest_lacks_the_key(tmp_path):
    # spec(T-020:AC-6)
    manifest_dir = tmp_path / "index"
    manifest_dir.mkdir()
    (manifest_dir / "manifest.json").write_text(json.dumps({"doc_count": 3}), encoding="utf-8")
    assert _default_sweep(tmp_path, manifest_dir=manifest_dir)["corpus_version"] == "unversioned"


def test_artifact_round_trips_through_json_unchanged(tmp_path):
    # spec(T-020:AC-6) -- every value must be JSON-native (no tuples, no
    # numpy floats) so the written artifact equals the returned dict.
    result = _default_sweep(tmp_path)
    artifact = tmp_path / "chunking_recall.json"
    artifact.write_text(json.dumps(result), encoding="utf-8")
    assert json.loads(artifact.read_text(encoding="utf-8")) == result


def test_sweep_is_deterministic_across_calls(tmp_path):
    # spec(T-020:AC-6)
    assert _default_sweep(tmp_path) == _default_sweep(tmp_path)


def test_sweep_writes_nothing_to_disk(tmp_path, monkeypatch):
    # spec(T-020:AC-6) -- in-memory only; the real artifacts/index stays
    # corpus-doc-keyed and must never be overwritten with chunk ids.
    workdir = tmp_path / "work"
    workdir.mkdir()
    judgments = _write_judgments(tmp_path / "j" / "judgments.jsonl", MERGE_JUDGMENTS)
    monkeypatch.chdir(workdir)
    _chunk_sweep(MERGE_DOCS, judgments)
    assert list(workdir.iterdir()) == []


# ==========================================================================
# AC-7 — parameter validation
# ==========================================================================


def test_window_zero_raises_value_error_naming_window():
    # spec(T-020:AC-7)
    with pytest.raises(ValueError, match="window"):
        _chunk_corpus(_mixed_corpus(), window=0, overlap=0)


def test_negative_window_raises_value_error_naming_window():
    # spec(T-020:AC-7)
    with pytest.raises(ValueError, match="window"):
        _chunk_corpus(_mixed_corpus(), window=-1, overlap=0)


def test_negative_overlap_raises_value_error_naming_overlap():
    # spec(T-020:AC-7)
    with pytest.raises(ValueError, match="overlap"):
        _chunk_corpus(_mixed_corpus(), window=2, overlap=-1)


def test_overlap_equal_to_window_raises_value_error_naming_overlap():
    # spec(T-020:AC-7)
    with pytest.raises(ValueError, match="overlap"):
        _chunk_corpus(_mixed_corpus(), window=2, overlap=2)


def test_overlap_greater_than_window_raises_value_error_naming_overlap():
    # spec(T-020:AC-7)
    with pytest.raises(ValueError, match="overlap"):
        _chunk_corpus(_mixed_corpus(), window=2, overlap=5)
