"""Failing tests for T-021 — embeddings: provider adapter, content-hash cache,
fp16 store, brute-force cosine.

Encodes tickets/T-021.md AC-1..AC-8, as amended by the ORCHESTRATOR RULING on
test-review finding C-1 (see "Orchestrator ruling" below). These tests are
FROZEN after the Test Agent hands off: do not edit this file to make an
implementation pass — fix the implementation (new file
`onrecord/rag/embeddings.py`) instead.

Run with:
    uv run pytest tests/unit/rag/ -v

MODULE-PRESENCE GUARD (why every test starts with `_module()`)
--------------------------------------------------------------
`onrecord.rag.embeddings` is THIS ticket's target module and does not exist
yet. A module-scope `import onrecord.rag.embeddings` would blow the whole
file up as a pytest COLLECTION ERROR, which pollutes other in-flight
tickets' regression baselines (`uv run pytest -q` is run by the orchestrator
at any time). So, mirroring tests/unit/test_api.py's established idiom,
`_require_module_spec(...)` + `pytest.fail(...)` turns "module missing" into
a clean per-test RED failure. numpy and httpx are real pyproject deps
(numpy>=2.1, httpx>=0.27) so they import at module scope with no guard, and
this ticket adds NO dependencies.

ZERO NETWORK, ZERO KEYS
-----------------------
Every provider interaction goes through a `FakeProvider`/`ScriptedProvider`
(the Protocol boundary) or `httpx.MockTransport` (the OpenAI wire shape).
No test reads a real key: key-sensitive tests always `monkeypatch.delenv`
or `monkeypatch.setenv` a sentinel first, so neither branch is
"environmentally lucky" (plan-review I-5).

===========================================================================
ORCHESTRATOR RULING — storage is PER-CHUNK, de-duplication is PER-API-CALL
===========================================================================
Test-review C-1 established that the ticket's text-keyed store (one row per
content hash, one recorded `chunk_id` per row) is incompatible with T-022's
pinned per-chunk verification whenever two corpus documents share identical
text — 63 such documents exist in corpus v1, ~700 projected for v2. The
orchestrator ruled, and this suite freezes the ruling:

* **Storage is per-chunk.** One matrix row per `chunk_id`. T-022's pinned
  "the store entry's recorded `chunk_id` must equal the chunk's `chunk_id`"
  therefore holds verbatim — the recorded chunk_id is the entry's KEY.
* **`entries.json` maps `chunk_id -> {"row": int, "content_hash": str}`**
  (the inverse of the ticket's L22 sketch), wrapped in a header carrying the
  store's model/dim identity (see "Store identity" below).
* **De-duplication moved to the API-CALL level.** Inside `embed_corpus`, a
  text whose `content_hash` already has a vector — from earlier in this same
  call, or from a previous run already in the store — has that vector
  **copied** into the new chunk's own row. The provider is never billed
  twice for identical text, which is the spend guarantee the content-hash
  cache existed for; the store stays one-row-per-chunk, which is the
  correspondence guarantee T-022 needs. Both halves are pinned:
  `test_duplicate_text_is_billed_to_the_provider_only_once` /
  `test_duplicate_text_rows_hold_identical_vector_bytes` and their
  cross-run twins.
* **Alignment checks stay chunk_id-level** — `rows_for(chunk_ids)` and
  `entry_for(chunk_id)`.

>>> ESCALATION FOR THE ORCHESTRATOR / T-022's Test Agent <<<
`tickets/T-022.md:19` still reads "resolve rows via `store.rows_for(hashes)`".
Under this ruling that call is `store.rows_for(chunk_ids)` — a content hash
can no longer identify a row, precisely because duplicate texts now occupy
several rows. T-022 is still `status: backlog`, so its frozen suite has not
been written yet; that line needs a one-word amendment before it is.
**chunk_ids and content hashes are both `str`, so this substitution fails
SILENTLY (a total miss, every row `None`), which is the exact LESSONS
T-003/T-004 defect class.** A tripwire test —
`test_rows_for_is_chunk_id_keyed_not_content_hash_keyed` — is frozen here so
the mistake fails loudly in T-021's own suite. T-022 still needs
`content_hash` (now frozen public API, see below) to VERIFY the row it got:
`entry_for(chunk_id)["content_hash"]` must equal the chunk's computed hash,
which is what raises T-022's `StoreMismatch`.

CONTRACTS PINNED HERE
---------------------
Ticket-derived (T-021.md Context / ACs):

* Content-hash formula — `sha256(f"{model}\\n{dim}\\n{text}".encode("utf-8"))`
  hexdigest, with `dim` in the key (plan-review M-9). Frozen twice over: the
  tests compute it themselves via `_content_hash`, AND
  `test_content_hash_matches_the_frozen_formula` pins it against hard-coded
  hexdigest literals.
* `matrix.npy` — N x dim, **float16**, L2-normalized rows.
* Atomic `save`, checkpointing `embed_corpus`, validating `load`
  (integrity contract I-10a/b/c), blocked `cosine_top_k`, the OpenAI
  adapter's wire shape, and the T-014 secret-hygiene rule.

Test Agent decisions, ratified by the orchestrator ruling above (these are
NOT in the ticket's Context section — they are inventions this suite freezes,
and the implementer should read them as such):

1. `content_hash(model, dim, text) -> str` is **public API** (review I-4), so
   T-022 imports it instead of re-deriving the formula by hand.
2. `EmbeddingStore()` takes no required arguments and yields an empty store;
   `EmbeddingStore.load(dir)` is called on the CLASS and returns a store;
   `store.save(dir)` creates `dir` if needed.
3. `entries.json` top-level object carries **at least** `{"model", "dim",
   "entries"}`; a store written with exactly those three keys must load
   clean (extra keys such as a `version` are permitted and deliberately not
   required). `entries` values are exactly `{"row", "content_hash"}`.
4. **Store identity** (review I-5): the store persists the `model`/`dim` it
   was built with, exposes them as `store.model` / `store.dim`, and
   `load(dir, model=..., dim=...)` raises typed **`StoreIdentityMismatch`**
   when the persisted identity disagrees. Both identity arguments are
   OPTIONAL so T-024's bare `EmbeddingStore.load(dir)` still works. The
   exception's base class is deliberately NOT pinned — an implementer may
   subclass `CorruptStore` to inherit T-024's existing degradation rung, or
   keep it separate and let T-024 add one.
5. `embed_corpus` calls the provider in batches of **at most**
   `checkpoint_every` items when `checkpoint_dir` is set (a smaller final
   batch is explicitly fine — review I-2), and flushes that final partial
   batch (review I-3).
6. Missing key raises at **construction** (AC-5's mirrored branch says
   "construction succeeds" for the key-present case).
7. The OpenAI response's `index` field is authoritative for row order.
8. Mocked embeddings match `provider.dim`, so a defensive
   `arr.shape[1] == self.dim` check stays valid. This requires the adapter
   to know `dim` at construction with no network; a default for unknown
   model names is fine (review M-4).
9. Retry exhaustion on a permanent 5xx is pinned only as "retries, then
   fails loudly, 2-5 total requests" — "max 3" is ambiguous between attempts
   and retries, so the exception type and backoff schedule stay free.
10. **AC-2's M-9 "distinct entries" clause is unimplementable as written**
    (review I-6): two providers of different `dim` cannot share one packed
    N x dim matrix, which the ticket separately mandates. Rather than
    silently narrowing it to a miss-check, this suite resolves it
    constructively — embedding at a different `(model, dim)` than the
    store's raises `StoreIdentityMismatch`, and the "distinct keys" half is
    pinned directly on `content_hash`.
11. The adapter must not re-emit a transport error's text verbatim (review
    I-7); it wraps it in its own credential-free message.

DELIBERATELY NOT PINNED (documented gaps, not oversights)
---------------------------------------------------------
* Re-embedding an existing `chunk_id` whose TEXT changed. `embed_corpus`
  skips chunk_ids already present, so a stale row survives a corpus edit.
  The safety net is downstream and already pinned: T-022 compares
  `entry_for(chunk_id)["content_hash"]` against the chunk's recomputed hash
  and raises `StoreMismatch`. A re-freeze against an edited corpus wants a
  fresh store dir.
* A default store-path helper (review M-7): T-024 hard-codes
  `artifacts/embeddings/<resolved model>`. Naming a symbol here that T-024
  is not written against would risk a second id-space drift; left to T-024.
* Provider batch size when `checkpoint_dir is None` (tests count texts, not
  calls).

SECRET HYGIENE (LESSONS.md T-014, 2026-08-11)
----------------------------------------------
The key must never appear in ANY log record. The AC-6 tests capture at the
ROOT logger with library loggers left free to propagate at INFO. **Accuracy
note (review I-7):** T-014's leak was FMP's `?apikey=` QUERY STRING, and
httpx does log full request URLs at INFO — but the OpenAI key travels in a
bearer HEADER, so that specific vector does not transfer to this adapter.
What these tests actually guarantee is (a) the adapter never logs the key
itself, (b) it never surfaces it in exception or repr text, and (c) it never
re-emits a transport error's text verbatim. Each test carries an explicit
liveness precondition so none of them can pass vacuously.
"""

import contextlib
import hashlib
import importlib.util
import json
import logging
import time
from pathlib import Path

import httpx
import numpy as np
import pytest

FAKE_MODEL = "fake-embed-model"
SENTINEL_KEY = "SUPERSECRET-sentinel-openaikey-zzz9999"
OPENAI_MODEL = "text-embedding-3-small"
SHARED_TEXT = "identical boilerplate paragraph"
CANARY = "LOGGING-CAPTURE-CANARY"

# Captured before any test monkeypatches numpy.save (see the atomic-save test).
_REAL_NP_SAVE = np.save


# --------------------------------------------------------------------------
# Guards / module access
# --------------------------------------------------------------------------


def _require_module_spec(name: str, fail_message: str):
    """Return the module spec for `name`, or fail cleanly via pytest.fail.

    Mirrors tests/unit/test_api.py's guard idiom: importlib.util.find_spec
    raises ModuleNotFoundError (rather than returning None) when a parent
    package in a dotted name is itself missing — `onrecord.rag` does not
    exist yet either — so both "not found" cases are normalized into one
    clean assertion-style failure, never an uncaught exception or a pytest
    collection error.
    """
    try:
        spec = importlib.util.find_spec(name)
    except ModuleNotFoundError:
        spec = None
    if spec is None:
        pytest.fail(fail_message)
    return spec


def _module():
    _require_module_spec(
        "onrecord.rag.embeddings",
        "onrecord.rag.embeddings missing (T-021 target module — expected RED "
        "until the Implementation Agent lands it)",
    )
    import onrecord.rag.embeddings as embeddings

    return embeddings


def _attr(name: str):
    mod = _module()
    if not hasattr(mod, name):
        pytest.fail(f"onrecord.rag.embeddings.{name} missing")
    return getattr(mod, name)


def _new_store():
    """An empty store — `EmbeddingStore()` takes no required arguments."""
    return _attr("EmbeddingStore")()


def _load_store(path: Path, **identity):
    """`EmbeddingStore.load(dir)`, optionally with `model=`/`dim=` identity."""
    return _attr("EmbeddingStore").load(path, **identity)


# --------------------------------------------------------------------------
# Deterministic test doubles for the provider boundary
# --------------------------------------------------------------------------


class ProviderBoom(RuntimeError):
    """Simulated mid-run provider failure (quota exhaustion / flaky host)."""


def _fake_vector(text: str, dim: int, model: str) -> np.ndarray:
    """Deterministic, hash-seeded pseudo-embedding — stable across runs."""
    digest = hashlib.sha256(f"{model}|{dim}|{text}".encode()).digest()
    seed = int.from_bytes(digest[:8], "big")
    rng = np.random.default_rng(seed)
    return rng.standard_normal(dim).astype(np.float32)


class FakeProvider:
    """Hash-seeded deterministic stand-in for a real EmbeddingProvider.

    `calls` records every batch the store ASKED for; `returned` records only
    the batches that actually produced vectors (a batch that raises appears
    in `calls` but not in `returned`) — the AC-8 "nothing is embedded twice"
    assertion is about successfully-embedded texts.
    """

    def __init__(
        self,
        dim: int = 4,
        model: str = FAKE_MODEL,
        fail_on_call: int | None = None,
    ):
        self.dim = dim
        self.model = model
        self.fail_on_call = fail_on_call
        self.calls: list[list[str]] = []
        self.returned: list[list[str]] = []

    def embed(self, texts: list[str]) -> np.ndarray:
        batch = list(texts)
        self.calls.append(batch)
        if self.fail_on_call is not None and len(self.calls) == self.fail_on_call:
            raise ProviderBoom(f"simulated provider failure on batch {self.fail_on_call}")
        self.returned.append(batch)
        if not batch:
            return np.zeros((0, self.dim), dtype=np.float32)
        rows = [_fake_vector(t, self.dim, self.model) for t in batch]
        return np.stack(rows).astype(np.float32)

    @property
    def texts_seen(self) -> list[str]:
        return [t for batch in self.calls for t in batch]

    @property
    def texts_returned(self) -> list[str]:
        return [t for batch in self.returned for t in batch]


class ScriptedProvider:
    """Returns exactly the vector scripted for each text (hand-computable)."""

    def __init__(self, vectors: dict[str, list[float]], model: str = "scripted-model"):
        self.vectors = {k: np.asarray(v, dtype=np.float32) for k, v in vectors.items()}
        self.dim = int(next(iter(self.vectors.values())).shape[0])
        self.model = model
        self.calls: list[list[str]] = []

    def embed(self, texts: list[str]) -> np.ndarray:
        batch = list(texts)
        self.calls.append(batch)
        return np.stack([self.vectors[t] for t in batch]).astype(np.float32)


# --------------------------------------------------------------------------
# Shared helpers
# --------------------------------------------------------------------------


def _content_hash(model: str, dim: int, text: str) -> str:
    """The frozen cache key: sha256("<model>\\n<dim>\\n<text>") hexdigest."""
    return hashlib.sha256(f"{model}\n{dim}\n{text}".encode()).hexdigest()


def _pairs(n: int, prefix: str = "t") -> list[tuple[str, str]]:
    """`n` (chunk_id, text) pairs, all texts distinct."""
    return [(f"c{i}", f"{prefix} {i}") for i in range(n)]


def _ids(pairs: list[tuple[str, str]]) -> list[str]:
    return [chunk_id for chunk_id, _text in pairs]


def _l2(vec: np.ndarray) -> np.ndarray:
    vec = np.asarray(vec, dtype=np.float32)
    return vec / np.linalg.norm(vec)


def _entries_payload(entries: dict[str, dict], model: str = FAKE_MODEL, dim: int = 4) -> dict:
    return {"model": model, "dim": dim, "entries": entries}


def _write_raw_store(path: Path, matrix: np.ndarray, payload: dict) -> None:
    """Write a store's two files by hand (AC-7 corrupt-store fixtures)."""
    path.mkdir(parents=True, exist_ok=True)
    np.save(path / "matrix.npy", matrix)
    (path / "entries.json").write_text(json.dumps(payload), encoding="utf-8")


def _valid_raw_store(path: Path, rows: int = 3, dim: int = 4) -> tuple[np.ndarray, dict]:
    """A hand-written, structurally valid store — the AC-7 baseline.

    Deliberately written with EXACTLY the three required top-level keys, so
    `load` may not depend on any additional field of its own invention.
    """
    matrix = np.stack([_l2(_fake_vector(f"t {i}", dim, FAKE_MODEL)) for i in range(rows)]).astype(
        np.float16
    )
    entries = {
        f"c{i}": {"row": i, "content_hash": _content_hash(FAKE_MODEL, dim, f"t {i}")}
        for i in range(rows)
    }
    payload = _entries_payload(entries, model=FAKE_MODEL, dim=dim)
    _write_raw_store(path, matrix, payload)
    return matrix, payload


def _build_cosine_store(vectors: list[list[float]]):
    """A real EmbeddingStore holding exactly `vectors` (normalized, fp16)."""
    texts = [f"cos-text-{i}" for i in range(len(vectors))]
    provider = ScriptedProvider(dict(zip(texts, vectors, strict=True)))
    store = _new_store()
    store.embed_corpus([(f"cos-{i}", t) for i, t in enumerate(texts)], provider)
    return store


def _embed_until_crash(store, pairs, provider, checkpoint_dir, checkpoint_every):
    """Run `embed_corpus` expecting the scripted provider failure.

    Fails with an explanatory message (rather than an opaque shape error)
    when the provider's scripted 3rd call is never reached — which happens
    exactly when batches are larger than `checkpoint_every` (review I-2).
    """
    try:
        store.embed_corpus(
            pairs,
            provider,
            checkpoint_dir=checkpoint_dir,
            checkpoint_every=checkpoint_every,
        )
    except ProviderBoom:
        return
    pytest.fail(
        f"the FakeProvider was scripted to fail on its 3rd call and embed_corpus "
        f"never reached it: batches must hold AT MOST checkpoint_every "
        f"({checkpoint_every}) items so a checkpoint can be written every "
        f"{checkpoint_every} newly-embedded items. Batch sizes were "
        f"{[len(b) for b in provider.calls]}."
    )


def _marker_value(text: str) -> float:
    """Recover the ordinal encoded in a `doc-<i>` text (0.0 if absent)."""
    tail = text.rsplit("-", 1)[-1]
    return float(tail) if tail.isdigit() else 0.0


def _openai_handler(
    dim: int,
    requests: list[httpx.Request],
    statuses: list[int] | None = None,
    reverse_data: bool = False,
):
    """MockTransport handler: records requests, replies OpenAI-shaped.

    Each returned embedding is `[<ordinal of the text>, 0.0, 0.0, ...]` so a
    row's identity is readable from its first component — that is how the
    "row order == input order" contract is asserted across a batch split.
    `statuses` is a queue of status codes (200 once exhausted).
    """
    queue = list(statuses or [])
    tail = [0.0] * (dim - 1)

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        status = queue.pop(0) if queue else 200
        if status != 200:
            return httpx.Response(status, json={"error": {"message": "upstream boom"}})
        payload = json.loads(request.content)
        texts = payload["input"]
        data = [
            {
                "object": "embedding",
                "index": i,
                "embedding": [_marker_value(text), *tail],
            }
            for i, text in enumerate(texts)
        ]
        if reverse_data:
            data = list(reversed(data))
        return httpx.Response(
            200,
            json={
                "object": "list",
                "data": data,
                "model": payload.get("model"),
                "usage": {"prompt_tokens": len(texts), "total_tokens": len(texts)},
            },
        )

    return handler


def _leaky_transport(recorder: list[str]) -> httpx.MockTransport:
    """A transport whose error TEXT carries the Authorization header.

    The liveness half of the AC-6 error-path test (review I-7): it proves the
    secret is genuinely reachable from the exception the adapter has to
    handle, so "no record contains the key" cannot pass vacuously.
    """

    def handler(request: httpx.Request) -> httpx.Response:
        message = f"connection reset mid-request: headers={dict(request.headers)}"
        recorder.append(message)
        raise httpx.ConnectError(message)

    return httpx.MockTransport(handler)


def _openai_provider(api_key: str, transport: httpx.MockTransport, model: str = OPENAI_MODEL):
    return _attr("OpenAIEmbeddingProvider")(model=model, api_key=api_key, transport=transport)


def _provider_dim(provider) -> int:
    dim = getattr(provider, "dim", None)
    if not isinstance(dim, int) or dim <= 0:
        pytest.fail(f"provider.dim must be a positive int per the Protocol, got {dim!r}")
    return dim


def _never_called(request: httpx.Request) -> httpx.Response:
    raise AssertionError(f"no HTTP request expected here: {request.method} {request.url}")


def _openai_dim(model: str = OPENAI_MODEL) -> int:
    """The adapter's own declared dim — mocked responses must match it, so a
    defensive `arr.shape[1] == self.dim` check in the adapter stays valid."""
    probe = _openai_provider(SENTINEL_KEY, httpx.MockTransport(_never_called), model)
    return _provider_dim(probe)


@contextlib.contextmanager
def _library_loggers_unmuted():
    """Reproduce the repo's own process-wide INFO logging (LESSONS T-014).

    onrecord's ingest entrypoints call `logging.basicConfig(level=INFO)`, and
    httpx's own logger is NOTSET by default so it inherits root. The baseline
    is restored afterwards — including root's handler list, so a
    `basicConfig` that is NOT a no-op (e.g. under `-p no:logging`, where
    pytest has not installed a root handler) cannot leak a StreamHandler into
    the rest of the session (review M-6). An implementation that
    silences/redacts library loggers AROUND its own keyed request still wins,
    because that happens inside the call, after this setup.
    """
    root = logging.getLogger()
    previous_root_level = root.level
    previous_handlers = root.handlers[:]
    library = [logging.getLogger(name) for name in ("httpx", "httpcore", "openai")]
    previous = [(lg, lg.level, lg.propagate) for lg in library]
    logging.basicConfig(level=logging.INFO)
    root.setLevel(logging.INFO)
    for lg in library:
        lg.setLevel(logging.NOTSET)
        lg.propagate = True
    try:
        yield
    finally:
        root.setLevel(previous_root_level)
        root.handlers[:] = previous_handlers
        for lg, level, propagate in previous:
            lg.setLevel(level)
            lg.propagate = propagate


def _assert_capture_is_live(caplog):
    """Precondition for every sentinel test: the root capture really works.

    Without this, silencing every logger — or running under `-p no:logging` —
    would turn "no record contains the key" into a vacuous pass. The canary
    is emitted from a neutral logger so it does not constrain whether the
    implementation silences httpx (which the ticket explicitly permits).
    """
    logging.getLogger("onrecord.tests.canary").info("capture liveness canary %s", CANARY)
    assert any(CANARY in record.getMessage() for record in caplog.records), (
        "precondition failed: the root-level log capture is not live, so a "
        "'no record contains the key' assertion below would pass vacuously"
    )


def _leaking_records(caplog, secret: str) -> list[tuple[str, str]]:
    return [(r.name, r.getMessage()) for r in caplog.records if secret in r.getMessage()]


# ==========================================================================
# AC-1 — cache hit: a second identical embed_corpus run makes ZERO provider
# calls and leaves the matrix untouched.
# ==========================================================================


def test_module_exposes_documented_public_api():
    # spec(T-021:AC-1)
    # Tagged AC-1 as the first AC that touches the module (review M-2 notes
    # the tag is loose — this is a cross-AC surface guard). It is kept first
    # and cheap deliberately: without it, every other AC fails with an
    # opaque AttributeError instead of a named missing symbol.
    mod = _module()
    expected = [
        "EmbeddingProvider",
        "OpenAIEmbeddingProvider",
        "PROVIDERS",
        "get_provider",
        "ProviderNotConfigured",
        "EmbeddingStore",
        "CorruptStore",
        "StoreIdentityMismatch",
        "content_hash",
        "cosine_top_k",
    ]
    missing = [name for name in expected if not hasattr(mod, name)]
    assert missing == [], f"onrecord.rag.embeddings is missing public API symbols: {missing}"


def test_second_embed_corpus_run_makes_zero_provider_calls():
    # spec(T-021:AC-1)
    pairs = _pairs(4)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())

    second = FakeProvider()
    store.embed_corpus(pairs, second)

    assert second.calls == [], (
        f"a fully-cached re-run must not call the provider at all (this is the "
        f"spec's content-hash cache requirement — a paid re-embed otherwise), "
        f"got {second.calls}"
    )


def test_second_embed_corpus_run_leaves_matrix_unchanged():
    # spec(T-021:AC-1)
    pairs = _pairs(4)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    before = np.array(store.matrix, copy=True)

    store.embed_corpus(pairs, FakeProvider())

    assert store.matrix.shape == before.shape, (
        f"a fully-cached re-run must not append rows: {before.shape} -> {store.matrix.shape}"
    )
    assert np.array_equal(store.matrix, before), "a fully-cached re-run must not alter any row"


def test_cache_hit_survives_save_load_round_trip(tmp_path):
    # spec(T-021:AC-1)
    pairs = _pairs(4)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    store.save(tmp_path / "store")

    reloaded = _load_store(tmp_path / "store")
    provider = FakeProvider()
    reloaded.embed_corpus(pairs, provider)

    assert provider.calls == [], (
        f"the cache must survive save/load — a re-freeze against a persisted "
        f"store must make zero provider calls, got {provider.calls}"
    )


# ==========================================================================
# AC-2 — incremental embed, per-chunk rows with call-level de-duplication
# (orchestrator ruling), id-keyed alignment, fp16 L2-normalized rows, and
# the frozen content_hash formula.
# ==========================================================================


def test_incremental_run_sends_only_novel_texts_to_provider():
    # spec(T-021:AC-2)
    cached = _pairs(3)
    novel = [("c3", "brand new three"), ("c4", "brand new four")]
    store = _new_store()
    store.embed_corpus(cached, FakeProvider())

    provider = FakeProvider()
    store.embed_corpus(cached + novel, provider)

    assert provider.texts_seen == ["brand new three", "brand new four"], (
        f"only the 2 uncached texts may be sent, in first-appearance order; got "
        f"{provider.texts_seen}"
    )


def test_rows_for_maps_every_chunk_id_to_its_own_row():
    # spec(T-021:AC-2)
    cached = _pairs(3)
    novel = [("c3", "brand new three"), ("c4", "brand new four")]
    store = _new_store()
    store.embed_corpus(cached, FakeProvider())
    store.embed_corpus(cached + novel, FakeProvider())

    rows = store.rows_for(_ids(cached + novel))

    assert rows == [0, 1, 2, 3, 4], (
        f"rows are first-appearance order across ALL runs: the 3 cached chunks keep "
        f"rows 0..2 and the 2 novel chunks append at 3..4; got {rows}"
    )


def test_rows_for_returns_none_for_an_unknown_chunk_id():
    # spec(T-021:AC-2)
    pairs = _pairs(2)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())

    rows = store.rows_for(["NEVER-EMBEDDED", "c0"])

    assert rows == [None, 0], f"an absent chunk_id maps to None, never to a bogus row: {rows}"


def test_rows_for_is_chunk_id_keyed_not_content_hash_keyed():
    # spec(T-021:AC-2)
    # Tripwire for the T-022 escalation in this module's docstring. Both id
    # spaces are `str`, so handing `rows_for` a content hash yields a silent
    # total miss rather than an error — this test makes that loud HERE.
    pairs = _pairs(3)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())

    hash_of_t0 = _content_hash(FAKE_MODEL, 4, "t 0")

    assert store.rows_for([hash_of_t0]) == [None], (
        "rows_for is keyed by chunk_id, NOT by content hash (orchestrator ruling: "
        "storage is per-chunk). T-022 must call rows_for(chunk_ids) and use the "
        "entry's recorded content_hash to VERIFY the row it got back"
    )
    assert store.rows_for(["c0"]) == [0]


def test_entry_for_records_the_content_hash_per_chunk_id():
    # spec(T-021:AC-2)
    pairs = _pairs(3) + [("c9", "extra nine")]
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())

    recorded = {chunk_id: store.entry_for(chunk_id) for chunk_id, _text in pairs}

    assert recorded == {
        "c0": {"row": 0, "content_hash": _content_hash(FAKE_MODEL, 4, "t 0")},
        "c1": {"row": 1, "content_hash": _content_hash(FAKE_MODEL, 4, "t 1")},
        "c2": {"row": 2, "content_hash": _content_hash(FAKE_MODEL, 4, "t 2")},
        "c9": {"row": 3, "content_hash": _content_hash(FAKE_MODEL, 4, "extra nine")},
    }, f"entry_for must return exactly {{'row', 'content_hash'}} per chunk_id; got {recorded}"


def test_content_hash_matches_the_frozen_formula():
    # spec(T-021:AC-2)
    # Review I-4: frozen against hard-coded literals so T-022 can IMPORT this
    # instead of re-deriving `sha256(f"{model}\n{dim}\n{text}")` by hand. Two
    # frozen suites each encoding the same string concatenation is the
    # T-003/T-004 recurrence in miniature; any drift is a silent total miss.
    content_hash = _attr("content_hash")

    assert content_hash(FAKE_MODEL, 4, "t 0") == (
        "faabe9a72d8ffa4fa78c0bfd627ddbcd50bddf6908a4d623604d7bdf012318b2"
    )
    assert content_hash(OPENAI_MODEL, 1536, "hello world") == (
        "c92e2a558b09ad70afffa663155cd9cd7f6cfe27318ddb3c04189824ab068cc0"
    )


def test_content_hash_is_dim_scoped_at_the_same_model_name():
    # spec(T-021:AC-2)
    # plan-review M-9, "distinct keys" half (see decision 10 in the docstring).
    content_hash = _attr("content_hash")

    at_4 = content_hash("shared-model", 4, SHARED_TEXT)
    at_8 = content_hash("shared-model", 8, SHARED_TEXT)

    assert at_4 != at_8, (
        "dim is part of the key, so a model whose `dimensions` parameter changes "
        "cannot poison the cache at the same model name"
    )
    assert at_4 == "302a08e9a712ae74c6bb98803d880d876f5546bbae6f64880fa1873e79532cec"
    assert at_8 == "e51c89f57535d5072dd15e32265b5bf936401a03277be02cf95e12be2c721dbb"


def test_embedding_at_a_different_dim_raises_store_identity_mismatch():
    # spec(T-021:AC-2)
    # decision 10: AC-2's literal "distinct entries" is impossible (one packed
    # N x dim matrix cannot hold both), so the collision is refused instead.
    store = _new_store()
    store.embed_corpus([("c0", SHARED_TEXT)], FakeProvider(dim=4, model="shared-model"))

    with pytest.raises(_attr("StoreIdentityMismatch")) as excinfo:
        store.embed_corpus([("c1", SHARED_TEXT)], FakeProvider(dim=8, model="shared-model"))

    message = str(excinfo.value)
    assert "4" in message and "8" in message, (
        f"the error must name both dims so the operator knows which store to use; got {message!r}"
    )


def test_store_records_the_provider_identity_it_was_built_with():
    # spec(T-021:AC-2)
    store = _new_store()
    store.embed_corpus(_pairs(2), FakeProvider(dim=4, model=FAKE_MODEL))

    assert store.model == FAKE_MODEL
    assert store.dim == 4


def test_stored_rows_are_l2_normalized_fp16_of_provider_vectors():
    # spec(T-021:AC-2)
    pairs = _pairs(3)
    provider = FakeProvider()
    store = _new_store()
    store.embed_corpus(pairs, provider)

    assert store.matrix.dtype == np.float16, (
        f"the packed matrix is fp16 (0.78 GB at 265K x 1536 — fp32 would double it): "
        f"got {store.matrix.dtype}"
    )
    for i, (_chunk_id, text) in enumerate(pairs):
        expected = _l2(_fake_vector(text, provider.dim, provider.model))
        row = store.matrix[i].astype(np.float32)
        assert np.allclose(row, expected, atol=1e-3), (
            f"row {i} must be the L2-normalized provider vector within fp16 tolerance: "
            f"{row} != {expected}"
        )
        assert float(np.linalg.norm(row)) == pytest.approx(1.0, abs=2e-3), (
            f"rows are normalized ONCE at ingest so cosine is a plain dot product; "
            f"row {i} has norm {float(np.linalg.norm(row))}"
        )


# --- Orchestrator ruling: duplicate text -> per-chunk rows, one API call ---


def test_duplicate_texts_get_one_row_per_chunk():
    # spec(T-021:AC-2)
    # Ruling side (b): storage is per-chunk. 63 documents in corpus v1 share
    # text with another document; identity chunking turns each into its own
    # chunk, and T-022 resolves rows per chunk.
    pairs = [("DOC-A", SHARED_TEXT), ("DOC-B", SHARED_TEXT), ("DOC-C", "something else")]
    store = _new_store()

    store.embed_corpus(pairs, FakeProvider())

    assert store.matrix.shape[0] == 3, (
        f"three chunks must occupy three rows even though two share text — a "
        f"text-keyed store would collapse them to 2 and break T-022's per-chunk "
        f"verification; got {store.matrix.shape[0]} rows"
    )
    assert store.rows_for(["DOC-A", "DOC-B", "DOC-C"]) == [0, 1, 2]


def test_duplicate_text_is_billed_to_the_provider_only_once():
    # spec(T-021:AC-2)
    # Ruling side (a): de-duplication moves to the API-CALL level. This is the
    # spend guarantee the content-hash cache exists for.
    pairs = [("DOC-A", SHARED_TEXT), ("DOC-B", SHARED_TEXT), ("DOC-C", "something else")]
    provider = FakeProvider()
    store = _new_store()

    store.embed_corpus(pairs, provider)

    assert provider.texts_seen.count(SHARED_TEXT) == 1, (
        f"an identical text must be sent to the provider exactly once per run, "
        f"however many chunks carry it; provider saw {provider.texts_seen}"
    )
    assert sorted(provider.texts_seen) == sorted([SHARED_TEXT, "something else"])


def test_duplicate_text_rows_hold_identical_vector_bytes():
    # spec(T-021:AC-2)
    pairs = [("DOC-A", SHARED_TEXT), ("DOC-B", SHARED_TEXT)]
    store = _new_store()

    store.embed_corpus(pairs, FakeProvider())

    row_a = store.matrix[store.entry_for("DOC-A")["row"]]
    row_b = store.matrix[store.entry_for("DOC-B")["row"]]
    assert np.array_equal(row_a, row_b), (
        "the second chunk's vector is COPIED from the first (not re-requested and "
        "not left empty), so identical text yields byte-identical rows"
    )
    assert store.entry_for("DOC-A")["content_hash"] == store.entry_for("DOC-B")["content_hash"]


def test_text_already_in_the_store_is_copied_into_a_new_chunks_row_unbilled():
    # spec(T-021:AC-2)
    # The cross-run half of the ruling: "from this run OR the existing store".
    store = _new_store()
    store.embed_corpus([("DOC-A", SHARED_TEXT)], FakeProvider())

    provider = FakeProvider()
    store.embed_corpus([("DOC-B", SHARED_TEXT)], provider)

    assert provider.calls == [], (
        f"a text already embedded in an EARLIER run must never be re-billed; the "
        f"provider was called with {provider.calls}"
    )
    assert store.rows_for(["DOC-A", "DOC-B"]) == [0, 1]
    assert np.array_equal(store.matrix[0], store.matrix[1])


def test_store_with_duplicate_texts_reloads_through_its_own_validation(tmp_path):
    # spec(T-021:AC-2)
    # Review C-2: an implementation with no call-level de-duplication appends
    # one row per occurrence but only one entry, producing a store that saves
    # happily and then fails its OWN load validation — discovered only after
    # the multi-hour, ~$30-80 run, and degrading T-024 to a blanket 503.
    pairs = [("DOC-A", SHARED_TEXT), ("DOC-B", "unique one"), ("DOC-C", SHARED_TEXT)]
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    store.save(tmp_path / "store")

    reloaded = _load_store(tmp_path / "store")

    assert reloaded.matrix.shape[0] == 3, (
        f"the store must hold exactly one row per chunk — {reloaded.matrix.shape[0]} "
        f"rows for 3 chunks means entries and matrix have diverged"
    )
    assert reloaded.rows_for(["DOC-A", "DOC-B", "DOC-C"]) == [0, 1, 2]


# --- C-3 adversarial: alignment is id-keyed, never positional ---


def test_permuted_store_with_extra_rows_resolves_by_chunk_id_not_position():
    # spec(T-021:AC-2)
    # C-3 adversarial: same 4 chunks, different insertion order, PLUS 2 extra
    # rows appended. Row order is first-appearance order across all runs, so
    # position is meaningless; only chunk_id -> row is authoritative.
    pairs = _pairs(4)
    reference = _new_store()
    reference.embed_corpus(pairs, FakeProvider())

    permuted_pairs = [pairs[2], pairs[0], pairs[3], pairs[1], ("c4", "t 4"), ("c5", "t 5")]
    permuted = _new_store()
    permuted.embed_corpus(permuted_pairs, FakeProvider())

    assert reference.rows_for(_ids(pairs)) == [0, 1, 2, 3]
    assert permuted.rows_for(_ids(pairs)) == [1, 3, 0, 2], (
        f"rows must follow first-appearance order in THIS store, not the caller's "
        f"pair order; got {permuted.rows_for(_ids(pairs))}"
    )
    for chunk_id, text in pairs:
        entry = permuted.entry_for(chunk_id)
        assert entry["content_hash"] == _content_hash(FAKE_MODEL, 4, text), (
            f"the recorded content_hash must still describe {chunk_id}'s own text "
            f"in a permuted, extended store; got {entry!r}"
        )
        assert np.array_equal(
            permuted.matrix[entry["row"]],
            reference.matrix[reference.entry_for(chunk_id)["row"]],
        ), f"the vector reached via chunk_id must be identical in both stores ({chunk_id})"
    assert not np.array_equal(permuted.matrix[0], reference.matrix[0]), (
        "the adversarial point: a consumer that indexed positionally (row i == "
        "pairs[i]) would silently read the WRONG chunk's vector here"
    )


def test_swapped_content_hashes_are_visible_through_entry_for(tmp_path):
    # spec(T-021:AC-2)
    # C-3 adversarial: a store whose chunk_ids all match and whose length
    # checks all pass, but whose recorded content_hashes have drifted.
    # `len(entries) == matrix.shape[0]` proves NOTHING — only id-level
    # verification catches it, and this is exactly the signal T-022 turns into
    # its `StoreMismatch`.
    pairs = _pairs(6)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    path = tmp_path / "store"
    store.save(path)

    entries_path = path / "entries.json"
    payload = json.loads(entries_path.read_text(encoding="utf-8"))
    entries = payload["entries"]
    entries["c0"]["content_hash"], entries["c1"]["content_hash"] = (
        entries["c1"]["content_hash"],
        entries["c0"]["content_hash"],
    )
    entries_path.write_text(json.dumps(payload), encoding="utf-8")

    reloaded = _load_store(path)

    assert len(entries) == reloaded.matrix.shape[0] == 6, (
        "precondition of the adversarial case: the store is structurally valid, "
        "so a length-equality check passes while the alignment is wrong"
    )
    assert reloaded.entry_for("c0")["content_hash"] == _content_hash(FAKE_MODEL, 4, "t 1"), (
        "entry_for must report the content_hash RECORDED on disk (not one silently "
        "recomputed at load), which is what lets T-022 detect drift"
    )
    row = reloaded.matrix[reloaded.entry_for("c0")["row"]].astype(np.float32)
    assert np.allclose(row, _l2(_fake_vector("t 0", 4, FAKE_MODEL)), atol=1e-3), (
        "the vector itself is still 't 0' — the recorded hash is the ONLY signal "
        "that the id-level correspondence broke"
    )


# ==========================================================================
# AC-3 — store round-trip, on-disk shape, atomic save.
# ==========================================================================


def test_save_load_round_trip_preserves_dtype_shape_and_entries(tmp_path):
    # spec(T-021:AC-3)
    pairs = _pairs(5)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    store.save(tmp_path / "store")

    reloaded = _load_store(tmp_path / "store")

    assert reloaded.matrix.dtype == np.float16
    assert reloaded.matrix.shape == store.matrix.shape == (5, 4)
    assert np.array_equal(reloaded.matrix, store.matrix)
    ids = _ids(pairs)
    assert [reloaded.entry_for(i) for i in ids] == [store.entry_for(i) for i in ids]
    assert sorted(reloaded.entry_for(i)["row"] for i in ids) == [0, 1, 2, 3, 4], (
        "every row must be claimed by exactly one chunk_id after a round-trip"
    )


def test_save_load_round_trip_preserves_store_identity(tmp_path):
    # spec(T-021:AC-3)
    # Review I-5: without persisted identity, pointing a differently-modelled
    # store at a query is a silent total miss rather than a typed failure.
    store = _new_store()
    store.embed_corpus(_pairs(3), FakeProvider(dim=4, model=FAKE_MODEL))
    store.save(tmp_path / "store")

    reloaded = _load_store(tmp_path / "store")

    assert reloaded.model == FAKE_MODEL
    assert reloaded.dim == 4


def test_entries_json_on_disk_carries_identity_and_chunk_keyed_entries(tmp_path):
    # spec(T-021:AC-3)
    pairs = _pairs(3)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    store.save(tmp_path / "store")

    payload = json.loads((tmp_path / "store" / "entries.json").read_text(encoding="utf-8"))

    assert set(payload) >= {"model", "dim", "entries"}, (
        f"entries.json carries the store's identity alongside its entries; extra "
        f"keys (e.g. a format version) are allowed but these three are required. "
        f"Got keys {sorted(payload)}"
    )
    assert payload["model"] == FAKE_MODEL
    assert payload["dim"] == 4
    assert payload["entries"] == {
        "c0": {"row": 0, "content_hash": _content_hash(FAKE_MODEL, 4, "t 0")},
        "c1": {"row": 1, "content_hash": _content_hash(FAKE_MODEL, 4, "t 1")},
        "c2": {"row": 2, "content_hash": _content_hash(FAKE_MODEL, 4, "t 2")},
    }, f"entries is chunk_id -> {{'row', 'content_hash'}} exactly; got {payload['entries']}"


def test_saved_matrix_file_is_float16_on_disk(tmp_path):
    # spec(T-021:AC-3)
    # Adversarial: fp32 leaking into the packed store doubles a 0.78 GB
    # resident matrix and is invisible to any in-memory assertion that runs
    # before the save.
    pairs = _pairs(5)
    store = _new_store()
    store.embed_corpus(pairs, FakeProvider())
    store.save(tmp_path / "store")

    raw = np.load(tmp_path / "store" / "matrix.npy")

    assert raw.dtype == np.float16, f"matrix.npy must be fp16 on disk, got {raw.dtype}"
    assert raw.shape == (5, 4)
    assert raw.nbytes == 5 * 4 * 2, (
        f"fp16 packing means exactly 2 bytes per component (N*dim*2 = 40), got {raw.nbytes}"
    )


def test_load_missing_directory_raises_file_not_found(tmp_path):
    # spec(T-021:AC-3)
    missing = tmp_path / "no-such-store"

    with pytest.raises(FileNotFoundError) as excinfo:
        _load_store(missing)

    assert "no-such-store" in str(excinfo.value), (
        f"the error must name the missing store path, got {excinfo.value!r}"
    )


def test_load_raises_file_not_found_when_a_store_file_is_absent(tmp_path):
    # spec(T-021:AC-3)
    # Review M-5: T-024's degradation ladder distinguishes "missing" from
    # "CorruptStore"; a half-populated directory must land on the missing rung.
    path = tmp_path / "store"
    _valid_raw_store(path)
    (path / "matrix.npy").unlink()

    with pytest.raises(FileNotFoundError) as excinfo:
        _load_store(path)

    assert "matrix.npy" in str(excinfo.value), (
        f"the error must name the absent file, got {excinfo.value!r}"
    )


def test_interrupted_save_leaves_the_previous_store_loadable(tmp_path, monkeypatch):
    # spec(T-021:AC-3)
    # Atomicity asserted by BEHAVIOR: whatever a crashed save leaves behind,
    # the previously-saved store must still load intact and self-consistent.
    #
    # `np.save` here writes its file and THEN raises ("monkeypatched np.save
    # raising after the first file", per AC-3) — the realistic mid-save crash,
    # where the first file has already hit the disk. That ordering is what
    # makes this bite in BOTH in-place write orders: matrix-first leaves a new
    # matrix beside old entries, entries-first leaves new entries beside an
    # old matrix. Only temp-names-then-os.replace survives.
    path = tmp_path / "store"
    first_pairs = _pairs(3)
    first = _new_store()
    first.embed_corpus(first_pairs, FakeProvider())
    first.save(path)
    expected_matrix = np.array(first.matrix, copy=True)

    second = _new_store()
    second.embed_corpus(first_pairs + [("c7", "seven"), ("c8", "eight")], FakeProvider())
    monkeypatch.setattr(np, "save", _save_then_fail)
    try:
        second.save(path)
    except OSError:
        pass
    else:
        pytest.fail(
            "save() completed even though numpy.save was patched to raise. AC-3 "
            "pins the interruption through `np.save`, so the matrix write must go "
            "through numpy.save(...) — np.lib.format.write_array or a raw file "
            "handle will not trip this test (review M-1)."
        )
    finally:
        monkeypatch.undo()

    reloaded = _load_store(path)
    assert np.array_equal(reloaded.matrix, expected_matrix), (
        "a save interrupted mid-write must leave the PREVIOUS store fully intact "
        "(write both files to temp names, then os.replace)"
    )
    assert [reloaded.entry_for(i) for i in _ids(first_pairs)] == [
        {"row": 0, "content_hash": _content_hash(FAKE_MODEL, 4, "t 0")},
        {"row": 1, "content_hash": _content_hash(FAKE_MODEL, 4, "t 1")},
        {"row": 2, "content_hash": _content_hash(FAKE_MODEL, 4, "t 2")},
    ]
    assert reloaded.rows_for(["c7"]) == [None], (
        "the interrupted save must not have leaked the new run's entries onto the "
        "old matrix — that is exactly the silent mis-map the atomic contract bans"
    )


def _save_then_fail(*args, **kwargs):
    """Let np.save write its file, then blow up — see the test above."""
    _REAL_NP_SAVE(*args, **kwargs)
    raise OSError("simulated crash immediately after np.save wrote its file")


# ==========================================================================
# AC-4 — cosine_top_k on hand-computable vectors.
# ==========================================================================


def test_cosine_top_k_returns_hand_computed_order_and_scores():
    # spec(T-021:AC-4)
    store = _build_cosine_store([[1, 0, 0, 0], [0, 1, 0, 0], [1, 1, 0, 0], [-1, 0, 0, 0]])
    query = np.array([2, 0, 0, 0], dtype=np.float32)  # unnormalized on purpose

    results = _attr("cosine_top_k")(store, query, 4)

    assert [row for row, _ in results] == [0, 2, 1, 3], (
        f"expected order by cosine similarity 1.0 > 0.7071 > 0.0 > -1.0; got {results}"
    )
    expected_scores = [1.0, 0.7071067811865476, 0.0, -1.0]
    for (row, score), expected in zip(results, expected_scores, strict=True):
        assert score == pytest.approx(expected, abs=1e-3), (
            f"row {row}: cosine must be the dot product of L2-normalized vectors "
            f"(query normalized too), expected {expected}, got {score}"
        )


def test_cosine_top_k_breaks_ties_by_ascending_row_index():
    # spec(T-021:AC-4)
    store = _build_cosine_store([[1, 0, 0, 0], [0, 1, 0, 0], [1, 0, 0, 0], [0, 1, 0, 0]])
    query = np.array([1, 0, 0, 0], dtype=np.float32)

    results = _attr("cosine_top_k")(store, query, 4)

    assert [row for row, _ in results] == [0, 2, 1, 3], (
        f"equal scores must be ordered by ascending row index (deterministic ties); got {results}"
    )


def test_cosine_top_k_truncates_to_k():
    # spec(T-021:AC-4)
    store = _build_cosine_store([[1, 0, 0, 0], [0, 1, 0, 0], [1, 1, 0, 0], [-1, 0, 0, 0]])
    query = np.array([1, 0, 0, 0], dtype=np.float32)

    results = _attr("cosine_top_k")(store, query, 2)

    assert [row for row, _ in results] == [0, 2], f"k=2 must return the top 2 rows: {results}"


def test_cosine_top_k_with_k_larger_than_the_corpus_returns_every_row():
    # spec(T-021:AC-4)
    # T-022 calls cosine_top_k(..., k=len(chunks)), so k >= N is a real path.
    store = _build_cosine_store([[1, 0, 0, 0], [0, 1, 0, 0], [1, 1, 0, 0]])
    query = np.array([1, 0, 0, 0], dtype=np.float32)

    results = _attr("cosine_top_k")(store, query, 25)

    assert len(results) == 3, f"k > N must clamp to N rows, not pad or raise: {results}"


def test_cosine_top_k_blocked_path_matches_unblocked():
    # spec(T-021:AC-4)
    store = _build_cosine_store(
        [[1, 0, 0, 0], [0, 1, 0, 0], [1, 1, 0, 0], [-1, 0, 0, 0], [0, 0, 1, 0]]
    )
    query = np.array([0.5, 0.25, 0, 0], dtype=np.float32)
    cosine_top_k = _attr("cosine_top_k")

    blocked = cosine_top_k(store, query, 5, block_rows=2)
    unblocked = cosine_top_k(store, query, 5, block_rows=8192)

    assert [row for row, _ in blocked] == [row for row, _ in unblocked], (
        f"blocking is a memory bound, never a semantic change: {blocked} != {unblocked}"
    )
    for (_row, a), (_row2, b) in zip(blocked, unblocked, strict=True):
        assert a == pytest.approx(b, abs=1e-6)


# ==========================================================================
# AC-5 — OpenAI-shaped adapter over httpx.MockTransport (zero network) and
# the key-presence/key-absence branches (plan-review I-5).
# ==========================================================================


def test_openai_adapter_posts_model_url_and_bearer_header():
    # spec(T-021:AC-5)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    transport = httpx.MockTransport(_openai_handler(dim, requests))
    provider = _openai_provider(SENTINEL_KEY, transport)

    provider.embed(["doc-0", "doc-1", "doc-2"])

    assert len(requests) == 1
    request = requests[0]
    assert request.method == "POST"
    assert request.url.host == "api.openai.com"
    assert request.url.path == "/v1/embeddings"
    assert request.headers.get("authorization") == f"Bearer {SENTINEL_KEY}"
    body = json.loads(request.content)
    assert body["model"] == OPENAI_MODEL
    assert body["input"] == ["doc-0", "doc-1", "doc-2"], (
        f"the request must carry the texts unchanged and in order: {body.get('input')}"
    )


def test_openai_adapter_returns_float32_rows_in_input_order():
    # spec(T-021:AC-5)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    # The API returns `data` with an explicit `index` per row; this mock hands
    # it back REVERSED, so an adapter that trusts list order silently permutes
    # every embedding. Row order == input order is the Protocol's contract.
    transport = httpx.MockTransport(_openai_handler(dim, requests, reverse_data=True))
    provider = _openai_provider(SENTINEL_KEY, transport)

    out = provider.embed(["doc-0", "doc-1", "doc-2"])

    assert isinstance(out, np.ndarray)
    assert out.dtype == np.float32, f"the Protocol pins float32 output, got {out.dtype}"
    assert out.shape == (3, dim)
    assert [float(row[0]) for row in out] == [0.0, 1.0, 2.0], (
        "rows must be ordered by the response's `index` field (== input order), not "
        "by the order the objects happen to arrive in"
    )


def test_openai_adapter_splits_513_texts_into_two_requests():
    # spec(T-021:AC-5)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    transport = httpx.MockTransport(_openai_handler(dim, requests))
    provider = _openai_provider(SENTINEL_KEY, transport)
    texts = [f"doc-{i}" for i in range(513)]

    out = provider.embed(texts)

    sizes = [len(json.loads(r.content)["input"]) for r in requests]
    assert len(requests) == 2, f"513 texts must split into 2 requests, got sizes {sizes}"
    assert max(sizes) <= 512, f"no request may exceed the 512-text batch cap: {sizes}"
    assert sum(sizes) == 513
    assert out.shape == (513, dim)
    assert [float(row[0]) for row in out] == [float(i) for i in range(513)], (
        "batches must be concatenated back in input order"
    )


def test_openai_adapter_retries_429_then_succeeds(monkeypatch):
    # spec(T-021:AC-5)
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    transport = httpx.MockTransport(_openai_handler(dim, requests, statuses=[429]))
    provider = _openai_provider(SENTINEL_KEY, transport)

    out = provider.embed(["doc-0", "doc-1"])

    assert len(requests) == 2, (
        f"a 429 must be retried with backoff, not surfaced: {len(requests)} request(s) made"
    )
    assert out.shape == (2, dim)
    assert [float(row[0]) for row in out] == [0.0, 1.0]


def test_openai_adapter_raises_after_exhausting_retries_on_5xx(monkeypatch):
    # spec(T-021:AC-5)
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    transport = httpx.MockTransport(_openai_handler(dim, requests, statuses=[500] * 20))
    provider = _openai_provider(SENTINEL_KEY, transport)

    # The concrete exception type is the implementer's choice — only "fails
    # loudly, bounded" is frozen here ("max 3" is ambiguous between attempts
    # and retries).
    with pytest.raises(Exception) as excinfo:
        provider.embed(["doc-0"])

    assert not isinstance(excinfo.value, AssertionError)
    assert 2 <= len(requests) <= 5, (
        f"a permanently-500 batch must be retried (max 3) and then FAIL LOUDLY — "
        f"never silently return partial or zero vectors; requests made: {len(requests)}"
    )


def test_missing_openai_key_raises_provider_not_configured(monkeypatch):
    # spec(T-021:AC-5)
    # plan-review I-5: delenv(raising=False) so the branch is pinned whether or
    # not the ambient environment happens to have a key.
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    provider_not_configured = _attr("ProviderNotConfigured")

    with pytest.raises(provider_not_configured) as excinfo:
        _attr("OpenAIEmbeddingProvider")(model=OPENAI_MODEL)

    assert "OPENAI_API_KEY" in str(excinfo.value), (
        f"the error must be actionable — it names the env var to set; got {excinfo.value!r}"
    )


def test_present_openai_key_constructs_without_raising(monkeypatch):
    # spec(T-021:AC-5)
    # The mirrored branch of I-5: neither side may be environmentally lucky.
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)

    provider = _attr("OpenAIEmbeddingProvider")(model=OPENAI_MODEL)

    assert provider.model == OPENAI_MODEL
    assert _provider_dim(provider) > 0


def test_get_provider_defaults_to_the_openai_adapter(monkeypatch):
    # spec(T-021:AC-5)
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)
    monkeypatch.delenv("ONRECORD_EMBED_PROVIDER", raising=False)
    monkeypatch.delenv("ONRECORD_EMBED_MODEL", raising=False)

    provider = _attr("get_provider")()

    assert isinstance(provider, _attr("OpenAIEmbeddingProvider"))
    assert provider.model == OPENAI_MODEL, (
        f"default model is text-embedding-3-small; got {provider.model!r}"
    )


def test_get_provider_honors_the_model_override_env(monkeypatch):
    # spec(T-021:AC-5)
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)
    monkeypatch.setenv("ONRECORD_EMBED_PROVIDER", "openai")
    monkeypatch.setenv("ONRECORD_EMBED_MODEL", "text-embedding-3-large")

    provider = _attr("get_provider")()

    assert provider.model == "text-embedding-3-large", (
        f"ONRECORD_EMBED_MODEL overrides the adapter default; got {provider.model!r}"
    )


def test_get_provider_without_a_key_raises_instead_of_returning_a_fake(monkeypatch):
    # spec(T-021:AC-5)
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("ONRECORD_EMBED_PROVIDER", raising=False)
    monkeypatch.delenv("ONRECORD_EMBED_MODEL", raising=False)  # review M-3

    with pytest.raises(_attr("ProviderNotConfigured")) as excinfo:
        _attr("get_provider")()

    assert "OPENAI_API_KEY" in str(excinfo.value), (
        "locked decision: an unconfigured provider raises an actionable error and "
        "NEVER silently returns a fake (fakes are test-injected only)"
    )


def test_providers_registry_holds_openai_and_no_speculative_voyage():
    # spec(T-021:AC-5)
    providers = _attr("PROVIDERS")

    assert isinstance(providers, dict)
    assert "openai" in providers, f"PROVIDERS must register the openai adapter: {providers}"
    assert "voyage" not in providers, (
        "the Voyage adapter is an OPEN QUESTION for the owner — it must not be "
        "implemented speculatively (ticket Out of Scope)"
    )


# ==========================================================================
# AC-6 — secret-leak sentinel at the ROOT logger (LESSONS.md T-014).
# Every test here carries a liveness precondition (review I-7).
# ==========================================================================


def test_no_log_record_contains_the_api_key_on_the_success_path(caplog):
    # spec(T-021:AC-6)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    transport = httpx.MockTransport(_openai_handler(dim, requests))
    provider = _openai_provider(SENTINEL_KEY, transport)

    with _library_loggers_unmuted(), caplog.at_level(logging.INFO):  # root: EVERY logger
        provider.embed(["doc-0", "doc-1"])
        _assert_capture_is_live(caplog)

    assert requests, "precondition: the mocked request must actually have been made"
    assert requests[0].headers.get("authorization") == f"Bearer {SENTINEL_KEY}", (
        "precondition: the sentinel really was in flight during the captured window"
    )
    assert _leaking_records(caplog, SENTINEL_KEY) == [], (
        f"the API key must never reach ANY log record — root + library loggers "
        f"(LESSONS T-014): {_leaking_records(caplog, SENTINEL_KEY)}"
    )
    assert SENTINEL_KEY not in caplog.text


def test_no_log_record_contains_the_api_key_on_an_http_error_path(caplog, monkeypatch):
    # spec(T-021:AC-6)
    # Error paths are where keys leak — a naive `log.warning("embed failed: %s",
    # exc)` re-emits whatever the failure carries.
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    dim = _openai_dim()
    requests: list[httpx.Request] = []
    transport = httpx.MockTransport(_openai_handler(dim, requests, statuses=[401, 500, 500, 500]))
    provider = _openai_provider(SENTINEL_KEY, transport)

    with _library_loggers_unmuted(), caplog.at_level(logging.INFO):
        with pytest.raises(Exception) as excinfo:
            provider.embed(["doc-0"])
        _assert_capture_is_live(caplog)

    assert not isinstance(excinfo.value, AssertionError)
    assert requests[0].headers.get("authorization") == f"Bearer {SENTINEL_KEY}", (
        "precondition: the sentinel really was in flight on the failing request"
    )
    assert _leaking_records(caplog, SENTINEL_KEY) == [], (
        f"the API key must never reach ANY log record on a failing request either: "
        f"{_leaking_records(caplog, SENTINEL_KEY)}"
    )
    assert SENTINEL_KEY not in caplog.text
    assert SENTINEL_KEY not in str(excinfo.value), (
        "nor may it appear in exception text (it propagates into tracebacks and "
        "any caller's own logging)"
    )
    assert SENTINEL_KEY not in repr(excinfo.value)


def test_transport_error_text_carrying_the_key_is_not_re_emitted(caplog):
    # spec(T-021:AC-6)
    # Decision 11 / review I-7: the liveness half. The transport raises an
    # error whose own message embeds the Authorization header, so the secret is
    # provably reachable from the exception the adapter must handle. The
    # adapter must wrap it in its own credential-free message rather than
    # re-emitting `str(exc)`.
    raised: list[str] = []
    provider = _openai_provider(SENTINEL_KEY, _leaky_transport(raised))

    with _library_loggers_unmuted(), caplog.at_level(logging.INFO):
        with pytest.raises(Exception) as excinfo:
            provider.embed(["doc-0"])
        _assert_capture_is_live(caplog)

    assert raised and all(SENTINEL_KEY in message for message in raised), (
        "precondition: the transport error's own text must contain the key, "
        "otherwise this test proves nothing"
    )
    assert not isinstance(excinfo.value, AssertionError)
    assert SENTINEL_KEY not in str(excinfo.value), (
        "the adapter must not re-emit a transport error's text verbatim — catch "
        "httpx.HTTPError and raise your own message with no credential material"
    )
    assert SENTINEL_KEY not in repr(excinfo.value)
    assert _leaking_records(caplog, SENTINEL_KEY) == [], (
        f"nor may it be logged on the way past: {_leaking_records(caplog, SENTINEL_KEY)}"
    )


def test_provider_repr_does_not_expose_the_api_key():
    # spec(T-021:AC-6)
    provider = _openai_provider(SENTINEL_KEY, httpx.MockTransport(_never_called))

    assert SENTINEL_KEY not in repr(provider)
    assert SENTINEL_KEY not in str(provider), (
        "a default dataclass/attrs repr embeds the key and lands it in every log "
        "line that interpolates the provider (LESSONS T-014)"
    )


# ==========================================================================
# AC-7 — CorruptStore / StoreIdentityMismatch validation at load
# (plan-review I-10c, review I-5).
# ==========================================================================


def test_a_valid_store_loads_clean(tmp_path):
    # spec(T-021:AC-7)
    path = tmp_path / "store"
    matrix, payload = _valid_raw_store(path)

    store = _load_store(path)

    assert store.matrix.dtype == np.float16
    assert np.array_equal(store.matrix, matrix)
    for chunk_id, entry in payload["entries"].items():
        assert store.entry_for(chunk_id) == entry


def test_load_raises_corrupt_store_on_entry_row_count_mismatch(tmp_path):
    # spec(T-021:AC-7)
    path = tmp_path / "store"
    matrix, payload = _valid_raw_store(path, rows=3)
    payload["entries"].pop("c0")  # 2 entries vs a 3-row matrix
    _write_raw_store(path, matrix, payload)

    with pytest.raises(_attr("CorruptStore")) as excinfo:
        _load_store(path)

    message = str(excinfo.value)
    assert "entries" in message and "matrix" in message, (
        f"the error must name the mismatching files, got {message!r}"
    )


def test_load_raises_corrupt_store_on_a_duplicate_row_index(tmp_path):
    # spec(T-021:AC-7)
    path = tmp_path / "store"
    matrix, payload = _valid_raw_store(path, rows=3)
    payload["entries"]["c1"]["row"] = 0  # two chunk_ids claiming row 0
    _write_raw_store(path, matrix, payload)

    with pytest.raises(_attr("CorruptStore")) as excinfo:
        _load_store(path)

    message = str(excinfo.value).lower()
    assert "entries" in message, f"the error must name entries.json, got {message!r}"
    assert "duplicate" in message or "row" in message, (
        f"the error must name the defect (duplicate row index), got {message!r}"
    )


def test_load_raises_corrupt_store_on_an_out_of_range_row_index(tmp_path):
    # spec(T-021:AC-7)
    path = tmp_path / "store"
    matrix, payload = _valid_raw_store(path, rows=3)
    payload["entries"]["c2"]["row"] = 7  # beyond the 3-row matrix
    _write_raw_store(path, matrix, payload)

    with pytest.raises(_attr("CorruptStore")) as excinfo:
        _load_store(path)

    message = str(excinfo.value).lower()
    assert "entries" in message
    assert "row" in message, f"the error must name the offending row index, got {message!r}"


def test_load_raises_corrupt_store_on_a_float32_matrix(tmp_path):
    # spec(T-021:AC-7)
    # Adversarial: fp32 leaking into the packed store must be rejected at the
    # door, not silently accepted (it doubles resident memory and breaks the
    # dtype half of the round-trip contract).
    path = tmp_path / "store"
    matrix, payload = _valid_raw_store(path, rows=3)
    _write_raw_store(path, matrix.astype(np.float32), payload)

    with pytest.raises(_attr("CorruptStore")) as excinfo:
        _load_store(path)

    message = str(excinfo.value).lower()
    assert "matrix" in message, f"the error must name matrix.npy, got {message!r}"
    assert "dtype" in message or "fp16" in message or "float16" in message, (
        f"the error must name the dtype defect, got {message!r}"
    )


def test_load_raises_corrupt_store_when_identity_is_missing(tmp_path):
    # spec(T-021:AC-7)
    path = tmp_path / "store"
    matrix, payload = _valid_raw_store(path, rows=3)
    payload.pop("model")
    _write_raw_store(path, matrix, payload)

    with pytest.raises(_attr("CorruptStore")) as excinfo:
        _load_store(path)

    message = str(excinfo.value).lower()
    assert "model" in message, (
        f"a store with no recorded model identity is unusable — the error must say "
        f"so rather than defaulting silently; got {message!r}"
    )


def test_load_raises_corrupt_store_on_malformed_entries_json(tmp_path):
    # spec(T-021:AC-7)
    # Review M-5: T-024 catches CorruptStore and degrades to 503; an
    # uncaught JSONDecodeError would crash startup instead.
    path = tmp_path / "store"
    matrix, _payload = _valid_raw_store(path, rows=3)
    (path / "entries.json").write_text("{not valid json", encoding="utf-8")

    with pytest.raises(_attr("CorruptStore")) as excinfo:
        _load_store(path)

    assert "entries.json" in str(excinfo.value), (
        f"the error must name the unparseable file, got {excinfo.value!r}"
    )
    assert matrix.dtype == np.float16  # fixture sanity


def test_load_with_matching_identity_succeeds(tmp_path):
    # spec(T-021:AC-7)
    path = tmp_path / "store"
    _valid_raw_store(path, rows=3, dim=4)

    store = _load_store(path, model=FAKE_MODEL, dim=4)

    assert store.model == FAKE_MODEL
    assert store.dim == 4


def test_load_with_a_mismatched_model_raises_store_identity_mismatch(tmp_path):
    # spec(T-021:AC-7)
    # Review I-5: without this, pointing a query at a store built by a
    # different model is a SILENT total miss (every row resolves to None).
    path = tmp_path / "store"
    _valid_raw_store(path, rows=3, dim=4)

    with pytest.raises(_attr("StoreIdentityMismatch")) as excinfo:
        _load_store(path, model="text-embedding-3-small", dim=4)

    message = str(excinfo.value)
    assert FAKE_MODEL in message and "text-embedding-3-small" in message, (
        f"the error must name BOTH the stored and the expected model; got {message!r}"
    )


def test_load_with_a_mismatched_dim_raises_store_identity_mismatch(tmp_path):
    # spec(T-021:AC-7)
    path = tmp_path / "store"
    _valid_raw_store(path, rows=3, dim=4)

    with pytest.raises(_attr("StoreIdentityMismatch")) as excinfo:
        _load_store(path, model=FAKE_MODEL, dim=1536)

    message = str(excinfo.value)
    assert "4" in message and "1536" in message, (
        f"the error must name BOTH the stored and the expected dim; got {message!r}"
    )


# ==========================================================================
# AC-8 — crash-resume checkpointing (plan-review I-10b): a multi-hour,
# ~$30-80, 265K-item run must never pay twice for the same text.
# ==========================================================================


def test_provider_batches_hold_at_most_checkpoint_every_items(tmp_path):
    # spec(T-021:AC-8)
    # Review I-2: "at most", not "exactly" — a smaller FINAL batch is correct
    # and expected (7 items at checkpoint_every=2 ends with a batch of 1).
    pairs = _pairs(7)
    provider = FakeProvider()
    store = _new_store()

    store.embed_corpus(pairs, provider, checkpoint_dir=tmp_path / "ckpt", checkpoint_every=2)

    sizes = [len(batch) for batch in provider.calls]
    assert sizes and all(size <= 2 for size in sizes), (
        f"checkpointing every N newly-embedded items requires provider batches of "
        f"AT MOST N items (a smaller final batch is fine); got sizes {sizes}"
    )
    assert sum(sizes) == 7, f"every novel text must be sent exactly once; got {sizes}"


def test_checkpoint_holds_every_successfully_embedded_chunk_at_crash_time(tmp_path):
    # spec(T-021:AC-8)
    # Batch-size agnostic (review I-2): whatever batching an implementation
    # picks, everything the provider successfully returned before the crash
    # must already be on disk.
    pairs = _pairs(6)
    checkpoint_dir = tmp_path / "ckpt"
    provider = FakeProvider(fail_on_call=3)
    store = _new_store()

    _embed_until_crash(store, pairs, provider, checkpoint_dir, 2)

    embedded = set(provider.texts_returned)
    assert 0 < len(embedded) < 6, (
        f"precondition: the crash must land mid-corpus, got {len(embedded)} of 6"
    )
    done_ids = [chunk_id for chunk_id, text in pairs if text in embedded]
    todo_ids = [chunk_id for chunk_id, text in pairs if text not in embedded]
    checkpoint = _load_store(checkpoint_dir)
    assert checkpoint.matrix.shape[0] == len(done_ids), (
        f"a crash must not discard paid work: {len(done_ids)} chunks were embedded "
        f"before it, but the checkpoint holds {checkpoint.matrix.shape[0]} rows"
    )
    assert checkpoint.rows_for(done_ids) == list(range(len(done_ids)))
    assert checkpoint.rows_for(todo_ids) == [None] * len(todo_ids)


def test_final_partial_batch_is_flushed_to_the_checkpoint(tmp_path):
    # spec(T-021:AC-8)
    # Review I-3: with 265,000 items at checkpoint_every=4096 the remainder is
    # 1,352 — a "checkpoint only when the counter hits the threshold"
    # implementation silently discards up to 4,095 already-paid embeddings.
    pairs = _pairs(5)  # deliberately NOT a multiple of checkpoint_every
    checkpoint_dir = tmp_path / "ckpt"
    store = _new_store()

    store.embed_corpus(pairs, FakeProvider(), checkpoint_dir=checkpoint_dir, checkpoint_every=2)

    reloaded = _load_store(checkpoint_dir)
    assert reloaded.matrix.shape[0] == 5, (
        f"the trailing partial batch must be flushed before embed_corpus returns; "
        f"the checkpoint holds only {reloaded.matrix.shape[0]} of 5 chunks"
    )
    assert reloaded.rows_for(_ids(pairs)) == [0, 1, 2, 3, 4]


def test_resume_after_a_crash_embeds_only_the_missing_chunks(tmp_path):
    # spec(T-021:AC-8)
    pairs = _pairs(6)
    checkpoint_dir = tmp_path / "ckpt"
    first = FakeProvider(fail_on_call=3)
    store = _new_store()
    _embed_until_crash(store, pairs, first, checkpoint_dir, 2)
    already_done = set(first.texts_returned)

    resumed = _load_store(checkpoint_dir)
    provider = FakeProvider()
    resumed.embed_corpus(pairs, provider, checkpoint_dir=checkpoint_dir, checkpoint_every=2)

    expected = [text for _chunk_id, text in pairs if text not in already_done]
    assert provider.texts_seen == expected, (
        f"resuming must re-embed ONLY the chunks the crash never stored — the "
        f"provider call count is the proof; expected {expected}, got "
        f"{provider.texts_seen}"
    )
    assert resumed.rows_for(_ids(pairs)) == [0, 1, 2, 3, 4, 5]


def test_resume_never_re_embeds_an_already_stored_text(tmp_path):
    # spec(T-021:AC-8)
    # Adversarial: nothing that was successfully embedded and checkpointed may
    # be paid for twice. (The batch that died produced no vectors, so retrying
    # exactly those texts is correct — and is not double-embedding.)
    pairs = _pairs(6)
    checkpoint_dir = tmp_path / "ckpt"
    first = FakeProvider(fail_on_call=3)
    store = _new_store()
    _embed_until_crash(store, pairs, first, checkpoint_dir, 2)

    resumed = _load_store(checkpoint_dir)
    second = FakeProvider()
    resumed.embed_corpus(pairs, second, checkpoint_dir=checkpoint_dir, checkpoint_every=2)

    paid_twice = sorted(set(first.texts_returned) & set(second.texts_seen))
    assert paid_twice == [], (
        f"these texts were embedded successfully before the crash and sent again "
        f"after it — a duplicated spend on a ~$30-80 run: {paid_twice}"
    )


def test_resumed_store_equals_the_never_crashed_store(tmp_path):
    # spec(T-021:AC-8)
    pairs = _pairs(6)
    checkpoint_dir = tmp_path / "ckpt"
    crashed = _new_store()
    _embed_until_crash(crashed, pairs, FakeProvider(fail_on_call=3), checkpoint_dir, 2)
    resumed = _load_store(checkpoint_dir)
    resumed.embed_corpus(pairs, FakeProvider(), checkpoint_dir=checkpoint_dir, checkpoint_every=2)

    clean = _new_store()
    clean.embed_corpus(pairs, FakeProvider())

    assert resumed.matrix.shape == clean.matrix.shape == (6, 4)
    assert np.array_equal(resumed.matrix, clean.matrix), (
        "a resumed run must be byte-identical to an uninterrupted one — same rows, "
        "same first-appearance order"
    )
    ids = _ids(pairs)
    assert [resumed.entry_for(i) for i in ids] == [clean.entry_for(i) for i in ids]
