"""Failing tests for T-026 — cross-family faithfulness judge (onrecord/rag/judge.py).

Encodes tickets/T-026.md AC-1..AC-7. These tests are FROZEN after the Test
Agent hands off: do not edit this file to make an implementation pass — fix
the implementation (new file `onrecord/rag/judge.py`, plus the committed
`evalsets/faithfulness_labels.jsonl` example rows) instead.

Run with:
    uv run pytest tests/unit/rag/test_judge.py -v

MODULE-PRESENCE GUARD (why every test starts with `_module()`)
--------------------------------------------------------------
`onrecord.rag.judge` is THIS ticket's target module and does not exist yet.
A module-scope `import onrecord.rag.judge` would blow the whole file up as a
pytest COLLECTION ERROR, polluting other in-flight tickets' regression
baselines (`uv run pytest -q` is run by the orchestrator at any time). So,
mirroring the established idiom in tests/unit/test_api.py,
tests/unit/rag/test_claims.py and tests/unit/rag/test_embeddings.py,
`_require_module_spec(...)` + `pytest.fail(...)` turns "module missing" into
a clean per-test RED failure. `httpx` and `hypothesis` are real dependencies
(httpx>=0.27, hypothesis>=6.115) so they import at module scope with no
guard, and this ticket adds NO dependencies.

`onrecord.rag.claims` (T-027, MERGED) is imported at module scope on purpose:
it is the shared segmentation authority, and this suite asserts the judge's
claim list against `split_claims` OUTPUT rather than against a second
hand-rolled segmentation (LESSONS T-003/T-004: two encodings of one rule
drift silently).

ZERO NETWORK, ZERO KEYS
-----------------------
Every judge interaction goes through an injected `judge_fn` double or
`httpx.MockTransport` (the OpenAI chat-completions wire shape). No test reads
a real key: key-sensitive tests always `monkeypatch.delenv` or
`monkeypatch.setenv` a sentinel first, so neither branch is "environmentally
lucky" (plan-review I-5, T-021 precedent).

Model ids appearing below (`gpt-4o`, `o3-mini`, `claude-3-5-sonnet`,
`gemini-1.5-pro`, `voyage-3`, ...) are FIXTURES for the prefix -> family
derivation rule ONLY. They are not a provisioning recommendation and carry no
claim about current availability — `DEFAULT_JUDGE_MODEL`'s real value is
research-required at provisioning (ticket DoD), and this suite deliberately
pins no literal value for it (see "deliberately not pinned" below).

CONTRACTS PINNED HERE
---------------------
Ticket-derived (tickets/T-026.md Context / ACs): `assert_cross_family`'s
prefix map and its fail-closed behaviour; `build_judge_prompt`'s strict
output protocol; `parse_verdict`'s tolerant extraction that never raises;
`judge_answer`'s per-claim verdicts, failures-as-data (both unparseable
output AND a raising `judge_fn` — plan-review M-8) and faithfulness math;
`validate_judge`'s agreement math + artifact; `run_faithfulness`'s
verdicts-don't-count gate and its `artifacts/rag_eval.jsonl` row shape
(stated identically in tickets/T-025.md — a shared schema, not an import);
the labels loader; and the T-014 secret-hygiene rule.

Test Agent decisions (NOT in the ticket's Context — inventions this suite
freezes; the implementer should read them as such)
--------------------------------------------------------------------------
1.  **Evidence is plain text.** `chunks` (in `judge_answer` /
    `build_judge_prompt`) is a `list[str]` of chunk TEXTS, not `Chunk`
    objects. Justification: the ticket's only concrete evidence schema is the
    labels row's `chunk_texts: [str]`, `validate_judge` feeds exactly that
    into the same prompt builder, and the ticket states this module "consumes
    plain values". Keeping it stringly-typed is also what keeps judge.py free
    of any T-019/T-020/T-023 import. Eval-time callers map `chunk.text`.
2.  **Chunks are numbered `[1]..[m]` in list order in the prompt**, 1-based
    (mirrors T-023's `build_prompt`, plan-review I-7) — that numbering is
    what `evidence_chunk: int` refers to. `evidence_chunk` is passed through
    verbatim; range validation is deliberately NOT pinned (see below).
3.  **`parse_verdict` normalizes case and surrounding whitespace** on the
    verdict token (`" Supported "` -> `"supported"`) but is otherwise a
    STRICT enum match: `"partially supported"` is `"unparseable"`, never
    `"supported"`. Rationale: normalization is free robustness with no
    false-positive risk, whereas substring matching invents support that the
    judge never asserted (LESSONS 2026-08-12 corollary — prefer the pin whose
    failure mode is conservative). `evidence_chunk` is tolerant in the other
    direction: a malformed secondary field (`"2"`, `true`, absent) becomes
    `None` and never destroys a valid verdict. A JSON `true` is not a chunk
    index even though `isinstance(True, int)` holds in Python.
4.  **`load_labels(path, include_examples=False) -> list[dict]`** is the
    loader's name and shape (mirrors T-025's `load_qa`/`load_unanswerable`).
    Rows are returned VERBATIM (extra keys pass through — hand-labelled data
    accretes annotation columns), every line is schema-validated INCLUDING
    example rows (the committed example rows document the schema; a broken
    one must fail loudly), errors are `ValueError`s naming the 1-based line
    number and the offending field, and `"example-"` is a PREFIX test.
5.  **`validate_judge` and `run_faithfulness` both accept an optional
    `validation_path`** defaulting to the ticket's literal
    `"artifacts/judge_validation.json"` (the ticket gives the parameter for
    `run_faithfulness` only; symmetry is required to test the writer without
    a chdir, and the default is pinned via a chdir test).
6.  **`disagreements` entries are exactly
    `{"label_id", "human_verdict", "judge_verdict"}`**, in label order. The
    ticket requires the key but leaves its shape open; an unpinned list shape
    is untestable.
7.  **A raising `judge_fn` during `validate_judge` is failures-as-data too** —
    recorded as verdict `"error"` and counted as a disagreement, never
    propagated. A validation run over the owner's ~10 hand labels costs money
    and human time; one transport blip must not discard the other 9 results.
8.  **Empty `labels` raises `ValueError`.** A "validation" over zero rows must
    never report an agreement number, because the shipped labels file is
    example-only: `load_labels()` returns `[]` until the owner lands the real
    hand labels, and a silent `0.0`/`passed: False` would look like a judge
    problem instead of a missing-data problem.
9.  **`run_faithfulness`'s `answers` rows are
    `{"qa_id", "question", "answer_text", "chunk_texts"}`** — the labels-row
    field names minus the hand-label columns, so one vocabulary covers both
    files; `per_answer` entries are
    `{"qa_id", "faithfulness", "supported", "total"}`; `mean_faithfulness` is
    the MEAN OF PER-ANSWER faithfulness (macro), not the micro-average
    `total_supported / total_claims` — the AC-5 fixture is built so the two
    differ (0.625 vs 0.6667). `run_faithfulness` RETURNS the row it appended.
10. **`corpus_version` is read through `ONRECORD_INDEX`** (falling back to
    `artifacts/index`) via T-018's `read_manifest`, with `"unversioned"` on
    any failure — verbatim the mechanism already frozen for
    `onrecord.eval.run._corpus_version`, so the two artifact writers agree.
11. **`resolved_judge_model() -> str`** exposes this module's own judge id
    (`ONRECORD_JUDGE_MODEL` env, else `DEFAULT_JUDGE_MODEL`), mirroring
    T-023's `resolved_generator_model()`. The ticket says the env is read "by
    `default_judge()` only"; a single internal resolver that `default_judge()`
    itself consumes honours that intent (one source of truth inside this
    module) while giving `main()` an honest way to pass `judge_model` without
    a second env read.
12. **`main()` has TWO lazy seams**, `_resolve_generator_model()` and
    `_resolve_answers()`, both monkeypatched here — the direct precedent is
    T-025's `_resolve_answer_fn` (plan-review I-9): T-023 and T-025 are
    same-wave and unmerged during implementation, so the real imports must
    live INSIDE the function bodies. `test_importing_judge_does_not_import_the
    _answer_pipeline` pins that laziness in a subprocess so it survives the
    wave-9 merge.
13. **`judge_answer` catches `Exception`, not `BaseException`** — a
    `KeyboardInterrupt` during a long paid eval run must still stop it.

DELIBERATELY NOT PINNED (documented gaps, not oversights)
---------------------------------------------------------
* `DEFAULT_JUDGE_MODEL`'s literal value (research-required at provisioning —
  ticket DoD). What IS pinned: it is a non-empty str whose family is neither
  unknown nor anthropic, i.e. `assert_cross_family(<claude id>,
  DEFAULT_JUDGE_MODEL)` must not raise. A hard-coded literal here would be
  exactly the "model id from memory" failure the ticket forbids.
* Case sensitivity of the family prefix map (`"GPT-4o"`). Either reading is
  fail-safe: case-sensitive yields "unknown" -> refuse.
* `evidence_chunk` range validation against `len(chunks)` — `parse_verdict`
  cannot see the chunk list, and the ticket asks for no such check. All
  fixtures use in-range indices so neither pass-through nor nulling is
  constrained.
* Whether `judge_answer` strips `[n]` markers from a claim before prompting.
  Prompt-content assertions therefore use marker-free sentence bodies, which
  are substrings under both readings. The `claim` FIELD, by contrast, is
  pinned verbatim to `split_claims` output — that is the shared-count
  contract with T-023's grounding.
* Retry/backoff schedule and timeouts of `default_judge()` (T-021 precedent).
* Whether `run_faithfulness` re-checks `assert_cross_family` itself: every
  gate fixture here uses a genuinely cross-family pair, so either ordering
  passes.
* Schema validation of `answers` rows (unlike labels rows, they are produced
  by the pipeline, not hand-authored).

SECRET HYGIENE (LESSONS.md T-014, 2026-08-11)
----------------------------------------------
The key must never appear in ANY log record. The AC-7 tests capture at the
ROOT logger with library loggers left free to propagate at INFO, and each one
carries a liveness precondition (a canary record proving the capture is live)
so it cannot pass vacuously — plus a leaky-transport case proving the
sentinel is genuinely REACHABLE from the exception the adapter must handle,
i.e. that it WOULD surface absent redaction (the T-021 standard).
"""

import contextlib
import importlib.util
import json
import logging
import re
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

import httpx
import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from onrecord.rag.claims import split_claims

SENTINEL_KEY = "SUPERSECRET-sentinel-openai-judgekey-zzz9999"
CANARY = "LOGGING-CAPTURE-CANARY"

# Family fixtures (see module docstring — derivation fixtures, not choices).
CLAUDE_MODEL = "claude-3-5-sonnet"
GPT_MODEL = "gpt-4o"
REPO_ROOT = Path(__file__).resolve().parents[3]
LABELS_FILE = REPO_ROOT / "evalsets" / "faithfulness_labels.jsonl"

VERDICT_ENUM = ("supported", "unsupported", "contradicted")
PARSED_KEYS = {"verdict", "evidence_chunk"}


# --------------------------------------------------------------------------
# Guards / module access
# --------------------------------------------------------------------------


def _require_module_spec(name: str, fail_message: str):
    """Return the module spec for `name`, or fail cleanly via pytest.fail.

    `importlib.util.find_spec` raises ModuleNotFoundError (rather than
    returning None) when a parent package in a dotted name is itself missing,
    so both "not found" cases are normalized into one clean assertion-style
    failure, never an uncaught exception or a pytest collection error.
    """
    try:
        spec = importlib.util.find_spec(name)
    except ModuleNotFoundError:
        spec = None
    if spec is None:
        pytest.fail(fail_message)
    return spec


def _module():
    _require_module_spec(
        "onrecord.rag.judge",
        "onrecord.rag.judge missing (T-026 target module — expected RED until "
        "the Implementation Agent lands it)",
    )
    import onrecord.rag.judge as judge

    return judge


def _attr(name: str):
    mod = _module()
    if not hasattr(mod, name):
        pytest.fail(f"onrecord.rag.judge.{name} missing")
    return getattr(mod, name)


# --------------------------------------------------------------------------
# Deterministic doubles for the judge boundary
# --------------------------------------------------------------------------


class JudgeTransportBoom(RuntimeError):
    """Simulated provider failure surfacing out of `judge_fn` (5xx, reset)."""


def _verdict_json(verdict: str, evidence_chunk=None) -> str:
    """A protocol-clean raw judge response."""
    return json.dumps({"verdict": verdict, "evidence_chunk": evidence_chunk})


class ClaimKeyedJudge:
    """A `judge_fn` scripted per claim, matched by a unique claim substring.

    `script` maps a substring that appears in exactly one claim's prompt to
    either a raw response string or an exception INSTANCE to raise.

    A fixture miss is recorded in `.misses` and answered with a neutral
    garbage string rather than raised: `judge_answer` catches exceptions from
    `judge_fn` by contract, so a raised AssertionError would be silently
    converted into an "error" verdict and the test would pass for the wrong
    reason. Every test using this double asserts `.misses == []`.
    """

    def __init__(self, script: dict):
        self.script = script
        self.prompts: list[str] = []
        self.misses: list[str] = []

    def __call__(self, prompt: str) -> str:
        self.prompts.append(prompt)
        matched = [key for key in self.script if key in prompt]
        if len(matched) != 1:
            self.misses.append(f"{len(matched)} script keys matched this prompt: {prompt!r}")
            return "FIXTURE-MISS"
        response = self.script[matched[0]]
        if isinstance(response, BaseException):
            raise response
        return response

    @property
    def call_count(self) -> int:
        return len(self.prompts)


class ConstantJudge:
    """A `judge_fn` returning one fixed raw response for every prompt."""

    def __init__(self, response: str):
        self.response = response
        self.prompts: list[str] = []

    def __call__(self, prompt: str) -> str:
        self.prompts.append(prompt)
        return self.response

    @property
    def call_count(self) -> int:
        return len(self.prompts)


class NeverCalledJudge:
    """A `judge_fn` that records calls; used for call-count-zero assertions."""

    def __init__(self):
        self.prompts: list[str] = []

    def __call__(self, prompt: str) -> str:
        self.prompts.append(prompt)
        return _verdict_json("supported", 1)

    @property
    def call_count(self) -> int:
        return len(self.prompts)


# --------------------------------------------------------------------------
# Shared fixtures / helpers
# --------------------------------------------------------------------------

QUESTION = "Did Dominion request additional capacity?"
CHUNKS = [
    "Dominion Energy Inc. filed a request for 240 MW of new capacity.",
    "Regulators asked the utility for additional load data.",
    "The hearing adjourned with no ruling on the record.",
]

# Five claims. `Inc.` and the trailing `[n]` markers are load-bearing: a naive
# `answer_text.split(". ")` yields SIX pieces here, so any implementation that
# re-rolls segmentation instead of importing `split_claims` fails loudly
# (T-027 is the single segmentation authority — locked).
ANSWER_FIVE_CLAIMS = (
    "Dominion Energy Inc. requested 240 MW. [1] "
    "Regulators requested more data. [2] "
    "The hearing concluded without a ruling. [3] "
    "Load growth reached 12 percent. [1] "
    "The commission scheduled a follow-up. [2]"
)
FIVE_CLAIM_BODIES = (
    "Dominion Energy Inc. requested 240 MW.",
    "Regulators requested more data.",
    "The hearing concluded without a ruling.",
    "Load growth reached 12 percent.",
    "The commission scheduled a follow-up.",
)


def _label_row(i: int, human_verdict: str, label_id: str | None = None) -> dict:
    """One schema-valid hand-label row (see tickets/T-026.md Context)."""
    return {
        "label_id": label_id if label_id is not None else f"L-{i:02d}",
        "question": f"Question {i:02d}?",
        "answer_text": f"Claim {i:02d} states a fact.",
        "chunk_texts": [f"Evidence {i:02d} alpha.", f"Evidence {i:02d} beta."],
        "claim": f"Claim {i:02d} states a fact.",
        "human_verdict": human_verdict,
    }


# 10 labels: 5 supported, 3 unsupported, 2 contradicted (AC-4's fixture set).
TEN_HUMAN_VERDICTS = [
    "supported",
    "supported",
    "unsupported",
    "supported",
    "contradicted",
    "supported",
    "unsupported",
    "supported",
    "contradicted",
    "unsupported",
]


def _ten_labels() -> list[dict]:
    return [_label_row(i, verdict) for i, verdict in enumerate(TEN_HUMAN_VERDICTS)]


def _agreeing_script(labels: list[dict], disagree_on: set[int]) -> dict:
    """Judge script agreeing with every label except the given indices."""
    flipped = {"supported": "unsupported", "unsupported": "supported", "contradicted": "supported"}
    script = {}
    for i, label in enumerate(labels):
        verdict = label["human_verdict"]
        if i in disagree_on:
            verdict = flipped[verdict]
        script[label["claim"]] = _verdict_json(verdict, 1)
    return script


def _write_labels_file(path: Path, rows: list) -> Path:
    """Write JSONL rows (dicts are dumped; raw strings are written verbatim)."""
    lines = [row if isinstance(row, str) else json.dumps(row) for row in rows]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _write_validation_artifact(
    path: Path,
    judge_model: str = GPT_MODEL,
    generator_model: str = CLAUDE_MODEL,
    passed: bool = True,
    agreement: float = 0.9,
    n: int = 10,
    drop_keys: tuple = (),
) -> Path:
    payload = {
        "timestamp": "2026-08-12T12:00:00+00:00",
        "judge_model": judge_model,
        "generator_model": generator_model,
        "agreement": agreement,
        "passed": passed,
        "n": n,
    }
    for key in drop_keys:
        payload.pop(key, None)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload), encoding="utf-8")
    return path


# Two answers, hand-computed: 1/2 and 3/4 -> macro mean 0.625 (the micro
# average would be 4/6 = 0.6667, which is why these two shapes were chosen).
ANSWERS_TWO = [
    {
        "qa_id": "qa-1",
        "question": "What did the utility file?",
        "answer_text": "Alpha claim one holds. [1] Alpha claim two holds. [2]",
        "chunk_texts": ["Alpha evidence one.", "Alpha evidence two."],
    },
    {
        "qa_id": "qa-2",
        "question": "What did regulators decide?",
        "answer_text": (
            "Beta claim one holds. [1] Beta claim two holds. [2] "
            "Beta claim three holds. [3] Beta claim four holds. [1]"
        ),
        "chunk_texts": ["Beta evidence one.", "Beta evidence two.", "Beta evidence three."],
    },
]

ANSWERS_TWO_SCRIPT = {
    "Alpha claim one": _verdict_json("supported", 1),
    "Alpha claim two": _verdict_json("unsupported", None),
    "Beta claim one": _verdict_json("supported", 1),
    "Beta claim two": _verdict_json("supported", 2),
    "Beta claim three": _verdict_json("supported", 3),
    "Beta claim four": _verdict_json("contradicted", 1),
}


# --------------------------------------------------------------------------
# OpenAI chat-completions wire doubles (AC-7)
# --------------------------------------------------------------------------


def _chat_handler(requests: list, content: str = "{}", statuses: list | None = None):
    """MockTransport handler recording requests, replying chat-completion shaped."""
    queue = list(statuses or [])

    def handler(request: httpx.Request) -> httpx.Response:
        requests.append(request)
        status = queue.pop(0) if queue else 200
        if status != 200:
            return httpx.Response(status, json={"error": {"message": "upstream boom"}})
        return httpx.Response(
            200,
            json={
                "id": "chatcmpl-test",
                "object": "chat.completion",
                "choices": [
                    {
                        "index": 0,
                        "message": {"role": "assistant", "content": content},
                        "finish_reason": "stop",
                    }
                ],
                "usage": {"prompt_tokens": 10, "completion_tokens": 5, "total_tokens": 15},
            },
        )

    return httpx.MockTransport(handler)


def _leaky_transport(recorder: list) -> httpx.MockTransport:
    """A transport whose error TEXT carries the Authorization header.

    The liveness half of the secret-sentinel tests (T-021 review I-7): it
    proves the secret is genuinely reachable from the exception the adapter
    has to handle, so "no record contains the key" cannot pass vacuously.
    """

    def handler(request: httpx.Request) -> httpx.Response:
        message = f"connection reset mid-request: headers={dict(request.headers)}"
        recorder.append(message)
        raise httpx.ConnectError(message)

    return httpx.MockTransport(handler)


@contextlib.contextmanager
def _library_loggers_unmuted():
    """Reproduce the repo's own process-wide INFO logging (LESSONS T-014).

    onrecord's entrypoints call `logging.basicConfig(level=INFO)`, and httpx's
    own logger is NOTSET by default so it inherits root. The baseline is
    restored afterwards — including root's handler list — so a `basicConfig`
    that is NOT a no-op cannot leak a StreamHandler into the rest of the
    session. An implementation that silences/redacts library loggers AROUND
    its own keyed request still wins: that happens inside the call.
    """
    root = logging.getLogger()
    previous_root_level = root.level
    previous_handlers = root.handlers[:]
    library = [logging.getLogger(name) for name in ("httpx", "httpcore", "openai")]
    previous = [(lg, lg.level, lg.propagate) for lg in library]
    logging.basicConfig(level=logging.INFO)
    root.setLevel(logging.INFO)
    for lg in library:
        lg.setLevel(logging.NOTSET)
        lg.propagate = True
    try:
        yield
    finally:
        root.setLevel(previous_root_level)
        root.handlers[:] = previous_handlers
        for lg, level, propagate in previous:
            lg.setLevel(level)
            lg.propagate = propagate


def _assert_capture_is_live(caplog):
    """Precondition for every sentinel test: the root capture really works."""
    logging.getLogger("onrecord.tests.canary").info("capture liveness canary %s", CANARY)
    assert any(CANARY in record.getMessage() for record in caplog.records), (
        "precondition failed: the root-level log capture is not live, so a "
        "'no record contains the key' assertion below would pass vacuously"
    )


def _leaking_records(caplog, secret: str) -> list:
    return [(r.name, r.getMessage()) for r in caplog.records if secret in r.getMessage()]


def _error_text(excinfo, path) -> str:
    """The error message with the labels-file path masked out.

    Loader errors legitimately name the file, and that path lives under
    pytest's tmp dir (`.../pytest-123/test_x0/labels.jsonl`) — so a raw
    `"3" in str(excinfo.value)` could pass on a digit from the PATH rather
    than on the line number under test. Masking the path first is what keeps
    the line-number assertions non-vacuous.
    """
    return str(excinfo.value).replace(str(path), "<labels-path>")


def _names_line(message: str, lineno: int) -> bool:
    """True if `message` names `lineno` as a standalone number (not inside
    a longer digit run such as the fixtures' own `L-01` / `Question 01?`)."""
    return re.search(rf"(?<!\d){lineno}(?!\d)", message) is not None


# ==========================================================================
# Public API surface — kept first and cheap so every other AC fails with a
# NAMED missing symbol instead of an opaque AttributeError.
# ==========================================================================


def test_module_exposes_documented_public_api():
    # spec(T-026:AC-1)
    mod = _module()
    expected = [
        "CrossFamilyViolation",
        "JudgeNotValidated",
        "JudgeNotConfigured",
        "DEFAULT_JUDGE_MODEL",
        "assert_cross_family",
        "build_judge_prompt",
        "parse_verdict",
        "judge_answer",
        "load_labels",
        "validate_judge",
        "run_faithfulness",
        "default_judge",
        "resolved_judge_model",
        "_resolve_generator_model",
        "_resolve_answers",
        "main",
    ]
    missing = [name for name in expected if not hasattr(mod, name)]
    assert missing == [], f"onrecord.rag.judge is missing public API symbols: {missing}"


def test_the_three_typed_errors_are_exception_classes():
    # spec(T-026:AC-1)
    for name in ("CrossFamilyViolation", "JudgeNotValidated", "JudgeNotConfigured"):
        error = _attr(name)
        assert isinstance(error, type) and issubclass(error, Exception), (
            f"{name} must be an Exception subclass so callers can catch it by type; got {error!r}"
        )


# ==========================================================================
# AC-1 — assert_cross_family: prefix-map families, fail CLOSED on same-family
# and on any unknown id.
# ==========================================================================


@pytest.mark.parametrize(
    ("generator_model", "judge_model"),
    [
        ("claude-3-5-sonnet", "gpt-4o"),  # the standing decision's real pairing
        ("claude-opus-4-1", "o3-mini"),  # `o*` is openai too
        ("claude-3-5-haiku-latest", "gemini-1.5-pro"),
        ("gpt-4o", "claude-3-5-sonnet"),  # order does not matter
        ("gemini-1.5-pro", "voyage-3"),
    ],
)
def test_cross_family_pairs_pass(generator_model, judge_model):
    # spec(T-026:AC-1)
    assert _attr("assert_cross_family")(generator_model, judge_model) is None, (
        "assert_cross_family is a guard: it returns None on success and raises otherwise"
    )


@pytest.mark.parametrize(
    ("generator_model", "judge_model"),
    [
        ("claude-3-5-sonnet", "claude-3-5-haiku"),  # AC-1's pinned same-family case
        ("gpt-4o", "gpt-4o-mini"),
        ("gpt-4o", "o3-mini"),  # `gpt*` and `o*` are the SAME family (openai)
        ("o3-mini", "o4-mini"),
        ("gemini-1.5-pro", "gemini-2.0-flash"),
        ("voyage-3", "voyage-3-lite"),
        ("claude-3-5-sonnet", "claude-3-5-sonnet"),  # literally the same id
    ],
)
def test_same_family_pairs_raise(generator_model, judge_model):
    # spec(T-026:AC-1)
    # The `gpt-4o` / `o3-mini` case is the one a per-id (rather than
    # per-FAMILY) check silently waves through — two OpenAI models sharing a
    # training lineage grading each other is exactly what spec Sec 5's
    # cross-family requirement exists to prevent.
    with pytest.raises(_attr("CrossFamilyViolation")):
        _attr("assert_cross_family")(generator_model, judge_model)


@pytest.mark.parametrize(
    ("generator_model", "judge_model"),
    [
        ("llama-3-70b", "gpt-4o"),  # unknown generator
        ("claude-3-5-sonnet", "mistral-large"),  # unknown judge
        ("llama-3-70b", "mistral-large"),  # both unknown
        ("", "gpt-4o"),  # empty id
        ("claude-3-5-sonnet", ""),
        ("   ", "gpt-4o"),  # whitespace-only id
    ],
)
def test_unknown_family_fails_closed(generator_model, judge_model):
    # spec(T-026:AC-1)
    # FAIL CLOSED (ticket Context): an unverifiable pairing never silently
    # counts. Two unknown ids are NOT "different families" — they are two
    # unknowns, and a judge whose provenance cannot be established must not
    # be allowed to certify the generator it may itself be.
    with pytest.raises(_attr("CrossFamilyViolation")):
        _attr("assert_cross_family")(generator_model, judge_model)


def test_cross_family_violation_message_names_both_models():
    # spec(T-026:AC-1)
    with pytest.raises(_attr("CrossFamilyViolation")) as excinfo:
        _attr("assert_cross_family")("claude-3-5-sonnet", "claude-3-5-haiku")

    message = str(excinfo.value)
    assert "claude-3-5-sonnet" in message and "claude-3-5-haiku" in message, (
        f"the error must name BOTH model ids so the operator can see which pairing "
        f"was refused; got {message!r}"
    )


def test_unknown_family_message_is_actionable():
    # spec(T-026:AC-1)
    with pytest.raises(_attr("CrossFamilyViolation")) as excinfo:
        _attr("assert_cross_family")("llama-3-70b", "gpt-4o")

    assert "llama-3-70b" in str(excinfo.value), (
        f"the refused (unknown-family) id must appear in the message; got {excinfo.value!r}"
    )


# ==========================================================================
# AC-2 — parse_verdict: tolerant extraction, strict enum, NEVER raises.
# ==========================================================================


@pytest.mark.parametrize(
    ("raw", "expected"),
    [
        # Clean protocol output, all three enum members.
        ('{"verdict": "supported", "evidence_chunk": 2}', {"verdict": "supported", "evidence": 2}),
        (
            '{"verdict": "unsupported", "evidence_chunk": null}',
            {"verdict": "unsupported", "evidence": None},
        ),
        (
            '{"verdict": "contradicted", "evidence_chunk": 1}',
            {"verdict": "contradicted", "evidence": 1},
        ),
        # JSON embedded in prose (the dominant real judge output).
        (
            'Sure! Here is my analysis:\n{"verdict": "supported", "evidence_chunk": 3}\nHope '
            "that helps.",
            {"verdict": "supported", "evidence": 3},
        ),
        # Fenced code block.
        (
            '```json\n{"verdict": "unsupported", "evidence_chunk": null}\n```',
            {"verdict": "unsupported", "evidence": None},
        ),
        # FIRST JSON object wins.
        (
            '{"verdict": "supported", "evidence_chunk": 1} then {"verdict": "unsupported"}',
            {"verdict": "supported", "evidence": 1},
        ),
        # A nested object inside the payload — kills a naive `\\{[^}]*\\}` scan.
        (
            '{"verdict": "supported", "evidence_chunk": 2, "meta": {"confidence": "high"}}',
            {"verdict": "supported", "evidence": 2},
        ),
        # Extra keys are tolerated (judges love to explain themselves).
        (
            '{"reasoning": "chunk 1 says so", "verdict": "supported", "evidence_chunk": 1}',
            {"verdict": "supported", "evidence": 1},
        ),
        # Array-wrapped single object (still "the first JSON object in the text").
        (
            '[{"verdict": "contradicted", "evidence_chunk": 2}]',
            {"verdict": "contradicted", "evidence": 2},
        ),
        # Case / whitespace normalization on the verdict token only.
        (
            '{"verdict": " Supported ", "evidence_chunk": 1}',
            {"verdict": "supported", "evidence": 1},
        ),
        (
            '{"verdict": "UNSUPPORTED", "evidence_chunk": null}',
            {"verdict": "unsupported", "evidence": None},
        ),
        # Missing / malformed secondary field never destroys a valid verdict.
        ('{"verdict": "supported"}', {"verdict": "supported", "evidence": None}),
        (
            '{"verdict": "supported", "evidence_chunk": "2"}',
            {"verdict": "supported", "evidence": None},
        ),
        (
            '{"verdict": "supported", "evidence_chunk": true}',
            {"verdict": "supported", "evidence": None},
        ),
        (
            '{"verdict": "supported", "evidence_chunk": [1, 2]}',
            {"verdict": "supported", "evidence": None},
        ),
    ],
)
def test_parse_verdict_maps_wellformed_outputs_to_pinned_results(raw, expected):
    # spec(T-026:AC-2)
    result = _attr("parse_verdict")(raw)

    assert result == {"verdict": expected["verdict"], "evidence_chunk": expected["evidence"]}


@pytest.mark.parametrize(
    "raw",
    [
        "",  # empty
        "   \n\t ",  # whitespace only
        "I cannot answer that.",  # prose with no JSON at all
        '{"verdict": "supported", "evidence_chunk":',  # truncated mid-object
        '{"verdict": "suppo',  # truncated mid-string
        "{}",  # object with no verdict
        '{"evidence_chunk": 1}',  # verdict key absent
        '{"verdict": null}',  # verdict not a string
        '{"verdict": 3}',
        '{"verdict": "maybe"}',  # invalid enum
        '{"verdict": "partially supported", "evidence_chunk": 1}',  # substring trap
        '{"verdict": "not supported", "evidence_chunk": 1}',  # substring trap
        '{"verdict": ["supported"]}',
        "verdict: supported",  # protocol ignored entirely
        "```json\n```",
        "\x00\x01\x02 binary-ish garbage �",
        "🙂" * 500,  # long unicode
    ],
)
def test_parse_verdict_maps_malformed_output_to_unparseable(raw):
    # spec(T-026:AC-2)
    # Judge flakiness is DATA, not a crash (ticket Context, mirroring the
    # LESSONS failures-as-data rule). The two substring traps are the
    # dangerous direction: "partially supported" / "not supported" contain
    # the literal token `supported`, and an implementation that matches by
    # substring would invent support the judge never asserted.
    result = _attr("parse_verdict")(raw)

    assert result == {"verdict": "unparseable", "evidence_chunk": None}


def test_parse_verdict_returns_exactly_the_two_pinned_keys():
    # spec(T-026:AC-2)
    result = _attr("parse_verdict")('{"verdict": "supported", "evidence_chunk": 1, "why": "x"}')

    assert set(result) == PARSED_KEYS, (
        f"parse_verdict returns exactly {{'verdict', 'evidence_chunk'}} — extra keys leak the "
        f"judge's free-form output into the artifact row; got {sorted(result)}"
    )


_PROSE_ALPHABET = "abcdefghijklmnopqrstuvwxyz ABCXYZ.,:\n"


@st.composite
def _judge_outputs(draw):
    """Protocol-clean JSON wrapped in brace-free prose (the real shape)."""
    verdict = draw(st.sampled_from(VERDICT_ENUM))
    evidence = draw(st.one_of(st.none(), st.integers(min_value=1, max_value=10)))
    prefix = draw(st.text(alphabet=_PROSE_ALPHABET, max_size=40))
    suffix = draw(st.text(alphabet=_PROSE_ALPHABET, max_size=40))
    body = json.dumps({"verdict": verdict, "evidence_chunk": evidence})
    return f"{prefix}{body}{suffix}", verdict, evidence


@given(data=_judge_outputs())
@settings(max_examples=200, deadline=None)
def test_property_wellformed_verdict_survives_arbitrary_surrounding_prose(data):
    # spec(T-026:AC-2)
    raw, verdict, evidence = data

    assert _attr("parse_verdict")(raw) == {"verdict": verdict, "evidence_chunk": evidence}


@given(raw=st.text(max_size=200))
@settings(max_examples=200, deadline=None)
def test_property_parse_verdict_never_raises_and_always_returns_the_pinned_shape(raw):
    # spec(T-026:AC-2)
    # "never raises" is the whole point: `judge_answer` calls this on whatever
    # a hosted model emitted, mid-run, with prior verdicts already paid for.
    result = _attr("parse_verdict")(raw)

    assert set(result) == PARSED_KEYS
    assert result["verdict"] in (*VERDICT_ENUM, "unparseable")
    assert result["evidence_chunk"] is None or (
        isinstance(result["evidence_chunk"], int) and not isinstance(result["evidence_chunk"], bool)
    )


# ==========================================================================
# AC-3 — build_judge_prompt (the input half of each per-claim call) +
# judge_answer's math, segmentation authority, and failures-as-data.
# ==========================================================================


def test_build_judge_prompt_carries_question_claim_and_every_chunk():
    # spec(T-026:AC-3)
    claim = "Dominion requested 240 MW of new capacity."

    prompt = _attr("build_judge_prompt")(QUESTION, claim, CHUNKS)

    assert isinstance(prompt, str) and prompt.strip()
    assert QUESTION in prompt
    assert claim in prompt
    for chunk in CHUNKS:
        assert chunk in prompt, f"every chunk text is evidence and must appear verbatim: {chunk!r}"


def test_build_judge_prompt_numbers_chunks_one_based_in_list_order():
    # spec(T-026:AC-3)
    # `evidence_chunk: int` is meaningless unless the prompt establishes the
    # numbering (mirrors T-023's build_prompt, plan-review I-7).
    prompt = _attr("build_judge_prompt")(QUESTION, "A claim.", CHUNKS)

    positions = [prompt.index(f"[{i}]") for i in (1, 2, 3)]
    assert positions == sorted(positions), (
        f"chunk markers [1]..[m] must appear in chunk order; got positions {positions}"
    )
    assert "[4]" not in prompt, "only the chunks actually supplied may be numbered"
    for i, chunk in enumerate(CHUNKS, start=1):
        assert prompt.index(f"[{i}]") < prompt.index(chunk), (
            f"chunk {i}'s marker must introduce its text, not trail it"
        )


def test_build_judge_prompt_states_the_strict_output_protocol():
    # spec(T-026:AC-3)
    prompt = _attr("build_judge_prompt")(QUESTION, "A claim.", CHUNKS)

    for token in ("verdict", "evidence_chunk", *VERDICT_ENUM):
        assert token in prompt, (
            f"the STRICT output protocol must name {token!r} in the prompt — parse_verdict's "
            f"enum is only enforceable if the judge was told it"
        )
    assert "JSON" in prompt or "json" in prompt


def test_build_judge_prompt_with_no_chunks_still_builds_a_string():
    # spec(T-026:AC-3)
    prompt = _attr("build_judge_prompt")(QUESTION, "A claim.", [])

    assert isinstance(prompt, str) and "A claim." in prompt
    assert "[1]" not in prompt


def test_judge_answer_segments_claims_through_the_shared_split_claims_authority():
    # spec(T-026:AC-3)
    # T-027 is the SINGLE segmentation authority (locked): judged claims and
    # T-023's grounding block must count identically. Asserted against
    # split_claims' real output AND against a hand-written expectation, so
    # neither a re-rolled splitter nor a drifted import passes.
    judge = ConstantJudge(_verdict_json("supported", 1))

    result = _attr("judge_answer")(QUESTION, ANSWER_FIVE_CLAIMS, CHUNKS, judge)

    claims = [entry["claim"] for entry in result["claims"]]
    assert claims == split_claims(ANSWER_FIVE_CLAIMS)
    assert claims == [
        "Dominion Energy Inc. requested 240 MW. [1]",
        "Regulators requested more data. [2]",
        "The hearing concluded without a ruling. [3]",
        "Load growth reached 12 percent. [1]",
        "The commission scheduled a follow-up. [2]",
    ], (
        "5 claims, not 6: `Inc.` is a fixed abbreviation and `[n]` markers stay attached to "
        "the sentence they follow — a naive split on '. ' gets this wrong"
    )
    assert result["total"] == 5


def test_judge_answer_ac3_scripted_mix_of_verdicts_errors_and_garbage():
    # spec(T-026:AC-3)
    # AC-3 verbatim: 2 supported + 1 contradicted + 1 unparseable + 1 that
    # RAISES -> supported=2, total=5, faithfulness=0.4; the raising claim is
    # recorded as verdict "error" and all four earlier verdicts are retained
    # (plan-review M-8 — a transport blip on claim 5 must never discard the
    # four already-paid verdicts).
    judge = ClaimKeyedJudge(
        {
            FIVE_CLAIM_BODIES[0]: _verdict_json("supported", 1),
            FIVE_CLAIM_BODIES[1]: _verdict_json("supported", 2),
            FIVE_CLAIM_BODIES[2]: _verdict_json("contradicted", 3),
            FIVE_CLAIM_BODIES[3]: "the judge rambled and emitted no JSON at all",
            FIVE_CLAIM_BODIES[4]: JudgeTransportBoom("provider 5xx after retries"),
        }
    )

    result = _attr("judge_answer")(QUESTION, ANSWER_FIVE_CLAIMS, CHUNKS, judge)

    assert judge.misses == [], judge.misses
    assert result["claims"] == [
        {
            "claim": "Dominion Energy Inc. requested 240 MW. [1]",
            "verdict": "supported",
            "evidence_chunk": 1,
        },
        {
            "claim": "Regulators requested more data. [2]",
            "verdict": "supported",
            "evidence_chunk": 2,
        },
        {
            "claim": "The hearing concluded without a ruling. [3]",
            "verdict": "contradicted",
            "evidence_chunk": 3,
        },
        {
            "claim": "Load growth reached 12 percent. [1]",
            "verdict": "unparseable",
            "evidence_chunk": None,
        },
        {
            "claim": "The commission scheduled a follow-up. [2]",
            "verdict": "error",
            "evidence_chunk": None,
        },
    ]
    assert result["supported"] == 2
    assert result["total"] == 5
    assert result["faithfulness"] == pytest.approx(0.4)
    assert judge.call_count == 5, "one call per claim, claim-level per spec Sec 5"


def test_judge_answer_returns_exactly_the_pinned_key_sets():
    # spec(T-026:AC-3)
    judge = ConstantJudge(_verdict_json("supported", 1))

    result = _attr("judge_answer")(QUESTION, "One claim only.", CHUNKS, judge)

    assert set(result) == {"claims", "supported", "total", "faithfulness"}, (
        f"top-level keys are pinned exactly; got {sorted(result)}"
    )
    assert set(result["claims"][0]) == {"claim", "verdict", "evidence_chunk"}, (
        f"per-claim keys are pinned exactly; got {sorted(result['claims'][0])}"
    )
    assert isinstance(result["faithfulness"], float)
    assert isinstance(result["supported"], int) and isinstance(result["total"], int)


@pytest.mark.parametrize(
    ("verdicts", "expected_supported", "expected_faithfulness"),
    [
        (["supported", "supported", "supported", "unsupported"], 3, 0.75),
        (["supported", "unsupported", "contradicted"], 1, 1 / 3),
        (["unsupported", "contradicted"], 0, 0.0),
        (["supported", "supported"], 2, 1.0),
    ],
)
def test_judge_answer_faithfulness_is_supported_over_total(
    verdicts, expected_supported, expected_faithfulness
):
    # spec(T-026:AC-3)
    bodies = [f"Claim number {i} is asserted." for i in range(len(verdicts))]
    answer_text = " ".join(f"{body} [1]" for body in bodies)
    judge = ClaimKeyedJudge(
        {body: _verdict_json(verdict, 1) for body, verdict in zip(bodies, verdicts, strict=True)}
    )

    result = _attr("judge_answer")(QUESTION, answer_text, CHUNKS, judge)

    assert judge.misses == [], judge.misses
    assert result["total"] == len(verdicts)
    assert result["supported"] == expected_supported
    assert result["faithfulness"] == pytest.approx(expected_faithfulness)


@pytest.mark.parametrize("answer_text", ["", "   \n\t "])
def test_judge_answer_on_an_empty_answer_is_zero_over_zero_and_calls_nothing(answer_text):
    # spec(T-026:AC-3)
    # `faithfulness` is 0.0 when total == 0 (ticket Context) — never a
    # ZeroDivisionError, and never a paid judge call for zero claims.
    judge = NeverCalledJudge()

    result = _attr("judge_answer")(QUESTION, answer_text, CHUNKS, judge)

    assert result == {"claims": [], "supported": 0, "total": 0, "faithfulness": 0.0}
    assert judge.call_count == 0


def test_judge_answer_keeps_going_after_a_mid_run_transport_error():
    # spec(T-026:AC-3)
    # plan-review M-8's real requirement: the run CONTINUES. AC-3's own
    # fixture puts the raiser last, which cannot distinguish "continues" from
    # "stops at the end anyway" — here the raiser is claim 2 of 4.
    bodies = [f"Sentence {i} is asserted." for i in range(4)]
    answer_text = " ".join(f"{body} [1]" for body in bodies)
    judge = ClaimKeyedJudge(
        {
            bodies[0]: _verdict_json("supported", 1),
            bodies[1]: JudgeTransportBoom("connection reset"),
            bodies[2]: _verdict_json("supported", 2),
            bodies[3]: _verdict_json("unsupported", None),
        }
    )

    result = _attr("judge_answer")(QUESTION, answer_text, CHUNKS, judge)

    assert judge.misses == [], judge.misses
    assert [entry["verdict"] for entry in result["claims"]] == [
        "supported",
        "error",
        "supported",
        "unsupported",
    ]
    assert judge.call_count == 4, "claims after the failing one must still be judged"
    assert (result["supported"], result["total"]) == (2, 4)
    assert result["faithfulness"] == pytest.approx(0.5)


@pytest.mark.parametrize(
    "boom",
    [
        JudgeTransportBoom("provider 5xx"),
        RuntimeError("generic runtime failure"),
        ValueError("bad response payload"),
        httpx.ConnectError("connection refused"),
        TimeoutError("read timeout"),
    ],
)
def test_judge_answer_records_any_judge_exception_as_an_error_verdict(boom):
    # spec(T-026:AC-3)
    judge = ClaimKeyedJudge({"Only claim": boom})

    result = _attr("judge_answer")(QUESTION, "Only claim here. [1]", CHUNKS, judge)

    assert judge.misses == [], judge.misses
    assert result["claims"] == [
        {"claim": "Only claim here. [1]", "verdict": "error", "evidence_chunk": None}
    ]
    assert (result["supported"], result["total"]) == (0, 1)
    assert result["faithfulness"] == pytest.approx(0.0)


def test_judge_answer_does_not_swallow_keyboard_interrupt():
    # spec(T-026:AC-3)
    # Failures-as-data covers PROVIDER failures, not the operator aborting a
    # long, paid eval run — `except Exception`, never `except BaseException`.
    judge = ClaimKeyedJudge({"Only claim": KeyboardInterrupt()})

    with pytest.raises(KeyboardInterrupt):
        _attr("judge_answer")(QUESTION, "Only claim here. [1]", CHUNKS, judge)


def test_judge_answer_counts_only_supported_toward_faithfulness():
    # spec(T-026:AC-3)
    # `unsupported`, `contradicted`, `unparseable` and `error` ALL count NOT
    # supported (ticket Context) — a faithfulness score must never be
    # inflated by the judge failing to answer.
    bodies = ["Alpha is asserted", "Bravo is asserted", "Charlie is asserted", "Delta is asserted"]
    answer_text = " ".join(f"{body}. [1]" for body in bodies)
    judge = ClaimKeyedJudge(
        {
            bodies[0]: _verdict_json("unsupported", None),
            bodies[1]: _verdict_json("contradicted", 1),
            bodies[2]: "not json",
            bodies[3]: JudgeTransportBoom("boom"),
        }
    )

    result = _attr("judge_answer")(QUESTION, answer_text, CHUNKS, judge)

    assert judge.misses == [], judge.misses
    assert [entry["verdict"] for entry in result["claims"]] == [
        "unsupported",
        "contradicted",
        "unparseable",
        "error",
    ]
    assert (result["supported"], result["total"]) == (0, 4)
    assert result["faithfulness"] == pytest.approx(0.0)


def test_judge_answer_sends_one_claim_per_call_and_never_the_whole_answer():
    # spec(T-026:AC-3)
    # Claim-level judging (spec Sec 5): prompt i carries claim i and no other
    # claim. Asserted on marker-free sentence bodies so that stripping `[n]`
    # markers before prompting stays a free implementation choice.
    judge = ConstantJudge(_verdict_json("supported", 1))

    _attr("judge_answer")(QUESTION, ANSWER_FIVE_CLAIMS, CHUNKS, judge)

    assert judge.call_count == 5
    for i, prompt in enumerate(judge.prompts):
        assert FIVE_CLAIM_BODIES[i] in prompt, f"prompt {i} must carry claim {i}"
        others = [body for j, body in enumerate(FIVE_CLAIM_BODIES) if j != i]
        leaked = [body for body in others if body in prompt]
        assert leaked == [], (
            f"prompt {i} leaked other claims {leaked} — one claim per call is what makes a "
            f"per-claim verdict meaningful"
        )
        assert QUESTION in prompt
        for chunk in CHUNKS:
            assert chunk in prompt


def test_judge_answer_records_one_verdict_per_claim_even_for_batched_judge_output():
    # spec(T-026:AC-3)
    # Malformed shape: the judge ignores the one-claim-per-call protocol and
    # answers for five claims at once. `total` must still equal the number of
    # segmented claims — the arithmetic denominator is OUR segmentation, never
    # the judge's opinion about how many claims there were.
    batched = json.dumps([{"verdict": "supported", "evidence_chunk": i} for i in range(1, 6)])
    judge = ConstantJudge(batched)

    result = _attr("judge_answer")(QUESTION, "First claim. [1] Second claim. [2]", CHUNKS, judge)

    assert result["total"] == 2
    assert len(result["claims"]) == 2
    assert judge.call_count == 2


# ==========================================================================
# AC-4 — validate_judge: agreement math, the artifact, and the cross-family
# precondition.
# ==========================================================================


def test_validate_judge_eight_of_ten_agreement_passes(tmp_path):
    # spec(T-026:AC-4)
    labels = _ten_labels()
    judge = ClaimKeyedJudge(_agreeing_script(labels, disagree_on={3, 7}))
    artifact = tmp_path / "artifacts" / "judge_validation.json"

    result = _attr("validate_judge")(
        judge, labels, GPT_MODEL, CLAUDE_MODEL, validation_path=str(artifact)
    )

    assert judge.misses == [], judge.misses
    assert result["agreement"] == pytest.approx(0.8)
    assert result["passed"] is True, "the gate is >= min_agreement, and 0.8 >= 0.8"
    assert result["n"] == 10
    assert result["disagreements"] == [
        {"label_id": "L-03", "human_verdict": "supported", "judge_verdict": "unsupported"},
        {"label_id": "L-07", "human_verdict": "supported", "judge_verdict": "unsupported"},
    ]
    assert set(result) == {"agreement", "passed", "n", "disagreements"}
    assert judge.call_count == 10, "one judge call per label"


def test_validate_judge_writes_the_artifact_with_exactly_the_pinned_keys(tmp_path):
    # spec(T-026:AC-4)
    labels = _ten_labels()
    judge = ClaimKeyedJudge(_agreeing_script(labels, disagree_on={3, 7}))
    artifact = tmp_path / "artifacts" / "judge_validation.json"

    _attr("validate_judge")(judge, labels, GPT_MODEL, CLAUDE_MODEL, validation_path=str(artifact))

    assert artifact.exists(), "a PASSING validation writes the artifact (creating dirs as needed)"
    payload = json.loads(artifact.read_text(encoding="utf-8"))
    assert set(payload) == {
        "timestamp",
        "judge_model",
        "generator_model",
        "agreement",
        "passed",
        "n",
    }, f"artifact keys are pinned exactly (run_faithfulness reads them); got {sorted(payload)}"
    assert payload["judge_model"] == GPT_MODEL
    assert payload["generator_model"] == CLAUDE_MODEL, (
        "BOTH ids are recorded: the artifact is the evidence that THIS pairing was "
        "cross-family-validated, not just that some judge scored well"
    )
    assert payload["agreement"] == pytest.approx(0.8)
    assert payload["passed"] is True
    assert payload["n"] == 10
    datetime.fromisoformat(payload["timestamp"])  # raises if it is not ISO-8601


def test_validate_judge_default_artifact_path_is_the_ticket_literal(tmp_path, monkeypatch):
    # spec(T-026:AC-4)
    monkeypatch.chdir(tmp_path)
    labels = _ten_labels()
    judge = ClaimKeyedJudge(_agreeing_script(labels, disagree_on={3, 7}))

    _attr("validate_judge")(judge, labels, GPT_MODEL, CLAUDE_MODEL)

    assert (tmp_path / "artifacts" / "judge_validation.json").exists(), (
        "the default validation_path is 'artifacts/judge_validation.json' — the same "
        "literal run_faithfulness defaults to, or the gate can never be satisfied"
    )


def test_validate_judge_seven_of_ten_fails_and_writes_no_artifact(tmp_path):
    # spec(T-026:AC-4)
    labels = _ten_labels()
    judge = ClaimKeyedJudge(_agreeing_script(labels, disagree_on={1, 3, 7}))
    artifact = tmp_path / "artifacts" / "judge_validation.json"

    result = _attr("validate_judge")(
        judge, labels, GPT_MODEL, CLAUDE_MODEL, validation_path=str(artifact)
    )

    assert judge.misses == [], judge.misses
    assert result["agreement"] == pytest.approx(0.7)
    assert result["passed"] is False
    assert result["n"] == 10
    assert len(result["disagreements"]) == 3
    assert not artifact.exists(), (
        "a FAILING validation must leave no artifact behind — the artifact IS the "
        "'verdicts count' token, and a failed run must not mint one"
    )


@pytest.mark.parametrize(
    ("min_agreement", "disagree_count", "expected_pass"),
    [
        (0.8, 2, True),  # exactly at the threshold -> inclusive
        (0.8, 3, False),
        (0.9, 2, False),  # a stricter caller-supplied gate
        (0.9, 1, True),
        (0.5, 5, True),
    ],
)
def test_validate_judge_threshold_is_inclusive_and_caller_settable(
    tmp_path, min_agreement, disagree_count, expected_pass
):
    # spec(T-026:AC-4)
    labels = _ten_labels()
    judge = ClaimKeyedJudge(_agreeing_script(labels, disagree_on=set(range(disagree_count))))
    artifact = tmp_path / "artifacts" / "judge_validation.json"

    result = _attr("validate_judge")(
        judge,
        labels,
        GPT_MODEL,
        CLAUDE_MODEL,
        min_agreement=min_agreement,
        validation_path=str(artifact),
    )

    assert judge.misses == [], judge.misses
    assert result["agreement"] == pytest.approx(1 - disagree_count / 10)
    assert result["passed"] is expected_pass
    assert artifact.exists() is expected_pass


def test_validate_judge_refuses_a_same_family_pair_before_any_judge_call(tmp_path):
    # spec(T-026:AC-4)
    labels = _ten_labels()
    judge = NeverCalledJudge()
    artifact = tmp_path / "artifacts" / "judge_validation.json"

    with pytest.raises(_attr("CrossFamilyViolation")):
        _attr("validate_judge")(
            judge, labels, "claude-3-5-haiku", CLAUDE_MODEL, validation_path=str(artifact)
        )

    assert judge.call_count == 0, (
        "assert_cross_family runs FIRST — a same-family pairing must cost zero paid "
        "judge calls, not be discovered after 10 of them"
    )
    assert not artifact.exists()


def test_validate_judge_refuses_an_unknown_family_pair(tmp_path):
    # spec(T-026:AC-4)
    labels = _ten_labels()
    judge = NeverCalledJudge()

    with pytest.raises(_attr("CrossFamilyViolation")):
        _attr("validate_judge")(
            judge,
            labels,
            "some-internal-model-v2",
            CLAUDE_MODEL,
            validation_path=str(tmp_path / "judge_validation.json"),
        )

    assert judge.call_count == 0


def test_validate_judge_counts_unparseable_output_as_a_disagreement(tmp_path):
    # spec(T-026:AC-4)
    labels = _ten_labels()
    judge = ConstantJudge("the judge refused to follow the protocol")
    artifact = tmp_path / "judge_validation.json"

    result = _attr("validate_judge")(
        judge, labels, GPT_MODEL, CLAUDE_MODEL, validation_path=str(artifact)
    )

    assert result["agreement"] == pytest.approx(0.0), (
        "an unparseable verdict can never AGREE with a hand label — otherwise a totally "
        "broken judge could validate itself"
    )
    assert result["passed"] is False
    assert [d["judge_verdict"] for d in result["disagreements"]] == ["unparseable"] * 10
    assert not artifact.exists()


def test_validate_judge_records_a_raising_judge_as_an_error_disagreement(tmp_path):
    # spec(T-026:AC-4)
    # Test Agent decision 7: the validation run is paid and human-labelled —
    # one transport blip must not discard the other rows.
    labels = _ten_labels()
    script = _agreeing_script(labels, disagree_on=set())
    script[labels[4]["claim"]] = JudgeTransportBoom("provider 5xx after retries")
    judge = ClaimKeyedJudge(script)

    result = _attr("validate_judge")(
        judge,
        labels,
        GPT_MODEL,
        CLAUDE_MODEL,
        validation_path=str(tmp_path / "judge_validation.json"),
    )

    assert judge.misses == [], judge.misses
    assert judge.call_count == 10, "the run continues past the failing label"
    assert result["agreement"] == pytest.approx(0.9)
    assert result["disagreements"] == [
        {"label_id": "L-04", "human_verdict": "contradicted", "judge_verdict": "error"}
    ]


def test_validate_judge_prompts_each_label_with_its_own_claim_and_question(tmp_path):
    # spec(T-026:AC-4)
    labels = _ten_labels()
    judge = ClaimKeyedJudge(_agreeing_script(labels, disagree_on=set()))

    _attr("validate_judge")(
        judge,
        labels,
        GPT_MODEL,
        CLAUDE_MODEL,
        validation_path=str(tmp_path / "judge_validation.json"),
    )

    assert judge.misses == [], judge.misses
    assert judge.call_count == len(labels)
    for label, prompt in zip(labels, judge.prompts, strict=True):
        assert label["claim"] in prompt
        assert label["question"] in prompt
        for chunk_text in label["chunk_texts"]:
            assert chunk_text in prompt, (
                "the label's own chunk_texts are the evidence the human graded against — "
                "validating against different evidence measures nothing"
            )


def test_validate_judge_on_empty_labels_raises_value_error(tmp_path):
    # spec(T-026:AC-4)
    # Test Agent decision 8: until the owner lands the ~10 real hand labels,
    # `load_labels()` returns [] (the shipped rows are example-only). A
    # silent 0.0 would read as "the judge is bad" instead of "there is no
    # label set yet".
    judge = NeverCalledJudge()

    with pytest.raises(ValueError) as excinfo:
        _attr("validate_judge")(
            judge, [], GPT_MODEL, CLAUDE_MODEL, validation_path=str(tmp_path / "v.json")
        )

    assert "label" in str(excinfo.value).lower(), (
        f"the error must say what is missing; got {excinfo.value!r}"
    )
    assert judge.call_count == 0


# ==========================================================================
# AC-5 — run_faithfulness: the verdicts-don't-count gate + the rag_eval row.
# ==========================================================================


def _run_faithfulness(tmp_path, artifact_path, answers=None, judge=None, judge_model=GPT_MODEL):
    return _attr("run_faithfulness")(
        ANSWERS_TWO if answers is None else answers,
        ClaimKeyedJudge(ANSWERS_TWO_SCRIPT) if judge is None else judge,
        judge_model,
        CLAUDE_MODEL,
        validation_path=str(artifact_path),
    )


def test_run_faithfulness_refuses_when_no_validation_artifact_exists(tmp_path, monkeypatch):
    # spec(T-026:AC-5)
    monkeypatch.chdir(tmp_path)
    missing = tmp_path / "artifacts" / "judge_validation.json"
    judge = NeverCalledJudge()

    with pytest.raises(_attr("JudgeNotValidated")) as excinfo:
        _run_faithfulness(tmp_path, missing, judge=judge)

    assert "judge_validation.json" in str(excinfo.value), (
        f"the refusal must name the artifact the operator has to produce; got {excinfo.value!r}"
    )
    assert judge.call_count == 0, "an unvalidated judge must not be paid to produce verdicts"
    assert not (tmp_path / "artifacts" / "rag_eval.jsonl").exists()


def test_run_faithfulness_refuses_when_the_artifact_says_passed_false(tmp_path, monkeypatch):
    # spec(T-026:AC-5)
    monkeypatch.chdir(tmp_path)
    artifact = _write_validation_artifact(
        tmp_path / "artifacts" / "judge_validation.json", passed=False, agreement=0.7
    )
    judge = NeverCalledJudge()

    with pytest.raises(_attr("JudgeNotValidated")):
        _run_faithfulness(tmp_path, artifact, judge=judge)

    assert judge.call_count == 0
    assert not (tmp_path / "artifacts" / "rag_eval.jsonl").exists()


def test_run_faithfulness_refuses_on_a_judge_model_mismatch(tmp_path, monkeypatch):
    # spec(T-026:AC-5)
    # The artifact certifies a SPECIFIC judge model. Swapping the model after
    # validation is exactly the "verdicts that never counted" hole spec Sec 5
    # closes.
    monkeypatch.chdir(tmp_path)
    artifact = _write_validation_artifact(
        tmp_path / "artifacts" / "judge_validation.json", judge_model="gpt-4o-mini"
    )
    judge = NeverCalledJudge()

    with pytest.raises(_attr("JudgeNotValidated")) as excinfo:
        _run_faithfulness(tmp_path, artifact, judge=judge, judge_model="gpt-4o")

    message = str(excinfo.value)
    assert "gpt-4o-mini" in message and "gpt-4o" in message, (
        f"the refusal must name the validated and requested models; got {message!r}"
    )
    assert judge.call_count == 0


@pytest.mark.parametrize(
    ("content", "why"),
    [
        ("{not json at all", "corrupt JSON"),
        ("[]", "not an object"),
        ('{"judge_model": "gpt-4o"}', "no passed key"),
        ('{"passed": true}', "no judge_model key"),
        ('{"passed": "true", "judge_model": "gpt-4o"}', "passed is a string, not a bool"),
    ],
)
def test_run_faithfulness_fails_closed_on_an_unusable_artifact(tmp_path, monkeypatch, content, why):
    # spec(T-026:AC-5)
    # An artifact that cannot be READ is not a passing artifact — it must
    # raise the typed JudgeNotValidated, never a JSONDecodeError/KeyError
    # (the caller catches the typed one) and never a silent pass.
    monkeypatch.chdir(tmp_path)
    artifact = tmp_path / "artifacts" / "judge_validation.json"
    artifact.parent.mkdir(parents=True, exist_ok=True)
    artifact.write_text(content, encoding="utf-8")
    judge = NeverCalledJudge()

    with pytest.raises(_attr("JudgeNotValidated")):
        _run_faithfulness(tmp_path, artifact, judge=judge)

    assert judge.call_count == 0, why


def test_run_faithfulness_appends_the_exact_shared_row_shape(tmp_path, monkeypatch):
    # spec(T-026:AC-5)
    # The row shape is pinned IDENTICALLY in tickets/T-025.md (a shared
    # schema stated in both tickets, not a code import) — extra or renamed
    # keys break the sidecar artifact both runners write.
    monkeypatch.chdir(tmp_path)
    monkeypatch.delenv("ONRECORD_INDEX", raising=False)
    artifact = _write_validation_artifact(tmp_path / "artifacts" / "judge_validation.json")
    judge = ClaimKeyedJudge(ANSWERS_TWO_SCRIPT)

    returned = _run_faithfulness(tmp_path, artifact, judge=judge)

    assert judge.misses == [], judge.misses
    eval_path = tmp_path / "artifacts" / "rag_eval.jsonl"
    assert eval_path.exists(), "results land in artifacts/rag_eval.jsonl"
    lines = [line for line in eval_path.read_text(encoding="utf-8").splitlines() if line.strip()]
    assert len(lines) == 1
    row = json.loads(lines[0])

    assert set(row) == {"timestamp", "git_sha", "corpus_version", "kind", "metrics"}, (
        f"rag_eval row keys are pinned exactly; got {sorted(row)}"
    )
    assert row["kind"] == "faithfulness"
    assert set(row["metrics"]) == {"mean_faithfulness", "per_answer"}
    assert row["metrics"]["per_answer"] == [
        {"qa_id": "qa-1", "faithfulness": 0.5, "supported": 1, "total": 2},
        {"qa_id": "qa-2", "faithfulness": 0.75, "supported": 3, "total": 4},
    ]
    assert row["metrics"]["mean_faithfulness"] == pytest.approx(0.625), (
        "mean_faithfulness is the MEAN OF PER-ANSWER faithfulness (0.5 and 0.75), not the "
        "micro-average over all claims (4/6 = 0.667) — the fixture is built so the two differ"
    )
    assert isinstance(row["git_sha"], str) and row["git_sha"]
    assert row["corpus_version"] == "unversioned", "no manifest reachable -> the pinned fallback"
    datetime.fromisoformat(row["timestamp"])
    assert returned == row, "run_faithfulness returns the row it appended"


def test_run_faithfulness_reads_corpus_version_from_the_index_manifest(tmp_path, monkeypatch):
    # spec(T-026:AC-5)
    # Same mechanism already frozen for onrecord.eval.run._corpus_version
    # (T-018 read_manifest via ONRECORD_INDEX) so the two artifact writers
    # never disagree about which corpus a number describes.
    monkeypatch.chdir(tmp_path)
    index_dir = tmp_path / "index"
    index_dir.mkdir()
    (index_dir / "manifest.json").write_text(json.dumps({"corpus_version": "v2"}), encoding="utf-8")
    monkeypatch.setenv("ONRECORD_INDEX", str(index_dir))
    artifact = _write_validation_artifact(tmp_path / "artifacts" / "judge_validation.json")

    row = _run_faithfulness(tmp_path, artifact)

    assert row["corpus_version"] == "v2"


def test_run_faithfulness_appends_and_never_truncates(tmp_path, monkeypatch):
    # spec(T-026:AC-5)
    monkeypatch.chdir(tmp_path)
    artifact = _write_validation_artifact(tmp_path / "artifacts" / "judge_validation.json")
    eval_path = tmp_path / "artifacts" / "rag_eval.jsonl"
    eval_path.parent.mkdir(parents=True, exist_ok=True)
    eval_path.write_text(json.dumps({"kind": "refusal", "metrics": {}}) + "\n", encoding="utf-8")

    _run_faithfulness(tmp_path, artifact)
    _run_faithfulness(tmp_path, artifact)

    lines = [line for line in eval_path.read_text(encoding="utf-8").splitlines() if line.strip()]
    assert len(lines) == 3, (
        "rag_eval.jsonl is an APPEND-ONLY sidecar shared with T-025's runner — a rewrite "
        "destroys the other runner's history"
    )
    assert json.loads(lines[0])["kind"] == "refusal"
    assert [json.loads(line)["kind"] for line in lines[1:]] == ["faithfulness", "faithfulness"]


def test_run_faithfulness_over_zero_answers_reports_zero(tmp_path, monkeypatch):
    # spec(T-026:AC-5)
    # Mirrors onrecord.eval.run._mean_metrics' frozen empty-input behaviour
    # (0.0, not an error).
    monkeypatch.chdir(tmp_path)
    artifact = _write_validation_artifact(tmp_path / "artifacts" / "judge_validation.json")
    judge = NeverCalledJudge()

    row = _run_faithfulness(tmp_path, artifact, answers=[], judge=judge)

    assert row["metrics"] == {"mean_faithfulness": 0.0, "per_answer": []}
    assert judge.call_count == 0


def test_run_faithfulness_default_validation_path_is_the_ticket_literal(tmp_path, monkeypatch):
    # spec(T-026:AC-5)
    monkeypatch.chdir(tmp_path)
    _write_validation_artifact(tmp_path / "artifacts" / "judge_validation.json")

    row = _attr("run_faithfulness")(
        ANSWERS_TWO, ClaimKeyedJudge(ANSWERS_TWO_SCRIPT), GPT_MODEL, CLAUDE_MODEL
    )

    assert row["kind"] == "faithfulness", (
        "with no validation_path given, the default 'artifacts/judge_validation.json' must "
        "be the file the gate consults"
    )


# ==========================================================================
# AC-6 — load_labels: schema validation with line numbers, example filtering.
# ==========================================================================


def test_load_labels_returns_rows_verbatim(tmp_path):
    # spec(T-026:AC-6)
    rows = [_label_row(0, "supported"), _label_row(1, "contradicted")]
    path = _write_labels_file(tmp_path / "labels.jsonl", rows)

    assert _attr("load_labels")(str(path)) == rows


def test_load_labels_tolerates_extra_annotation_keys(tmp_path):
    # spec(T-026:AC-6)
    # Hand-labelled data accretes columns (the owner's notes, a grader id).
    row = {**_label_row(0, "supported"), "notes": "graded 2026-08-12 by owner"}
    path = _write_labels_file(tmp_path / "labels.jsonl", [row])

    assert _attr("load_labels")(str(path)) == [row]


def test_load_labels_excludes_example_rows_by_default_and_includes_them_on_request(tmp_path):
    # spec(T-026:AC-6)
    example_a = _label_row(0, "supported", label_id="example-supported")
    example_b = _label_row(1, "unsupported", label_id="example-unsupported")
    real = _label_row(2, "contradicted", label_id="L-01")
    path = _write_labels_file(tmp_path / "labels.jsonl", [example_a, example_b, real])

    assert _attr("load_labels")(str(path)) == [real]
    assert _attr("load_labels")(str(path), include_examples=True) == [example_a, example_b, real]


@pytest.mark.parametrize("label_id", ["counterexample-1", "examples", "sample-1", "EXAMPLE-1"])
def test_load_labels_example_filter_is_a_prefix_test_not_a_substring_test(tmp_path, label_id):
    # spec(T-026:AC-6)
    # `"label_id": "example-*"` (ticket Context) is a PREFIX rule — a
    # substring match would silently drop a real hand label named
    # "counterexample-1", quietly shrinking the validation set.
    row = _label_row(0, "supported", label_id=label_id)
    path = _write_labels_file(tmp_path / "labels.jsonl", [row])

    assert _attr("load_labels")(str(path)) == [row]


@pytest.mark.parametrize(
    ("mutation", "field"),
    [
        ({"label_id": None}, "label_id"),
        ({"question": ""}, "question"),
        ({"answer_text": 7}, "answer_text"),
        ({"claim": "   "}, "claim"),
        ({"chunk_texts": "not a list"}, "chunk_texts"),
        ({"chunk_texts": [1, 2]}, "chunk_texts"),
        ({"human_verdict": "maybe"}, "human_verdict"),
        ({"human_verdict": "unparseable"}, "human_verdict"),
        ({"human_verdict": None}, "human_verdict"),
    ],
)
def test_load_labels_rejects_an_invalid_field_naming_line_and_field(tmp_path, mutation, field):
    # spec(T-026:AC-6)
    # Eval sets are GRADED artifacts (T-025's loader rule): never a silent
    # skip. `human_verdict` accepts only the three human-gradeable values —
    # "unparseable"/"error" are judge outputs, never hand labels.
    rows = [_label_row(0, "supported"), {**_label_row(1, "supported"), **mutation}]
    path = _write_labels_file(tmp_path / "labels.jsonl", rows)

    with pytest.raises(ValueError) as excinfo:
        _attr("load_labels")(str(path))

    message = _error_text(excinfo, path)
    assert _names_line(message, 2), (
        f"the error must name the 1-based line number (2); got {message!r}"
    )
    assert field in message, f"the error must name the offending field {field!r}; got {message!r}"


@pytest.mark.parametrize(
    "missing_field",
    ["label_id", "question", "answer_text", "chunk_texts", "claim", "human_verdict"],
)
def test_load_labels_rejects_a_row_missing_any_schema_field(tmp_path, missing_field):
    # spec(T-026:AC-6)
    row = _label_row(0, "supported")
    row.pop(missing_field)
    path = _write_labels_file(tmp_path / "labels.jsonl", [row])

    with pytest.raises(ValueError) as excinfo:
        _attr("load_labels")(str(path))

    message = _error_text(excinfo, path)
    assert _names_line(message, 1) and missing_field in message, (
        f"the error must name line 1 and the missing field {missing_field!r}; got {message!r}"
    )


def test_load_labels_line_numbers_survive_blank_lines(tmp_path):
    # spec(T-026:AC-6)
    # The classic off-by-one: counting only the rows it kept, or skipping
    # blanks without counting them, points the operator at the wrong line.
    good = json.dumps(_label_row(0, "supported"))
    bad = json.dumps({**_label_row(1, "supported"), "human_verdict": "nope"})
    path = tmp_path / "labels.jsonl"
    path.write_text(f"{good}\n\n{bad}\n", encoding="utf-8")

    with pytest.raises(ValueError) as excinfo:
        _attr("load_labels")(str(path))

    assert _names_line(_error_text(excinfo, path), 3), (
        f"the malformed row is on physical line 3 (line 2 is blank); got {excinfo.value!r}"
    )


def test_load_labels_rejects_a_line_that_is_not_json(tmp_path):
    # spec(T-026:AC-6)
    path = tmp_path / "labels.jsonl"
    path.write_text(
        f"{json.dumps(_label_row(0, 'supported'))}\nthis is not json\n", encoding="utf-8"
    )

    with pytest.raises(ValueError) as excinfo:
        _attr("load_labels")(str(path))

    assert _names_line(_error_text(excinfo, path), 2)


def test_load_labels_validates_example_rows_too(tmp_path):
    # spec(T-026:AC-6)
    # The committed example rows ARE the schema documentation (ticket DoD) —
    # a broken one must fail loudly even though the default filter drops it.
    broken_example = {
        **_label_row(0, "supported", label_id="example-broken"),
        "human_verdict": "definitely",
    }
    path = _write_labels_file(tmp_path / "labels.jsonl", [broken_example])

    with pytest.raises(ValueError) as excinfo:
        _attr("load_labels")(str(path))

    assert "human_verdict" in str(excinfo.value)


def test_load_labels_on_a_missing_file_raises_file_not_found(tmp_path):
    # spec(T-026:AC-6)
    missing = tmp_path / "no-such-labels.jsonl"

    with pytest.raises(FileNotFoundError) as excinfo:
        _attr("load_labels")(str(missing))

    assert "no-such-labels.jsonl" in str(excinfo.value)


def test_the_committed_labels_file_validates_against_its_own_loader():
    # spec(T-026:AC-6)
    # The shipped file is EXAMPLE-ONLY until the owner lands ~10 real hand
    # labels (ticket DoD owner ping), so this asserts the invariant that
    # survives that hand-off: every row validates, at least 2 example rows
    # document the schema, and the default filter drops exactly the
    # `example-` rows.
    _module()  # keep the failure mode uniform while judge.py is absent
    assert LABELS_FILE.exists(), (
        f"{LABELS_FILE} is a ticket deliverable (schema + 2 committed example rows)"
    )

    everything = _attr("load_labels")(str(LABELS_FILE), include_examples=True)
    default = _attr("load_labels")(str(LABELS_FILE))

    examples = [row for row in everything if row["label_id"].startswith("example-")]
    assert len(examples) >= 2, f"at least the 2 documented example rows must ship: {examples}"
    assert default == [row for row in everything if not row["label_id"].startswith("example-")]
    for row in everything:
        assert row["human_verdict"] in VERDICT_ENUM
        assert isinstance(row["chunk_texts"], list) and row["chunk_texts"]


# ==========================================================================
# AC-7 — config surface: default_judge, model-id plumbing, secret hygiene.
# ==========================================================================


def test_default_judge_without_a_key_raises_naming_the_env_var(monkeypatch):
    # spec(T-026:AC-7)
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("ONRECORD_JUDGE_MODEL", raising=False)

    with pytest.raises(_attr("JudgeNotConfigured")) as excinfo:
        _attr("default_judge")()

    assert "OPENAI_API_KEY" in str(excinfo.value), (
        "an unconfigured judge raises an ACTIONABLE error naming the variable, and never "
        "silently returns a fake (fakes are test-injected only)"
    )


def test_default_judge_with_a_key_constructs_a_callable(monkeypatch):
    # spec(T-026:AC-7)
    # The mirrored branch (plan-review I-5): both halves pinned so neither is
    # "environmentally lucky".
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)
    monkeypatch.delenv("ONRECORD_JUDGE_MODEL", raising=False)

    judge_fn = _attr("default_judge")()

    assert callable(judge_fn), "default_judge returns the injected-everywhere judge_fn shape"
    assert SENTINEL_KEY not in repr(judge_fn), (
        "a default repr that embeds the key lands it in every log line that interpolates "
        "the judge (LESSONS T-014)"
    )


def test_default_judge_posts_the_prompt_and_returns_the_message_content(monkeypatch):
    # spec(T-026:AC-7)
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)
    monkeypatch.delenv("ONRECORD_JUDGE_MODEL", raising=False)
    requests: list = []
    raw = _verdict_json("supported", 2)
    judge_fn = _attr("default_judge")(transport=_chat_handler(requests, content=raw))

    result = judge_fn("PROMPT-BODY-SENTINEL")

    assert result == raw, "judge_fn returns the assistant message content verbatim"
    assert len(requests) == 1
    assert requests[0].url.path.endswith("/chat/completions")
    assert requests[0].headers.get("authorization") == f"Bearer {SENTINEL_KEY}"
    assert "PROMPT-BODY-SENTINEL" in requests[0].content.decode("utf-8")


def test_default_judge_model_defaults_to_the_module_constant(monkeypatch):
    # spec(T-026:AC-7)
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)
    monkeypatch.delenv("ONRECORD_JUDGE_MODEL", raising=False)
    requests: list = []
    judge_fn = _attr("default_judge")(transport=_chat_handler(requests))

    judge_fn("prompt")

    body = json.loads(requests[0].content)
    assert body["model"] == _attr("DEFAULT_JUDGE_MODEL")
    assert _attr("resolved_judge_model")() == _attr("DEFAULT_JUDGE_MODEL")


def test_onrecord_judge_model_env_overrides_the_default(monkeypatch):
    # spec(T-026:AC-7)
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)
    monkeypatch.setenv("ONRECORD_JUDGE_MODEL", "gpt-override-for-tests")
    requests: list = []
    judge_fn = _attr("default_judge")(transport=_chat_handler(requests))

    judge_fn("prompt")

    assert json.loads(requests[0].content)["model"] == "gpt-override-for-tests"
    assert _attr("resolved_judge_model")() == "gpt-override-for-tests"


def test_default_judge_model_constant_is_cross_family_with_the_claude_generator():
    # spec(T-026:AC-7)
    # The literal id is research-required at provisioning (ticket DoD), so it
    # is deliberately NOT pinned here — what IS pinned is the property the
    # standing decision requires: whatever id ships must be a KNOWN family
    # and must not be the generator's. This fails loudly on an unfilled
    # placeholder (an empty or unrecognised id) or on an accidental Claude id.
    default_model = _attr("DEFAULT_JUDGE_MODEL")

    assert isinstance(default_model, str) and default_model.strip()
    _attr("assert_cross_family")(CLAUDE_MODEL, default_model)


def test_no_root_log_record_contains_the_api_key_on_the_success_path(monkeypatch, caplog):
    # spec(T-026:AC-7)
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)
    monkeypatch.delenv("ONRECORD_JUDGE_MODEL", raising=False)
    requests: list = []
    judge_fn = _attr("default_judge")(transport=_chat_handler(requests, content="{}"))

    with _library_loggers_unmuted(), caplog.at_level(logging.INFO):  # root: EVERY logger
        judge_fn("prompt")
        _assert_capture_is_live(caplog)

    assert requests, "precondition: the mocked request must actually have been made"
    assert requests[0].headers.get("authorization") == f"Bearer {SENTINEL_KEY}", (
        "precondition: the sentinel really was in flight during the captured window"
    )
    assert _leaking_records(caplog, SENTINEL_KEY) == [], (
        f"the key must never reach ANY log record — root + library loggers (LESSONS "
        f"T-014, where httpx logged a full keyed URL at INFO): "
        f"{_leaking_records(caplog, SENTINEL_KEY)}"
    )
    assert SENTINEL_KEY not in caplog.text


def test_no_root_log_record_contains_the_api_key_on_an_http_error_path(monkeypatch, caplog):
    # spec(T-026:AC-7)
    # Error paths are where keys leak — a naive `log.warning("judge failed:
    # %s", exc)` re-emits whatever the failure carries.
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)
    monkeypatch.delenv("ONRECORD_JUDGE_MODEL", raising=False)
    requests: list = []
    transport = _chat_handler(requests, statuses=[401, 500, 500, 500, 500, 500])
    judge_fn = _attr("default_judge")(transport=transport)

    with _library_loggers_unmuted(), caplog.at_level(logging.INFO):
        with pytest.raises(Exception) as excinfo:
            judge_fn("prompt")
        _assert_capture_is_live(caplog)

    assert not isinstance(excinfo.value, AssertionError)
    assert requests[0].headers.get("authorization") == f"Bearer {SENTINEL_KEY}", (
        "precondition: the sentinel really was in flight on the failing request"
    )
    assert _leaking_records(caplog, SENTINEL_KEY) == []
    assert SENTINEL_KEY not in caplog.text
    assert SENTINEL_KEY not in str(excinfo.value), (
        "nor may it appear in exception text (it propagates into tracebacks and any "
        "caller's own logging)"
    )
    assert SENTINEL_KEY not in repr(excinfo.value)


def test_a_transport_error_carrying_the_key_is_not_re_emitted(monkeypatch, caplog):
    # spec(T-026:AC-7)
    # The LIVENESS half (T-021 review I-7): the transport raises an error
    # whose own text embeds the Authorization header, so the sentinel is
    # provably REACHABLE from the exception the adapter must handle — this is
    # what proves the sentinel WOULD appear absent redaction, rather than the
    # test passing because nothing was ever logged.
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)
    monkeypatch.delenv("ONRECORD_JUDGE_MODEL", raising=False)
    raised: list = []
    judge_fn = _attr("default_judge")(transport=_leaky_transport(raised))

    with _library_loggers_unmuted(), caplog.at_level(logging.INFO):
        with pytest.raises(Exception) as excinfo:
            judge_fn("prompt")
        _assert_capture_is_live(caplog)

    assert raised and all(SENTINEL_KEY in message for message in raised), (
        "precondition: the transport error's own text must contain the key, otherwise "
        "this test proves nothing"
    )
    assert not isinstance(excinfo.value, AssertionError)
    assert SENTINEL_KEY not in str(excinfo.value), (
        "the adapter must not re-emit a transport error's text verbatim — catch "
        "httpx.HTTPError and raise your own message with no credential material"
    )
    assert SENTINEL_KEY not in repr(excinfo.value)
    assert _leaking_records(caplog, SENTINEL_KEY) == []


def test_a_failing_hosted_judge_degrades_to_error_verdicts_not_a_crash(monkeypatch):
    # spec(T-026:AC-7)
    # The two halves together: the real adapter's failure becomes DATA inside
    # judge_answer (ticket Context / plan-review M-8), so a provider outage
    # mid-eval yields a scored-zero row instead of a lost run.
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    monkeypatch.setenv("OPENAI_API_KEY", SENTINEL_KEY)
    monkeypatch.delenv("ONRECORD_JUDGE_MODEL", raising=False)
    requests: list = []
    judge_fn = _attr("default_judge")(transport=_chat_handler(requests, statuses=[500] * 20))

    result = _attr("judge_answer")(QUESTION, "First claim. [1] Second claim. [2]", CHUNKS, judge_fn)

    assert [entry["verdict"] for entry in result["claims"]] == ["error", "error"]
    assert result == {
        "claims": [
            {"claim": "First claim. [1]", "verdict": "error", "evidence_chunk": None},
            {"claim": "Second claim. [2]", "verdict": "error", "evidence_chunk": None},
        ],
        "supported": 0,
        "total": 2,
        "faithfulness": 0.0,
    }


def test_the_library_never_reads_the_generator_model_from_the_environment(tmp_path, monkeypatch):
    # spec(T-026:AC-7)
    # plan-review I-8, ONE source of truth: the generator id arrives as an
    # EXPLICIT parameter. Poison the env with an id whose family MATCHES the
    # judge's — if any code path preferred the env over the parameter, the
    # cross-family gate would flip and this call would raise.
    monkeypatch.setenv("ONRECORD_GENERATOR_MODEL", "gpt-4o-poison-from-env")
    labels = _ten_labels()
    judge = ClaimKeyedJudge(_agreeing_script(labels, disagree_on=set()))

    result = _attr("validate_judge")(
        judge,
        labels,
        GPT_MODEL,
        CLAUDE_MODEL,
        validation_path=str(tmp_path / "judge_validation.json"),
    )

    assert result["passed"] is True
    payload = json.loads((tmp_path / "judge_validation.json").read_text(encoding="utf-8"))
    assert payload["generator_model"] == CLAUDE_MODEL, (
        "the artifact must record the id that was PASSED IN — recording an env-derived id "
        "would certify a pairing that was never actually validated"
    )


def test_main_takes_its_generator_id_from_the_resolve_seam_not_the_environment(monkeypatch):
    # spec(T-026:AC-7)
    # The CLI's documented LAZY seam (ticket Context; same mechanism and
    # justification as T-025's `_resolve_answer_fn`, plan-review I-9). The
    # env is poisoned again here: `main()` must use the seam's value.
    mod = _module()
    monkeypatch.setenv("ONRECORD_GENERATOR_MODEL", "gpt-4o-poison-from-env")
    monkeypatch.setenv("ONRECORD_JUDGE_MODEL", "gpt-judge-for-main")
    monkeypatch.setattr(mod, "_resolve_generator_model", lambda: "claude-generator-from-seam")
    monkeypatch.setattr(mod, "_resolve_answers", lambda: ANSWERS_TWO)
    monkeypatch.setattr(
        mod, "default_judge", lambda *a, **kw: ConstantJudge(_verdict_json("supported", 1))
    )
    captured: list = []

    def _fake_run_faithfulness(answers, judge_fn, judge_model, generator_model, **kwargs):
        captured.append(
            {
                "answers": answers,
                "judge_model": judge_model,
                "generator_model": generator_model,
            }
        )
        return {"kind": "faithfulness", "metrics": {"mean_faithfulness": 1.0, "per_answer": []}}

    monkeypatch.setattr(mod, "run_faithfulness", _fake_run_faithfulness)

    exit_code = mod.main()

    assert captured, "main() must reach run_faithfulness"
    assert captured[0]["generator_model"] == "claude-generator-from-seam", (
        "the generator id comes from _resolve_generator_model() (T-023's "
        "resolved_generator_model, lazily imported) — never from an env read here"
    )
    assert captured[0]["judge_model"] == "gpt-judge-for-main"
    assert captured[0]["answers"] == ANSWERS_TWO
    assert exit_code == 0


def test_importing_judge_does_not_import_the_answer_pipeline():
    # spec(T-026:AC-7)
    # The seam's import must live INSIDE the function body: T-023 is
    # same-wave and unmerged while this ticket is implemented, so a
    # module-level `from onrecord.rag.answer import ...` is a collection
    # error in the wave-9 worktree. Run in a subprocess so another test's
    # imports cannot mask it, and asserted on sys.modules so it stays
    # meaningful AFTER T-023 merges (the laziness is the contract, not the
    # module's absence).
    _module()
    # `sys.stdout.write` rather than the print builtin, which the repo's
    # Tier-1 debug gate greps for in added lines (.tdd-swarm/gates.md).
    code = (
        "import sys; import onrecord.rag.judge as j; "
        "sys.stdout.write('LOADED' if 'onrecord.rag.answer' in sys.modules else 'LAZY'); "
        "sys.stdout.write('HASSEAM' if callable(j._resolve_generator_model) else 'NOSEAM')"
    )
    completed = subprocess.run(
        [sys.executable, "-c", code],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
        timeout=60,
    )

    assert completed.returncode == 0, (
        f"importing onrecord.rag.judge must succeed with no key, no network and no T-023 "
        f"present; stderr:\n{completed.stderr}"
    )
    assert "LAZY" in completed.stdout, (
        "onrecord.rag.answer must NOT be imported at judge-import time — the generator-model "
        "seam imports it lazily inside the function body"
    )
    assert "HASSEAM" in completed.stdout
