"""Failing tests for T-012 -- reference-BM25 differential (the assignment's
core ranking-math oracle: our BM25 vs `rank_bm25.BM25Okapi` on the IDENTICAL
analyzed token stream).

Encodes tickets/T-012.md AC-1..AC-4. These tests are FROZEN after the Test
Agent hands off: do not edit this file to make an implementation pass -- fix
the implementation (onrecord/eval/differential.py) instead.

Neither `onrecord/eval/differential.py` nor `tests/differential/` existed
before this ticket (import-guard pattern, matching tests/unit/test_bm25.py
and tests/unit/test_judgments.py). This file pins the module's exact API,
plus -- critically -- exactly what "our BM25 agrees with rank_bm25" means,
since the two libraries use DIFFERENT IDF formulas that do NOT coincide in
general (see "IDF reconciliation" below, required reading before touching
the implementation).

Run with:
    uv run pytest tests/differential/ -v

--------------------------------------------------------------------------
IDF reconciliation -- read this before writing/reviewing an implementation
--------------------------------------------------------------------------

Ours (`onrecord.rank.bm25.bm25_score`, T-011, frozen):

    idf_ours(df) = ln(1 + (N - df + 0.5) / (df + 0.5)) = ln((N + 1) / (df + 0.5))

    Always strictly positive for any 0 <= df <= N (proved in bm25.py's own
    docstring: N+1 > N+0.5 >= df+0.5, so the ratio is always > 1).

`rank_bm25.BM25Okapi._calc_idf` (read from the installed package source,
`.venv/lib/python*/site-packages/rank_bm25.py`, `BM25Okapi.__init__` default
`epsilon=0.25`):

    idf_theirs_raw(df) = ln(N - df + 0.5) - ln(df + 0.5) = ln((N - df + 0.5) / (df + 0.5))

    This is CLASSIC probabilistic IDF (no "+1"): strictly negative once
    df > N/2. `BM25Okapi` floors any negative-idf TERM to
    `epsilon * average_idf` -- a single scalar shared by every floored term
    in that corpus, derived from the *mean* raw idf across the corpus's
    *entire* vocabulary (not from that term's own df at all). A corpus
    dominated by common terms can even drive `average_idf` itself negative,
    at which point the "floor" is a negative number too. This flooring has
    NO analog in our always-positive formula -- there is nothing to
    reconcile it against, so the domain below is chosen to sidestep it
    entirely (every fixture query's terms have df comfortably < N/2, i.e.
    idf_theirs_raw > 0 always, so `average_idf`/epsilon-floor never enters
    the comparison on either side).

The saturation/length-norm factor IS byte-for-byte identical between the
two libraries given matched tf/doc_len/avg_doc_len/k1/b (verified against
`rank_bm25.BM25Okapi.get_scores`'s source):

    tf * (k1 + 1) / (tf + k1 * (1 - b + b * doc_len / avg_doc_len))

So the two total-score formulas are `idf_ours(df) * saturation(...)` vs
`idf_theirs(df) * saturation(...)` -- same saturation, different idf.
`idf_ours(df) != idf_theirs_raw(df)` in general (different logs entirely),
so NO universal exact-score-equality or fixed-tolerance score bound holds
across arbitrary queries/corpora. A differential test that asserted one
anyway would be pinning a false equivalence -- exactly what this ticket
warns against.

**What DOES hold, provably, not just empirically:**

For any query where every analyzed term shares the SAME document frequency
`df` (trivially true of every single-term query, and true of any
deliberately-constructed multi-term query drawn from one df-cohort), and
that shared `df < N/2` (idf_theirs_raw > 0, no epsilon floor):

    score_ours(doc) = idf_ours(df) * sum_t saturation(t, doc)
    score_theirs(doc) = idf_theirs_raw(df) * sum_t saturation(t, doc)

Because `idf_ours(df)` and `idf_theirs_raw(df)` are each a SINGLE SCALAR
(constant across every term in the query and every candidate doc), our
score is EXACTLY `c = idf_ours(df) / idf_theirs_raw(df)` times the
reference score for every candidate, for that query. Since `c > 0`, this
proportionality means, for that query:
  (a) top-k ORDER agrees exactly (a positive-scalar rescale never
      reorders; ties are broken identically on both sides by ascending
      external doc id, per this module's pinned tie-break);
  (b) per-doc SCORES agree exactly (to floating-point precision) after
      multiplying the reference score by the documented constant `c`.

This is the domain AC-1/AC-2 are pinned against below: the committed
50-doc fixture corpus (`fixtures/corpus.jsonl`) and all 10 fixture queries
(`fixtures/queries.txt`) are deliberately constructed so every query's
analyzed terms share one df value each (6 single-term queries spanning
df in {3, 7, 12, 18}; 4 multi-term queries where every term in the query
was assigned the identical target df at corpus-generation time) -- see
"Fixture corpus construction" below. Verified via a throwaway
implementation before freezing (max relative score deviation after the
`c`-transform was ~1e-16, i.e. floating-point noise, across every fixture
query) -- see the Test Agent's handoff report.

**What does NOT hold, and is not pinned as passing:** cross-df multi-term
queries (terms with DIFFERING document frequencies in the same query).
`idf_ours(df)/idf_theirs_raw(df)` is not a constant across df -- it grows
with df (the "+1" inflates a common (high-df) term's relative weight more
than a rare (low-df) term's), so the two systems can weigh a query's terms
differently enough to flip which candidate doc ranks higher, even with
every individual df < N/2. This is DEMONSTRATED, not hypothetical: the
committed 5-doc `fixtures/divergence_corpus.jsonl` +
`fixtures/divergence_queries.txt` (query "rare common", df(rare)=1 vs
df(common)=2, both « N/2=2.5) produces a genuinely different top-1 doc
between the two systems -- this is exactly what AC-4's exit-1 path
exercises below. An implementation must NOT special-case or "fix" this
divergence; it is mathematically real, not a bug.

--------------------------------------------------------------------------
Fixture corpus construction (fixtures/corpus.jsonl, fixtures/queries.txt)
--------------------------------------------------------------------------

50 synthetic `Doc`s (`source_type="filing"`), generated with a fixed seed.
Twelve "signal" terms are partitioned into four df-cohorts, each term
assigned to exactly `df` distinct documents at construction time (verified
programmatically, not just intended):

    df=3:  substation, megawatt, curtailment
    df=7:  transformer, capacitor, switchgear
    df=12: interconnection, hearing, docket
    df=18: variance, easement, petitioner

(N=50, so N/2=25 -- every cohort df is comfortably below it.) The 10
fixture queries (`queries.txt`, one per line) are:

    substation                          (single-term, df=3)
    transformer                         (single-term, df=7)
    interconnection                     (single-term, df=12)
    variance                            (single-term, df=18)
    megawatt                            (single-term, df=3)
    petitioner                          (single-term, df=18)
    substation megawatt curtailment     (same-df=3, 3 terms)
    transformer capacitor               (same-df=7, 2 terms)
    interconnection hearing docket      (same-df=12, 3 terms)
    variance easement                   (same-df=18, 2 terms)

Every doc is also padded with filler tokens from a large disjoint
vocabulary (never a query term), so `doc_len`/`avg_doc_len` vary
realistically. The REAL analyzer (`onrecord.analysis.analyzer.analyze`,
T-002) tokenizes the corpus for BOTH systems -- this is the entire point
of a differential test ("isolates ranking math from tokenization", per the
ticket's Context) -- never a trivial injected analyzer.

--------------------------------------------------------------------------
onrecord/eval/differential.py -- frozen contract
--------------------------------------------------------------------------

    @dataclass(frozen=True)
    class QueryDiff:
        query: str
        terms: list[str]
        our_ranking: list[str]        # top-k external doc ids, our system
        reference_ranking: list[str]  # top-k external doc ids, rank_bm25,
                                       # RESTRICTED to our own OR-semantics
                                       # candidate set (docs matching >=1
                                       # query term) -- rank_bm25.get_scores
                                       # returns a score for EVERY doc in the
                                       # corpus, including 0-score docs that
                                       # match no query term at all; those
                                       # must be excluded from this
                                       # comparison or a low-df query would
                                       # spuriously "mismatch" purely because
                                       # the reference ranking is padded
                                       # with irrelevant docs our OR-semantics
                                       # never considers candidates.
        order_agrees: bool            # our_ranking == reference_ranking
        score_transform: float | None # c s.t. our_score ~= c * reference_score,
                                       # computed ONLY when every term in the
                                       # query shares one df (else None) --
                                       # see "IDF reconciliation" above
        max_rel_score_diff: float | None  # max relative deviation from the
                                       # c-transform over shared candidates
                                       # (None when score_transform is None)

    @dataclass(frozen=True)
    class DifferentialReport:
        query_diffs: list[QueryDiff]
        all_orders_agree: bool        # all(qd.order_agrees for qd in query_diffs)

    def run_differential(
        index_docs: list[onrecord.types.Doc],
        queries: list[str],
        k1: float = 1.5,
        b: float = 0.75,
        k: int = 10,
        analyzer: Callable[[str], list[str]] | None = None,
    ) -> DifferentialReport: ...

`analyzer=None` means "use the real `onrecord.analysis.analyzer.analyze`"
(the default used throughout this suite; tests that need a controlled
vocabulary for hypothesis-generated corpora inject a trivial analyzer
instead, exactly like tests/unit/test_bm25.py's `TRIVIAL_ANALYZER`
convention). Both `index_docs` and every analyzed query's tie-break use
ASCENDING external `Doc.id` (matching `onrecord.search.ranked.ranked_search`'s
own pinned tie-break, T-011).

    def main(argv: list[str] | None = None) -> int: ...

CLI (argparse, `prog="python -m onrecord.eval.differential"`):
    --corpus   PATH   required   UTF-8 JSONL, one `Doc(**json.loads(line))`
                                  per line (blank lines skipped) -- same
                                  convention as `onrecord.eval.pooling._load_corpus`
    --queries  PATH   required   UTF-8 text file, one query per line (blank
                                  lines skipped)
    --k1       FLOAT  default 1.5
    --b        FLOAT  default 0.75
    --k        INT    default 10

Prints a per-query line for every query (status OK/MISMATCH + the query
text), and on any mismatch also prints both rankings for that query
(AC-4's "per-query diff table"). Returns 0 if `report.all_orders_agree`,
else 1. No default corpus/queries path is baked into the module itself
(onrecord/ production code never hardcodes a path into tests/ -- callers,
including this suite, always pass `--corpus`/`--queries` explicitly).
"""

from __future__ import annotations

import importlib.util
import json
import math
import subprocess
import sys
from pathlib import Path

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st
from rank_bm25 import BM25Okapi

from onrecord.analysis.analyzer import analyze
from onrecord.index.inverted import InvertedIndex
from onrecord.rank.bm25 import bm25_score
from onrecord.search.ranked import ranked_search
from onrecord.types import Doc

# --------------------------------------------------------------------------
# Guard helper -- see module docstring; established pattern from
# tests/unit/test_bm25.py and tests/unit/test_judgments.py.
# --------------------------------------------------------------------------


def _require_module_spec(name: str, fail_message: str):
    try:
        spec = importlib.util.find_spec(name)
    except ModuleNotFoundError:
        spec = None
    if spec is None:
        pytest.fail(fail_message)
    return spec


def _import_differential_module():
    _require_module_spec("onrecord.eval.differential", "onrecord.eval.differential missing")
    import onrecord.eval.differential as differential_mod

    return differential_mod


# --------------------------------------------------------------------------
# Fixture corpus / queries -- committed under tests/differential/fixtures/,
# see module docstring "Fixture corpus construction".
# --------------------------------------------------------------------------

FIXTURES_DIR = Path(__file__).parent / "fixtures"
CORPUS_PATH = FIXTURES_DIR / "corpus.jsonl"
QUERIES_PATH = FIXTURES_DIR / "queries.txt"
DIVERGENCE_CORPUS_PATH = FIXTURES_DIR / "divergence_corpus.jsonl"
DIVERGENCE_QUERIES_PATH = FIXTURES_DIR / "divergence_queries.txt"


def _load_corpus(path: Path) -> list[Doc]:
    docs = []
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            stripped = line.strip()
            if stripped:
                docs.append(Doc(**json.loads(stripped)))
    return docs


def _load_queries(path: Path) -> list[str]:
    with path.open("r", encoding="utf-8") as fh:
        return [line.strip() for line in fh if line.strip()]


FIXTURE_DOCS = _load_corpus(CORPUS_PATH)
FIXTURE_QUERIES = _load_queries(QUERIES_PATH)


@pytest.fixture(scope="module")
def fixture_index() -> InvertedIndex:
    # Real analyzer (analyzer=None default) -- the whole point of a
    # differential test is comparing ranking math on an IDENTICAL token
    # stream, per the ticket's own Context.
    return InvertedIndex.build(FIXTURE_DOCS)


def test_fixture_corpus_has_50_docs_and_10_queries():
    assert len(FIXTURE_DOCS) == 50
    assert len(FIXTURE_QUERIES) == 10


def test_fixture_query_terms_share_identical_df_and_stay_below_half_corpus(fixture_index):
    # Sanity-checks the fixture's own construction claim (module docstring):
    # every query's analyzed terms share one df, all comfortably < N/2.
    N = fixture_index.doc_count()
    for query in FIXTURE_QUERIES:
        terms = analyze(query)
        dfs = {fixture_index.df(t) for t in terms}
        assert len(dfs) == 1, f"query {query!r} terms have mismatched df: {dfs}"
        (df,) = dfs
        assert 0 < df < N / 2, f"query {query!r} df={df} is not comfortably below N/2={N / 2}"


# --------------------------------------------------------------------------
# Independent reference computations -- never call run_differential to
# compute what run_differential is being checked against (would make the
# test tautological). Mirrors tests/unit/test_bm25.py's `_ref_doc_score`
# pattern: hand-computed, straight off the real InvertedIndex's own stats
# plus a freshly-built rank_bm25.BM25Okapi.
# --------------------------------------------------------------------------


def _independent_our_scores(
    index: InvertedIndex, terms: list[str], k1: float = 1.5, b: float = 0.75
) -> dict[str, float]:
    N = index.doc_count()
    avg_len = index.avg_doc_length()
    candidate_ids: set[int] = set()
    for t in terms:
        candidate_ids.update(index.postings(t).doc_ids)
    scores: dict[str, float] = {}
    for iid in candidate_ids:
        doc_len = index.doc_length(iid)
        total = 0.0
        for t in terms:
            df = index.df(t)
            postings = index.postings(t)
            doc_ids = list(postings.doc_ids)
            tf = list(postings.tfs)[doc_ids.index(iid)] if iid in doc_ids else 0
            total += bm25_score(tf, df, N, doc_len, avg_len, k1=k1, b=b)
        scores[index.get_doc(iid).id] = total
    return scores


def _independent_reference_scores(
    docs: list[Doc], terms: list[str], k1: float = 1.5, b: float = 0.75
) -> dict[str, float]:
    token_lists = [analyze(d.text) for d in docs]
    reference = BM25Okapi(token_lists, k1=k1, b=b)
    raw_scores = reference.get_scores(terms)
    return {docs[i].id: float(raw_scores[i]) for i in range(len(docs))}


def _independent_expected_diff(docs, index, query, k1=1.5, b=0.75, k=10):
    """Full independent (query, expected top-k order per system) pair --
    used by both AC-1 and AC-4 to cross-check run_differential's output."""
    terms = analyze(query)
    our_scores = _independent_our_scores(index, terms, k1, b)
    ref_scores_all = _independent_reference_scores(docs, terms, k1, b)
    candidate_ids = set(our_scores)
    ref_scores = {d: ref_scores_all[d] for d in candidate_ids}
    our_order = sorted(candidate_ids, key=lambda d: (-our_scores[d], d))[:k]
    ref_order = sorted(candidate_ids, key=lambda d: (-ref_scores[d], d))[:k]
    return terms, our_scores, ref_scores, our_order, ref_order


# --------------------------------------------------------------------------
# Guard tests -- module importability.
# --------------------------------------------------------------------------


def test_differential_module_is_importable():
    _require_module_spec("onrecord.eval.differential", "onrecord.eval.differential missing")


def test_differential_module_exposes_frozen_dataclasses():
    diff_mod = _import_differential_module()
    assert hasattr(diff_mod, "QueryDiff")
    assert hasattr(diff_mod, "DifferentialReport")
    assert hasattr(diff_mod, "run_differential")
    assert hasattr(diff_mod, "main")


# --------------------------------------------------------------------------
# AC-1 -- top-10 ranking ORDER matches BM25Okapi's exactly, for every one
# of the 10 fixture queries (identical tokens, matched k1/b=1.5/0.75).
# --------------------------------------------------------------------------


@pytest.mark.parametrize("query", FIXTURE_QUERIES)
def test_ac1_order_agrees_exactly_for_every_fixture_query(query, fixture_index):
    # spec(T-012:AC-1)
    diff_mod = _import_differential_module()

    report = diff_mod.run_differential(FIXTURE_DOCS, [query], k1=1.5, b=0.75, k=10)
    assert len(report.query_diffs) == 1
    qd = report.query_diffs[0]

    terms, _, _, expected_our_order, expected_ref_order = _independent_expected_diff(
        FIXTURE_DOCS, fixture_index, query
    )
    assert expected_our_order == expected_ref_order, (
        f"sanity check failed for query {query!r}: the independently hand-computed "
        f"reference order itself disagrees with our order -- this fixture query is "
        f"not actually in the provable same-df agreement domain (see module docstring)"
    )

    assert qd.query == query
    assert qd.terms == terms
    assert qd.order_agrees is True, (
        f"query {query!r}: run_differential reported order_agrees=False, but this "
        f"fixture query is in the provable exact-agreement domain (same-df, df<N/2)"
    )
    assert qd.our_ranking == expected_our_order
    assert qd.reference_ranking == expected_ref_order


def test_ac1_report_all_orders_agree_true_for_full_fixture_query_set(fixture_index):
    # spec(T-012:AC-1)
    diff_mod = _import_differential_module()
    report = diff_mod.run_differential(FIXTURE_DOCS, FIXTURE_QUERIES, k1=1.5, b=0.75, k=10)
    assert len(report.query_diffs) == 10
    assert report.all_orders_agree is True
    assert all(qd.order_agrees for qd in report.query_diffs)


# --------------------------------------------------------------------------
# AC-2 -- per-doc scores agree within documented tolerance (the c-transform
# derived in "IDF reconciliation" above); any systematic deviation fails.
# --------------------------------------------------------------------------


@pytest.mark.parametrize("query", FIXTURE_QUERIES)
def test_ac2_score_agrees_via_documented_constant_transform(query, fixture_index):
    # spec(T-012:AC-2)
    diff_mod = _import_differential_module()

    terms = analyze(query)
    dfs = {fixture_index.df(t) for t in terms}
    assert len(dfs) == 1, f"fixture query {query!r} must be single-df by construction"
    (df,) = dfs
    N = fixture_index.doc_count()
    idf_ours = math.log(1 + (N - df + 0.5) / (df + 0.5))
    idf_theirs_raw = math.log((N - df + 0.5) / (df + 0.5))
    assert idf_theirs_raw > 0, "fixture df must stay below N/2 (module docstring)"
    expected_c = idf_ours / idf_theirs_raw

    report = diff_mod.run_differential(FIXTURE_DOCS, [query], k1=1.5, b=0.75, k=10)
    qd = report.query_diffs[0]

    assert qd.score_transform is not None, (
        f"query {query!r} is same-df by construction -- score_transform must be computed"
    )
    assert qd.score_transform == pytest.approx(expected_c, rel=1e-9)
    assert qd.max_rel_score_diff is not None
    assert qd.max_rel_score_diff < 1e-6, (
        f"query {query!r}: max relative score deviation {qd.max_rel_score_diff} after "
        f"applying the documented c-transform exceeds 1e-6 -- systematic deviation"
    )


def test_ac2_cross_df_query_reports_no_transform_not_a_false_equivalence():
    # spec(T-012:AC-2) -- a cross-df query (terms with DIFFERING document
    # frequencies) is NOT in the provable-agreement domain (module
    # docstring): score_transform/max_rel_score_diff must be None rather
    # than silently computing a bogus/misleading "tolerance" that doesn't
    # actually hold. Reuses two fixture terms from different df-cohorts.
    diff_mod = _import_differential_module()
    query = "substation transformer"  # df=3 vs df=7 -- deliberately cross-df

    report = diff_mod.run_differential(FIXTURE_DOCS, [query], k1=1.5, b=0.75, k=10)
    qd = report.query_diffs[0]
    assert qd.score_transform is None
    assert qd.max_rel_score_diff is None


# --------------------------------------------------------------------------
# AC-3 -- property (assignment invariant 3, per docs/presearch-transcript.md
# section D: "a doc gaining a query term cannot rank below an identical doc
# lacking it"), tested against OUR implementation (InvertedIndex +
# ranked_search), NOT the reference library.
#
# Formalized as: an "otherwise-identical" doc means SAME total token count
# -- `extra` filler tokens are swapped out for `extra` more occurrences of
# the query term (never appended, which would grow doc_len and could
# legitimately violate the invariant for MULTI-term queries once a
# companion term's length-normalization penalty outweighs the target
# term's own tf-saturation gain -- discovered and verified with a
# throwaway reference implementation before freezing; see the Test Agent's
# handoff report. T-011's own tf-monotonicity property
# (tests/unit/test_bm25.py) similarly holds doc_len/avg_doc_len fixed, for
# the same underlying reason). Verified over 1000+ hypothesis examples
# against the real InvertedIndex + ranked_search stack (both single- and
# two-term OR queries, 0-4 extra corpus docs) before freezing.
# --------------------------------------------------------------------------


def TRIVIAL_ANALYZER(text: str) -> list[str]:
    return text.lower().split()


def _ac3_doc(doc_id: str, tokens: list[str], n: int) -> Doc:
    return Doc(
        id=doc_id,
        text=" ".join(tokens),
        source_type="filing",
        venue_type="written",
        date="2025-01-01",
        deep_link=f"https://example.test/{n}",
    )


_AC3_FILLERS = ["alpha", "bravo", "charlie", "delta", "echo", "foxtrot", "golf", "hotel"]
_AC3_TARGETS = ["zeta", "yankee", "xray"]


@st.composite
def _ac3_params(draw):
    target = draw(st.sampled_from(_AC3_TARGETS))
    companion = draw(st.one_of(st.none(), st.sampled_from(_AC3_FILLERS)))
    non_query_fillers = [f for f in _AC3_FILLERS if f != companion]
    extra = draw(st.integers(min_value=1, max_value=5))
    total_len = draw(st.integers(min_value=extra + 1, max_value=extra + 15))
    base_tf = draw(st.integers(min_value=0, max_value=total_len - extra))
    filler_slots = total_len - base_tf  # guaranteed >= extra -- never falls
    # back to doc-length growth (see docstring above for why that matters).
    filler_pool = draw(
        st.lists(st.sampled_from(non_query_fillers), min_size=filler_slots, max_size=filler_slots)
    )
    n_other_docs = draw(st.integers(min_value=0, max_value=4))
    other_docs_tokens = draw(
        st.lists(
            st.lists(st.sampled_from([*_AC3_FILLERS, target]), min_size=1, max_size=10),
            min_size=n_other_docs,
            max_size=n_other_docs,
        )
    )
    return target, base_tf, extra, filler_pool, other_docs_tokens, companion


@given(params=_ac3_params())
@settings(max_examples=200, deadline=None)
def test_property_doc_gaining_a_query_term_occurrence_never_ranks_below_doc_lacking_it(params):
    # spec(T-012:AC-3)
    target, base_tf, extra, filler_pool, other_docs_tokens, companion = params

    less_tokens = filler_pool + [target] * base_tf
    more_tokens = filler_pool[:-extra] + [target] * (base_tf + extra)
    assert len(less_tokens) == len(more_tokens), "otherwise-identical: doc_len must be held fixed"

    docs = [_ac3_doc("doc_less", less_tokens, 0), _ac3_doc("doc_more", more_tokens, 1)]
    for i, tokens in enumerate(other_docs_tokens):
        docs.append(_ac3_doc(f"doc_other_{i}", tokens, 2 + i))

    idx = InvertedIndex.build(docs, analyzer=TRIVIAL_ANALYZER)
    query = target if companion is None else f"{target} {companion}"

    results = ranked_search(idx, query, k=len(docs), analyzer=TRIVIAL_ANALYZER)
    scores = {r.doc_id: r.score for r in results}
    less_score = scores.get("doc_less", 0.0)
    more_score = scores.get("doc_more", 0.0)

    assert more_score >= less_score - 1e-9, (
        f"target={target} base_tf={base_tf} extra={extra} companion={companion}: "
        f"doc_more (tf={base_tf + extra}) scored {more_score} < "
        f"doc_less (tf={base_tf}) scored {less_score}"
    )


# --------------------------------------------------------------------------
# AC-4 -- `python -m onrecord.eval.differential` exit-code contract: 0 on
# agreement (main fixture), 1 with a per-query diff table on divergence
# (divergence fixture, module docstring).
# --------------------------------------------------------------------------

_CLI_TIMEOUT = 60


def _run_differential_cli(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "onrecord.eval.differential", *args],
        capture_output=True,
        text=True,
        timeout=_CLI_TIMEOUT,
    )


def test_ac4_cli_exits_zero_on_the_agreeing_main_fixture():
    # spec(T-012:AC-4)
    _require_module_spec("onrecord.eval.differential", "onrecord.eval.differential missing")
    proc = _run_differential_cli("--corpus", str(CORPUS_PATH), "--queries", str(QUERIES_PATH))
    assert proc.returncode == 0, f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"


def test_ac4_cli_exits_nonzero_with_per_query_diff_table_on_the_divergence_fixture():
    # spec(T-012:AC-4)
    _require_module_spec("onrecord.eval.differential", "onrecord.eval.differential missing")

    # Independent sanity check: this fixture must genuinely diverge,
    # verified straight off the real InvertedIndex + a fresh BM25Okapi --
    # never assume the CLI's own report is correct without cross-checking.
    div_docs = _load_corpus(DIVERGENCE_CORPUS_PATH)
    div_queries = _load_queries(DIVERGENCE_QUERIES_PATH)
    assert len(div_queries) == 1
    div_index = InvertedIndex.build(div_docs)
    _, _, _, expected_our_order, expected_ref_order = _independent_expected_diff(
        div_docs, div_index, div_queries[0]
    )
    assert expected_our_order != expected_ref_order, (
        "sanity check failed: the divergence fixture no longer actually diverges "
        "independently of the CLI -- fixture or analyzer behavior changed"
    )

    proc = _run_differential_cli(
        "--corpus", str(DIVERGENCE_CORPUS_PATH), "--queries", str(DIVERGENCE_QUERIES_PATH)
    )
    assert proc.returncode == 1, f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
    assert div_queries[0] in proc.stdout, "diff table must identify which query diverged"
    for doc_id in expected_our_order:
        assert doc_id in proc.stdout, f"diff table must show doc id {doc_id!r} from the ranking"
    assert len(proc.stdout.strip().splitlines()) >= 2, (
        "must be a genuine per-query table, not one line"
    )


def test_ac4_cli_missing_required_args_is_a_usage_error_not_a_crash_on_none():
    # spec(T-012:AC-4) -- --corpus/--queries are required (module docstring:
    # onrecord/ production code never bakes a default path into tests/), so
    # omitting them must be argparse's own usage-error path (exit code 2),
    # not an unguarded crash trying to open path `None`.
    _require_module_spec("onrecord.eval.differential", "onrecord.eval.differential missing")
    proc = _run_differential_cli()
    assert proc.returncode == 2, f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"


def test_ac4_main_function_returns_int_directly_matching_cli_exit_code(fixture_index):
    # spec(T-012:AC-4) -- `main(argv)` itself (not just the subprocess/CLI
    # wrapper) returns the same 0/1 contract, called with an explicit argv
    # list (never relying on sys.argv), matching onrecord.eval.judgments's
    # `main(argv=None)` convention.
    diff_mod = _import_differential_module()
    del fixture_index  # not used directly -- CORPUS_PATH/QUERIES_PATH are module-level

    rc_ok = diff_mod.main(["--corpus", str(CORPUS_PATH), "--queries", str(QUERIES_PATH)])
    assert rc_ok == 0

    rc_diverge = diff_mod.main(
        ["--corpus", str(DIVERGENCE_CORPUS_PATH), "--queries", str(DIVERGENCE_QUERIES_PATH)]
    )
    assert rc_diverge == 1
