"""Failing tests for T-003 — inverted index (df, tf, positions, save/load/delete).

Encodes tickets/T-003.md AC-1..AC-5. These tests are FROZEN after the Test
Agent hands off: do not edit this file to make an implementation pass — fix
the implementation (onrecord/index/inverted.py) instead.

CRITICAL ISOLATION FROM T-002
-----------------------------
T-002 (the real analyzer, `onrecord.analysis.analyzer.analyze`) is implemented
IN PARALLEL, in a separate worktree, by a different agent. In *this* worktree
`analyze()` is still a stub that raises `NotImplementedError` (see
onrecord/analysis/analyzer.py). These tests therefore MUST NOT exercise the
real analyzer, directly or indirectly.

To make that possible, the frozen `InvertedIndex.build()` contract from T-001
is EXTENDED for dependency injection:

    InvertedIndex.build(docs, analyzer=None)

`analyzer=None` means "use the real `onrecord.analysis.analyzer.analyze`"
(untestable in this worktree). Every test below ALWAYS passes an explicit,
trivial analyzer instead:

    TRIVIAL_ANALYZER = lambda t: t.lower().split()

The implementer MUST honor the `analyzer` keyword with that default — the
stub signature in onrecord/index/inverted.py has already been updated (by
this Test Agent) to `build(cls, docs, analyzer=None)` so that calling
`build(docs, analyzer=...)` fails with the stub's `NotImplementedError`
(the correct RED failure mode) rather than a `TypeError` for an unexpected
keyword argument.

Schema assumption pinned here (not otherwise nailed down by the ticket text,
documented per T-001 Test Agent practice — see .tdd-swarm/reports/T-001-test.md):
`Postings.doc_ids` holds internal integer doc ids assigned ONCE at build()
time, in the order docs appear in the input `docs` list (first doc in the
list -> smallest internal id), and those ids are stable thereafter (`delete`
does not renumber survivors). This is the only reading under which AC-1's
concrete example ("postings tfs are [3,1] with correct sorted doc ids") is
mechanically checkable, so tests that rely on it build fixtures with the
higher-tf doc listed FIRST and only assert relative/monotonic ordering
(never a literal `[0, 1]`) to avoid over-constraining the exact integer
values chosen by the implementer. Tests that don't need this assumption
(retrievability via `get_doc`, delete semantics, df counts) avoid it
entirely and use only the frozen, external-id-based surface
(`get_doc`, `delete`, `doc_count`, `df`).

Run with:
    uv run pytest tests/unit/test_index.py -v
"""

from __future__ import annotations

from onrecord.index.inverted import InvertedIndex
from onrecord.types import Doc

# ---------------------------------------------------------------------------
# Injected trivial analyzer — the ONLY analyzer these tests ever use.
# Position of token i in the returned list is i (matches the real analyzer's
# documented contract: "token i's position is list index i").
# ---------------------------------------------------------------------------


def TRIVIAL_ANALYZER(text: str) -> list[str]:
    return text.lower().split()


def _make_doc(doc_id: str, text: str, n: int = 0) -> Doc:
    return Doc(
        id=doc_id,
        text=text,
        source_type="filing",
        venue_type="written",
        date="2024-01-01",
        deep_link=f"https://example.test/doc/{n}",
    )


# ---------------------------------------------------------------------------
# AC-1 — df + postings tfs, correct sorted doc ids
# ---------------------------------------------------------------------------


def test_df_and_postings_tfs_with_correct_sorted_doc_ids():
    # spec(T-003:AC-1)
    doc_3x = _make_doc("doc-three", "substation substation substation transformer", 0)
    doc_1x = _make_doc("doc-one", "the substation is near the county line", 1)
    doc_0x = _make_doc("doc-zero", "no relevant term here at all", 2)

    idx = InvertedIndex.build([doc_3x, doc_1x, doc_0x], analyzer=TRIVIAL_ANALYZER)

    assert idx.df("substation") == 2

    postings = idx.postings("substation")
    doc_ids = list(postings.doc_ids)
    tfs = list(postings.tfs)

    assert len(doc_ids) == 2
    assert len(tfs) == 2
    # doc_ids must be sorted ascending with no duplicates.
    assert doc_ids == sorted(doc_ids)
    assert len(set(doc_ids)) == len(doc_ids)
    # doc_3x was built first -> smallest internal id -> sorts first, and its
    # tf (3) must precede doc_1x's tf (1), matching AC-1's [3, 1] literally.
    assert tfs == [3, 1]


def test_df_counts_distinct_documents_not_occurrences():
    # spec(T-003:AC-1)
    doc_a = _make_doc("a", "grid grid grid grid", 0)
    doc_b = _make_doc("b", "grid", 1)
    idx = InvertedIndex.build([doc_a, doc_b], analyzer=TRIVIAL_ANALYZER)

    assert idx.df("grid") == 2
    assert idx.doc_count() == 2


# ---------------------------------------------------------------------------
# AC-2 — positions equal the (injected) analyzer's token indices
# ---------------------------------------------------------------------------


def test_positions_match_injected_analyzer_token_indices_single_doc():
    # spec(T-003:AC-2)
    text = "the substation near the substation gate"
    doc = _make_doc("d0", text, 0)
    idx = InvertedIndex.build([doc], analyzer=TRIVIAL_ANALYZER)

    tokens = TRIVIAL_ANALYZER(text)
    expected_positions = [i for i, tok in enumerate(tokens) if tok == "substation"]
    assert expected_positions == [1, 4]  # sanity on the fixture itself

    postings = idx.postings("substation")
    assert len(postings.positions) == 1
    assert list(postings.positions[0]) == expected_positions
    assert list(postings.tfs) == [len(expected_positions)]


def test_positions_align_with_doc_ids_across_multiple_docs():
    # spec(T-003:AC-2)
    doc_3x = _make_doc("doc-three", "substation substation substation transformer", 0)
    doc_1x = _make_doc("doc-one", "the substation is near the county line", 1)
    idx = InvertedIndex.build([doc_3x, doc_1x], analyzer=TRIVIAL_ANALYZER)

    postings = idx.postings("substation")
    assert len(postings.positions) == 2
    # doc_3x sorts first (smallest internal id, per pinned build-order
    # assumption); its three "substation" tokens are at positions 0,1,2.
    assert list(postings.positions[0]) == [0, 1, 2]
    # doc_1x: "the substation is near the county line" -> substation at index 1.
    assert list(postings.positions[1]) == [1]


# ---------------------------------------------------------------------------
# AC-3 — save/load round-trip
# ---------------------------------------------------------------------------


def test_save_load_round_trip_preserves_df_postings_and_doc_store(tmp_path):
    # spec(T-003:AC-3)
    doc_3x = _make_doc("doc-three", "substation substation substation transformer", 0)
    doc_1x = _make_doc("doc-one", "the substation is near the county line", 1)
    doc_0x = _make_doc("doc-zero", "no relevant term here at all", 2)
    docs = [doc_3x, doc_1x, doc_0x]

    idx = InvertedIndex.build(docs, analyzer=TRIVIAL_ANALYZER)

    save_path = tmp_path / "index-round-trip"
    idx.save(save_path)
    loaded = InvertedIndex.load(save_path)

    assert loaded.doc_count() == idx.doc_count()

    all_terms = {tok for d in docs for tok in TRIVIAL_ANALYZER(d.text)}
    for term in all_terms:
        assert loaded.df(term) == idx.df(term), f"df mismatch after round-trip for {term!r}"

        before = idx.postings(term)
        after = loaded.postings(term)
        assert list(after.doc_ids) == list(before.doc_ids), f"doc_ids mismatch for {term!r}"
        assert list(after.tfs) == list(before.tfs), f"tfs mismatch for {term!r}"
        assert len(after.positions) == len(before.positions), f"positions len mismatch for {term!r}"
        for pos_before, pos_after in zip(before.positions, after.positions, strict=True):
            assert list(pos_after) == list(pos_before), f"positions mismatch for {term!r}"

    for doc in docs:
        assert loaded.get_doc(doc.id) == idx.get_doc(doc.id) == doc


def test_save_load_round_trip_survives_a_delete():
    # spec(T-003:AC-3)
    import tempfile
    from pathlib import Path

    doc_a = _make_doc("a", "substation transformer", 0)
    doc_b = _make_doc("b", "substation county", 1)
    idx = InvertedIndex.build([doc_a, doc_b], analyzer=TRIVIAL_ANALYZER)
    idx.delete("a")

    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "idx"
        idx.save(path)
        loaded = InvertedIndex.load(path)

    assert loaded.doc_count() == 1
    assert loaded.df("substation") == 1
    assert loaded.df("transformer") == 0
    try:
        loaded.get_doc("a")
    except KeyError:
        pass
    else:
        raise AssertionError("get_doc('a') should raise KeyError after a deleted doc round-trips")


# ---------------------------------------------------------------------------
# AC-4 — delete purges postings everywhere + get_doc raises + df decrements
# ---------------------------------------------------------------------------


def test_delete_removes_doc_from_get_doc_and_decrements_doc_count():
    # spec(T-003:AC-4)
    doc_a = _make_doc("a", "substation transformer", 0)
    doc_b = _make_doc("b", "substation county", 1)
    idx = InvertedIndex.build([doc_a, doc_b], analyzer=TRIVIAL_ANALYZER)

    idx.delete("a")

    assert idx.doc_count() == 1
    try:
        idx.get_doc("a")
    except KeyError:
        pass
    else:
        raise AssertionError("get_doc('a') should raise KeyError after delete('a')")

    # Survivor unaffected.
    assert idx.get_doc("b") == doc_b


def test_delete_decrements_df_for_shared_term():
    # spec(T-003:AC-4)
    doc_a = _make_doc("a", "substation transformer", 0)
    doc_b = _make_doc("b", "substation county", 1)
    idx = InvertedIndex.build([doc_a, doc_b], analyzer=TRIVIAL_ANALYZER)

    assert idx.df("substation") == 2
    idx.delete("a")
    assert idx.df("substation") == 1

    postings = idx.postings("substation")
    assert len(list(postings.doc_ids)) == 1
    assert list(postings.tfs) == [1]


def test_delete_purges_term_unique_to_deleted_doc_everywhere():
    # spec(T-003:AC-4)
    doc_a = _make_doc("a", "substation transformer", 0)
    doc_b = _make_doc("b", "substation county", 1)
    idx = InvertedIndex.build([doc_a, doc_b], analyzer=TRIVIAL_ANALYZER)

    assert idx.df("transformer") == 1
    idx.delete("a")

    # "transformer" only ever appeared in the now-deleted doc "a" -> purged
    # entirely: df drops to 0 and postings are empty, no exception.
    assert idx.df("transformer") == 0
    postings = idx.postings("transformer")
    assert list(postings.doc_ids) == []
    assert list(postings.tfs) == []
    assert list(postings.positions) == []


def test_delete_on_sole_holder_drives_df_to_zero():
    # spec(T-003:AC-4)
    doc = _make_doc("solo", "unique-term-xyz", 0)
    idx = InvertedIndex.build([doc], analyzer=TRIVIAL_ANALYZER)

    assert idx.df("unique-term-xyz") == 1
    idx.delete("solo")
    assert idx.df("unique-term-xyz") == 0
    assert idx.doc_count() == 0


# ---------------------------------------------------------------------------
# AC-5 — absent term: df==0, empty postings, no exception
# ---------------------------------------------------------------------------


def test_absent_term_has_zero_df_and_empty_postings_no_exception():
    # spec(T-003:AC-5)
    doc = _make_doc("a", "substation transformer", 0)
    idx = InvertedIndex.build([doc], analyzer=TRIVIAL_ANALYZER)

    assert idx.df("this-term-never-appears-anywhere") == 0

    postings = idx.postings("this-term-never-appears-anywhere")
    assert list(postings.doc_ids) == []
    assert list(postings.tfs) == []
    assert list(postings.positions) == []


def test_absent_term_on_empty_index_no_exception():
    # spec(T-003:AC-5)
    idx = InvertedIndex.build([], analyzer=TRIVIAL_ANALYZER)

    assert idx.doc_count() == 0
    assert idx.df("anything") == 0
    postings = idx.postings("anything")
    assert list(postings.doc_ids) == []
    assert list(postings.tfs) == []
    assert list(postings.positions) == []
