"""Failing tests for T-001 — scaffold (package, frozen interfaces, registry, Makefile).

Encodes tickets/T-001.md AC-1..AC-4. These tests are FROZEN after the Test Agent
hands off: do not edit this file to make an implementation pass — fix the
implementation (onrecord/, pyproject.toml, Makefile, corpus/registry.yaml)
instead. Written adversarially: assumes nothing exists yet and nothing about
an implementer's good intentions.

Run with:
    uv run --with pytest --with pyyaml -- pytest tests/unit/test_scaffold.py -v

Schema assumption not otherwise pinned by the ticket (documented here for the
implementer and reviewer): corpus/registry.yaml is a YAML mapping with three
top-level lists, named after the exact nouns used in AC-3:
    youtube_channels: [{id, name, jurisdiction, state, ...}, ...]   (>= 45)
    tickers:          [{symbol, sector, ...}, ...]                  (>= 90)
    docket_sources:   [...]                                         (>= 10)
`onrecord.registry.load()` (no args) must return something exposing those same
three collections, either as mapping keys or attributes (both styles accepted
below) so the implementer is free to return a dict or a small wrapper object.
"""

from __future__ import annotations

import importlib.util
import re
import shutil
import subprocess
from dataclasses import MISSING, FrozenInstanceError, fields, is_dataclass
from pathlib import Path

import pytest
import yaml

# tests/unit/test_scaffold.py -> parents[2] is the repo root (worktree root).
REPO_ROOT = Path(__file__).resolve().parents[2]

YOUTUBE_CHANNEL_MIN = 45
TICKER_MIN = 90
DOCKET_MIN = 10
REQUIRED_CHANNEL_KEYS = {"id", "name", "jurisdiction", "state"}
REQUIRED_TICKER_KEYS = {"symbol", "sector"}

DOC_REQUIRED_FIELDS = ("id", "text", "source_type", "venue_type", "date", "deep_link")
DOC_OPTIONAL_FIELDS = ("ticker", "jurisdiction", "speaker")
SEARCHRESULT_FIELDS = ("doc_id", "score", "snippet")

_MISSING = object()


# --------------------------------------------------------------------------
# Helpers (not tests)
# --------------------------------------------------------------------------


def _read_makefile_text() -> str:
    path = REPO_ROOT / "Makefile"
    if not path.exists():
        pytest.fail("Makefile missing")
    return path.read_text()


def _target_block(text: str, name: str) -> str | None:
    """Return a target's definition line + indented recipe lines, or None."""
    pattern = re.compile(rf"(?m)^{re.escape(name)}\s*:.*\n(?:^[ \t]+.*\n?)*")
    m = pattern.search(text)
    return m.group(0) if m else None


def _load_registry_yaml() -> dict:
    path = REPO_ROOT / "corpus" / "registry.yaml"
    if not path.exists():
        pytest.fail("corpus/registry.yaml missing")
    with path.open() as fh:
        data = yaml.safe_load(fh)
    assert isinstance(data, dict), "corpus/registry.yaml must parse to a mapping"
    return data


def _attr_or_key(obj, key):
    """Accept either dict-style or attribute-style access on load() result."""
    if isinstance(obj, dict):
        return obj.get(key, _MISSING)
    return getattr(obj, key, _MISSING)


def _require_module_spec(name: str, fail_message: str):
    """Return the module spec for `name`, or fail cleanly via pytest.fail.

    importlib.util.find_spec raises ModuleNotFoundError (rather than
    returning None) when a parent package in a dotted name is itself
    missing/unimportable, so this normalizes both "not found" cases into one
    clean assertion-style failure instead of an uncaught exception.
    """
    try:
        spec = importlib.util.find_spec(name)
    except ModuleNotFoundError:
        spec = None
    if spec is None:
        pytest.fail(fail_message)
    return spec


# --------------------------------------------------------------------------
# AC-1 — clean clone + `make setup` -> `import onrecord` succeeds
# --------------------------------------------------------------------------


def test_onrecord_package_importable():
    # spec(T-001:AC-1)
    spec = importlib.util.find_spec("onrecord")
    assert spec is not None, "onrecord package missing (importlib.util.find_spec returned None)"


def test_make_setup_installs_deps_and_onrecord_imports():
    # spec(T-001:AC-1)
    pyproject = REPO_ROOT / "pyproject.toml"
    assert pyproject.exists(), "pyproject.toml missing"

    assert shutil.which("uv") is not None, "uv executable not found on PATH"

    setup = subprocess.run(
        ["make", "setup"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=600,
        check=False,
    )
    assert setup.returncode == 0, (
        f"'make setup' failed (exit {setup.returncode}):\n"
        f"stdout:\n{setup.stdout}\nstderr:\n{setup.stderr}"
    )

    check = subprocess.run(
        ["uv", "run", "python", "-c", "import onrecord"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    assert check.returncode == 0, (
        "'uv run python -c \"import onrecord\"' failed "
        f"(exit {check.returncode}):\nstdout:\n{check.stdout}\nstderr:\n{check.stderr}"
    )


# --------------------------------------------------------------------------
# Frozen interface contracts (onrecord/types.py) — part of the AC-1 import
# surface: `import onrecord` is only meaningful if its core types are the
# exact frozen dataclasses the ticket freezes for Wave-2 tickets.
# --------------------------------------------------------------------------


def test_doc_dataclass_is_frozen_with_exact_fields():
    # spec(T-001:AC-1) -- frozen interface contract (onrecord/types.py::Doc)
    _require_module_spec("onrecord.types", "onrecord package missing")
    from onrecord.types import Doc

    assert is_dataclass(Doc), "Doc must be a dataclass"
    assert Doc.__dataclass_params__.frozen, "Doc must be declared @dataclass(frozen=True)"

    field_map = {f.name: f for f in fields(Doc)}
    expected_order = DOC_REQUIRED_FIELDS + DOC_OPTIONAL_FIELDS
    assert tuple(field_map.keys()) == expected_order, (
        f"Doc fields {tuple(field_map.keys())} do not match expected {expected_order}"
    )
    for name in DOC_REQUIRED_FIELDS:
        assert field_map[name].default is MISSING, f"Doc.{name} must be required (no default)"
    for name in DOC_OPTIONAL_FIELDS:
        assert field_map[name].default is None, f"Doc.{name} must default to None"

    doc = Doc(
        id="d1",
        text="the applicant is requesting 240 megawatts",
        source_type="county_meeting",
        venue_type="sworn",
        date="2025-11-05",
        deep_link="https://youtube.com/watch?v=x&t=1s",
    )
    with pytest.raises(FrozenInstanceError):
        doc.id = "changed"  # type: ignore[misc]


def test_searchresult_dataclass_is_frozen_with_exact_fields():
    # spec(T-001:AC-1) -- frozen interface contract (onrecord/types.py::SearchResult)
    _require_module_spec("onrecord.types", "onrecord package missing")
    from onrecord.types import SearchResult

    assert is_dataclass(SearchResult), "SearchResult must be a dataclass"
    assert SearchResult.__dataclass_params__.frozen, (
        "SearchResult must be declared @dataclass(frozen=True)"
    )

    field_map = {f.name: f for f in fields(SearchResult)}
    assert tuple(field_map.keys()) == SEARCHRESULT_FIELDS, (
        f"SearchResult fields {tuple(field_map.keys())} do not match expected {SEARCHRESULT_FIELDS}"
    )
    for name in SEARCHRESULT_FIELDS:
        assert field_map[name].default is MISSING, (
            f"SearchResult.{name} must be required (no default)"
        )

    sr = SearchResult(doc_id="d1", score=1.0, snippet="…240 megawatts…")
    with pytest.raises(FrozenInstanceError):
        sr.score = 2.0  # type: ignore[misc]


# --------------------------------------------------------------------------
# AC-2 — `uv run pytest -q` executes the suite (Makefile's `test` delegates)
# --------------------------------------------------------------------------


def test_makefile_test_target_delegates_to_pytest():
    # spec(T-001:AC-2)
    text = _read_makefile_text()
    block = _target_block(text, "test")
    assert block is not None, "Makefile missing a 'test' target definition"
    assert "pytest" in block, f"'test' target does not invoke pytest:\n{block}"


# --------------------------------------------------------------------------
# AC-4 — setup|test|eval|ingest|demo all exist; eval/ingest/demo delegate to
# `uv run python -m onrecord...` entrypoints.
# --------------------------------------------------------------------------


def test_makefile_defines_all_required_targets():
    # spec(T-001:AC-4)
    text = _read_makefile_text()
    required = ["setup", "test", "eval", "ingest", "demo"]
    missing = [t for t in required if _target_block(text, t) is None]
    assert not missing, f"Makefile missing target definitions for: {missing}"


@pytest.mark.parametrize("target", ["eval", "ingest", "demo"])
def test_makefile_stub_targets_delegate_to_onrecord_module(target):
    # spec(T-001:AC-4)
    text = _read_makefile_text()
    block = _target_block(text, target)
    assert block is not None, f"Makefile missing a '{target}' target definition"
    assert "uv run python -m onrecord" in block, (
        f"'{target}' target must delegate to a 'uv run python -m onrecord...' "
        f"entrypoint, got:\n{block}"
    )


# --------------------------------------------------------------------------
# AC-3 — corpus/registry.yaml scale + schema, loadable via onrecord.registry.load()
# --------------------------------------------------------------------------


def test_registry_file_exists():
    # spec(T-001:AC-3)
    path = REPO_ROOT / "corpus" / "registry.yaml"
    assert path.exists(), "corpus/registry.yaml missing"


def test_registry_youtube_channels_meet_scale_and_schema():
    # spec(T-001:AC-3)
    data = _load_registry_yaml()
    channels = data.get("youtube_channels")
    assert isinstance(channels, list), "registry.yaml must have a top-level 'youtube_channels' list"
    assert len(channels) >= YOUTUBE_CHANNEL_MIN, (
        f"expected >= {YOUTUBE_CHANNEL_MIN} youtube channels, found {len(channels)}"
    )
    for i, ch in enumerate(channels):
        assert isinstance(ch, dict), f"youtube_channels[{i}] must be a mapping"
        missing = REQUIRED_CHANNEL_KEYS - set(ch.keys())
        assert not missing, f"youtube_channels[{i}] missing keys: {sorted(missing)}"


def test_registry_tickers_meet_scale_and_schema():
    # spec(T-001:AC-3)
    data = _load_registry_yaml()
    tickers = data.get("tickers")
    assert isinstance(tickers, list), "registry.yaml must have a top-level 'tickers' list"
    assert len(tickers) >= TICKER_MIN, f"expected >= {TICKER_MIN} tickers, found {len(tickers)}"
    for i, tk in enumerate(tickers):
        assert isinstance(tk, dict), f"tickers[{i}] must be a mapping"
        missing = REQUIRED_TICKER_KEYS - set(tk.keys())
        assert not missing, f"tickers[{i}] missing keys: {sorted(missing)}"


def test_registry_docket_sources_meet_scale():
    # spec(T-001:AC-3)
    data = _load_registry_yaml()
    dockets = data.get("docket_sources")
    assert isinstance(dockets, list), "registry.yaml must have a top-level 'docket_sources' list"
    assert len(dockets) >= DOCKET_MIN, (
        f"expected >= {DOCKET_MIN} docket sources, found {len(dockets)}"
    )


def test_registry_loadable_via_onrecord_registry_load():
    # spec(T-001:AC-3)
    _require_module_spec("onrecord.registry", "onrecord.registry module missing")
    from onrecord import registry

    assert hasattr(registry, "load"), "onrecord.registry must expose a load() function"
    loaded = registry.load()

    channels = _attr_or_key(loaded, "youtube_channels")
    tickers = _attr_or_key(loaded, "tickers")
    dockets = _attr_or_key(loaded, "docket_sources")

    assert channels is not _MISSING, "onrecord.registry.load() result missing 'youtube_channels'"
    assert tickers is not _MISSING, "onrecord.registry.load() result missing 'tickers'"
    assert dockets is not _MISSING, "onrecord.registry.load() result missing 'docket_sources'"

    assert len(channels) >= YOUTUBE_CHANNEL_MIN, (
        f"onrecord.registry.load(): expected >= {YOUTUBE_CHANNEL_MIN} youtube "
        f"channels, found {len(channels)}"
    )
    assert len(tickers) >= TICKER_MIN, (
        f"onrecord.registry.load(): expected >= {TICKER_MIN} tickers, found {len(tickers)}"
    )
    assert len(dockets) >= DOCKET_MIN, (
        f"onrecord.registry.load(): expected >= {DOCKET_MIN} docket sources, found {len(dockets)}"
    )
