"""Failing tests for T-006 — YouTube captions adapter (VTT -> Doc, deep links).

Encodes tickets/T-006.md AC-1..AC-5. These tests are FROZEN after the Test
Agent hands off: do not edit this file to make an implementation pass — fix
the implementation (onrecord/ingest/youtube.py, scripts/pull_captions.sh)
instead. Written adversarially: assumes nothing beyond the stub exists and
nothing about an implementer's good intentions.

Run with:
    uv run pytest tests/unit/ingest/test_youtube.py -v

Zero network: every test below reads only committed fixtures under
tests/fixtures/youtube/. `onrecord.ingest.youtube.parse_video_dir` currently
raises NotImplementedError (see its module docstring for the full frozen
contract) — that is the CORRECT failure mode for every test that calls it
until T-006 is implemented.

Schema/contract decisions not otherwise pinned by the ticket (fixed here and
documented in onrecord/ingest/youtube.py's module docstring, which the
implementer must follow):

- File discovery: videos are found by globbing `*.info.json` in the target
  directory (non-recursive, sorted-filename order). The video id comes from
  the JSON body's `"id"` field, not the filename stem — yt-dlp's default
  naming embeds the title (`"<title> [<id>].info.json"`). The caption file
  is the lexicographically-first `<stem>.*.vtt` match in the same directory.
- Rollup dedupe (AC-2): a cue is dropped if its cleaned text is identical to
  the immediately preceding *retained* cue's cleaned text — a consecutive,
  whole-video-order comparison, not scoped per-window.
- Windowing: fixed 75s windows, `window_index = int(cue_start_seconds //
  75)`. A cue belongs to the window containing its START time. A cue that
  starts before a boundary and ends after it is NOT split (whole cue -> the
  earlier window). A cue starting exactly on a boundary (t=75.000s) belongs
  to the LATER window. Empty windows are omitted; window text is retained
  cues' cleaned text joined with a single space, in cue order.
- Malformed/truncated `.vtt` (AC-5) and missing `.vtt` (AC-3): the whole
  video is skipped (not partially recovered), with one WARNING-level log
  line (stdlib `logging`, `logging.getLogger("onrecord.ingest.youtube")`)
  naming the offending video id/stem. No exception escapes `parse_video_dir`
  either way, and any other videos in the same directory still parse.

Fixture layout (tests/fixtures/youtube/), a 3-video simulated channel pull:
    mixed_batch/
        "...Regular Meeting - June 11, 2025 [LCB0611meet].info.json" + ".en.vtt"
            well-formed: cues spanning 0-200s, upload_date 20250611,
            includes two consecutive-duplicate ("rollup") cue pairs, a cue
            that starts exactly at t=75.000s, and a cue that starts at t=70s
            and ends at t=82s (spans the 75s boundary).
        "...Budget Work Session (audio issue) [LCBbadvtt01].info.json" + ".en.vtt"
            malformed/truncated .vtt (cut off mid-timestamp, no cue text).
        "...Closed Session Placeholder [LCBnosubs01].info.json" (no .vtt)
            simulates "no English subs available".
    malformed_only/   — isolated copy of the LCBbadvtt01 pair (AC-5 alone).
    nosubs_only/      — isolated copy of the LCBnosubs01 info.json (AC-3 alone).

`registry_entry` fixtures mirror corpus/registry.yaml's `youtube_channels[i]`
shape (`id`, `name`, `jurisdiction`, `state`, `verified`).
"""

from __future__ import annotations

import logging
import stat
from pathlib import Path

from onrecord.ingest.youtube import parse_video_dir

# tests/unit/ingest/test_youtube.py -> parents[3] is the repo root (worktree root).
REPO_ROOT = Path(__file__).resolve().parents[3]

FIXTURES_DIR = REPO_ROOT / "tests" / "fixtures" / "youtube"
MIXED_BATCH_DIR = FIXTURES_DIR / "mixed_batch"
MALFORMED_ONLY_DIR = FIXTURES_DIR / "malformed_only"
NOSUBS_ONLY_DIR = FIXTURES_DIR / "nosubs_only"

PULL_SCRIPT = REPO_ROOT / "scripts" / "pull_captions.sh"

GOOD_VIDEO_ID = "LCB0611meet"
BAD_VIDEO_ID = "LCBbadvtt01"
NOSUB_VIDEO_ID = "LCBnosubs01"

LOUDOUN_ENTRY = {
    "id": "https://www.youtube.com/@LoudounCountyBoardofSupervisors",
    "name": "Loudoun County Board of Supervisors",
    "jurisdiction": "Loudoun County, VA",
    "state": "VA",
    "verified": False,
}

FAIRFAX_ENTRY = {
    "id": "https://www.youtube.com/@FairfaxCountyBoardofSupervisors",
    "name": "Fairfax County Board of Supervisors",
    "jurisdiction": "Fairfax County, VA",
    "state": "VA",
    "verified": False,
}

# Expected window text for the well-formed video, computed by hand from the
# mixed_batch/*.en.vtt fixture: cue lines joined with a single space, in cue
# order, with the two consecutive-duplicate ("rollup") cues collapsed.
WINDOW0_TEXT = (
    "Good evening. I'll call this meeting to order. "
    "Roll call: Chair Randall present, Vice Chair Briskman present. "
    "Item four: rezoning application ZMAP twenty twenty five dash eleven for a data center campus. "
    "The applicant proposes a two hundred forty megawatt capacity increase near the existing "
    "substation. "
    "Staff recommends approval subject to the proffered conditions on noise and water use. "
    "This cue begins before and ends after the seventy five second window boundary."
)
WINDOW1_TEXT = (
    "This cue starts exactly at the seventy five second boundary and belongs to the next window. "
    "Supervisor Briskman asks about traffic impact studies for the proposed site. "
    "The applicant's traffic engineer summarizes the trip generation analysis for the board."
)
WINDOW2_TEXT = (
    "Chair Randall opens the public hearing for comment on the rezoning application. "
    "Three residents signed up to speak in support and two in opposition. "
    "The board closes the public hearing and moves to deliberation on the record."
)


def _docs_for(docs: list, video_id: str) -> list:
    return [d for d in docs if d.id.startswith(f"yt:{video_id}:")]


# --------------------------------------------------------------------------
# AC-1 — 3 Docs from cues spanning 0-200s, correct &t= starts, concatenated text
# --------------------------------------------------------------------------


def test_ac1_three_windows_with_correct_ids_and_deep_link_starts():
    # spec(T-006:AC-1)
    docs = parse_video_dir(MIXED_BATCH_DIR, LOUDOUN_ENTRY)
    good = sorted(_docs_for(docs, GOOD_VIDEO_ID), key=lambda d: d.id)

    assert [d.id for d in good] == [
        f"yt:{GOOD_VIDEO_ID}:seg000",
        f"yt:{GOOD_VIDEO_ID}:seg001",
        f"yt:{GOOD_VIDEO_ID}:seg002",
    ]
    assert [d.deep_link for d in good] == [
        f"https://youtube.com/watch?v={GOOD_VIDEO_ID}&t=0s",
        f"https://youtube.com/watch?v={GOOD_VIDEO_ID}&t=75s",
        f"https://youtube.com/watch?v={GOOD_VIDEO_ID}&t=150s",
    ]


def test_ac1_window_text_is_concatenated_cue_text():
    # spec(T-006:AC-1)
    docs = parse_video_dir(MIXED_BATCH_DIR, LOUDOUN_ENTRY)
    good = {d.id: d for d in _docs_for(docs, GOOD_VIDEO_ID)}

    assert good[f"yt:{GOOD_VIDEO_ID}:seg000"].text == WINDOW0_TEXT
    assert good[f"yt:{GOOD_VIDEO_ID}:seg001"].text == WINDOW1_TEXT
    assert good[f"yt:{GOOD_VIDEO_ID}:seg002"].text == WINDOW2_TEXT


# --------------------------------------------------------------------------
# AC-1 adversarial — window-boundary assignment rule
# --------------------------------------------------------------------------


def test_window_boundary_cue_starting_exactly_at_75s_belongs_to_second_window():
    # spec(T-006:AC-1) -- adversarial: a cue whose start lands exactly on the
    # 75s boundary belongs to the LATER window (window_index = int(start // 75)).
    docs = parse_video_dir(MIXED_BATCH_DIR, LOUDOUN_ENTRY)
    good = {d.id: d for d in _docs_for(docs, GOOD_VIDEO_ID)}
    seg000 = good[f"yt:{GOOD_VIDEO_ID}:seg000"]
    seg001 = good[f"yt:{GOOD_VIDEO_ID}:seg001"]

    boundary_cue_text = "belongs to the next window"
    assert boundary_cue_text in seg001.text, (
        "cue starting at exactly t=75.000s must land in window 1"
    )
    assert boundary_cue_text not in seg000.text


def test_cue_spanning_window_boundary_assigned_by_start_time_not_end_time():
    # spec(T-006:AC-1) -- adversarial: a cue that starts at t=70s and ends at
    # t=82s spans the 75s boundary but is NOT split. Per the documented rule
    # ("a cue belongs to the window containing its start time"), it belongs
    # entirely to window 0, even though two-thirds of its span is in window 1.
    docs = parse_video_dir(MIXED_BATCH_DIR, LOUDOUN_ENTRY)
    good = {d.id: d for d in _docs_for(docs, GOOD_VIDEO_ID)}
    seg000 = good[f"yt:{GOOD_VIDEO_ID}:seg000"]
    seg001 = good[f"yt:{GOOD_VIDEO_ID}:seg001"]

    spanning_cue_text = "seventy five second window boundary"
    assert spanning_cue_text in seg000.text
    assert spanning_cue_text not in seg001.text


# --------------------------------------------------------------------------
# AC-2 — consecutive duplicated auto-caption rollup lines are collapsed
# --------------------------------------------------------------------------


def test_ac2_consecutive_duplicate_rollup_lines_collapsed():
    # spec(T-006:AC-2)
    docs = parse_video_dir(MIXED_BATCH_DIR, LOUDOUN_ENTRY)
    seg000 = next(d for d in docs if d.id == f"yt:{GOOD_VIDEO_ID}:seg000")

    # Each of these lines appears twice, back-to-back, in the raw .vtt fixture.
    assert seg000.text.count("Good evening. I'll call this meeting to order.") == 1
    assert seg000.text.count("Roll call: Chair Randall present, Vice Chair Briskman present.") == 1


def test_ac2_no_adjacent_duplicate_lines_in_any_window():
    # spec(T-006:AC-2)
    docs = parse_video_dir(MIXED_BATCH_DIR, LOUDOUN_ENTRY)
    for doc in _docs_for(docs, GOOD_VIDEO_ID):
        sentences = [s.strip() for s in doc.text.split(". ") if s.strip()]
        for prev, curr in zip(sentences, sentences[1:]):
            assert prev != curr, f"adjacent duplicate line in {doc.id}: {curr!r}"


# --------------------------------------------------------------------------
# AC-3 — video with no .vtt is skipped with a warning; others still parse
# --------------------------------------------------------------------------


def test_ac3_video_without_vtt_skipped_other_videos_still_parse(caplog):
    # spec(T-006:AC-3)
    with caplog.at_level(logging.WARNING):
        docs = parse_video_dir(MIXED_BATCH_DIR, LOUDOUN_ENTRY)

    assert not _docs_for(docs, NOSUB_VIDEO_ID), "video with no .vtt must produce zero Docs"
    assert _docs_for(docs, GOOD_VIDEO_ID), "other videos in the directory must still parse"

    warning_messages = [r.getMessage() for r in caplog.records if r.levelno == logging.WARNING]
    assert any(NOSUB_VIDEO_ID in msg for msg in warning_messages), (
        f"expected a WARNING log line naming {NOSUB_VIDEO_ID!r}; got: {warning_messages}"
    )


def test_ac3_isolated_nosubs_dir_returns_empty_list_no_exception(caplog):
    # spec(T-006:AC-3)
    with caplog.at_level(logging.WARNING):
        docs = parse_video_dir(NOSUBS_ONLY_DIR, LOUDOUN_ENTRY)

    assert docs == []


# --------------------------------------------------------------------------
# AC-4 — date from info.json upload_date; jurisdiction from registry_entry
# --------------------------------------------------------------------------


def test_ac4_date_iso_and_constant_source_venue_fields():
    # spec(T-006:AC-4)
    docs = parse_video_dir(MIXED_BATCH_DIR, LOUDOUN_ENTRY)
    good = _docs_for(docs, GOOD_VIDEO_ID)
    assert good, "expected the well-formed video to produce Docs"

    for doc in good:
        assert doc.date == "2025-06-11"
        assert doc.source_type == "county_meeting"
        assert doc.venue_type == "sworn"
        assert doc.ticker is None
        assert doc.speaker is None


def test_ac4_jurisdiction_populated_from_registry_entry_argument():
    # spec(T-006:AC-4)
    docs_loudoun = _docs_for(parse_video_dir(MIXED_BATCH_DIR, LOUDOUN_ENTRY), GOOD_VIDEO_ID)
    assert docs_loudoun and all(d.jurisdiction == "Loudoun County, VA" for d in docs_loudoun)

    # Same fixture files, a different registry_entry -> jurisdiction must
    # come from the argument, not be hardcoded or read from info.json.
    docs_fairfax = _docs_for(parse_video_dir(MIXED_BATCH_DIR, FAIRFAX_ENTRY), GOOD_VIDEO_ID)
    assert docs_fairfax and all(d.jurisdiction == "Fairfax County, VA" for d in docs_fairfax)


# --------------------------------------------------------------------------
# AC-5 — malformed/truncated .vtt is skipped with a warning; no crash
# --------------------------------------------------------------------------


def test_ac5_malformed_vtt_skipped_other_videos_still_parse(caplog):
    # spec(T-006:AC-5)
    with caplog.at_level(logging.WARNING):
        docs = parse_video_dir(MIXED_BATCH_DIR, LOUDOUN_ENTRY)

    assert not _docs_for(docs, BAD_VIDEO_ID), "malformed .vtt must produce zero Docs"
    assert _docs_for(docs, GOOD_VIDEO_ID), "other videos in the directory must still parse"

    warning_messages = [r.getMessage() for r in caplog.records if r.levelno == logging.WARNING]
    assert any(BAD_VIDEO_ID in msg for msg in warning_messages), (
        f"expected a WARNING log line naming {BAD_VIDEO_ID!r}; got: {warning_messages}"
    )


def test_ac5_isolated_malformed_dir_returns_empty_list_no_crash(caplog):
    # spec(T-006:AC-5)
    with caplog.at_level(logging.WARNING):
        docs = parse_video_dir(MALFORMED_ONLY_DIR, LOUDOUN_ENTRY)

    assert docs == []


# --------------------------------------------------------------------------
# scripts/pull_captions.sh — light tests (implementer scope; not tied to a
# numbered AC in tickets/T-006.md, but required by its Definition of Done:
# "pull script is resumable (re-run skips archived ids)"). Static/text
# checks only, zero execution, zero network.
# --------------------------------------------------------------------------


def test_pull_captions_script_exists():
    assert PULL_SCRIPT.exists(), "scripts/pull_captions.sh missing"


def test_pull_captions_script_is_executable():
    assert PULL_SCRIPT.exists(), "scripts/pull_captions.sh missing"
    mode = PULL_SCRIPT.stat().st_mode
    assert mode & stat.S_IXUSR, "scripts/pull_captions.sh must be executable (chmod +x)"


def test_pull_captions_script_uses_download_archive_for_resumability():
    assert PULL_SCRIPT.exists(), "scripts/pull_captions.sh missing"
    text = PULL_SCRIPT.read_text()
    assert "--download-archive" in text, "resumability requires yt-dlp's --download-archive flag"


def test_pull_captions_script_uses_sleep_requests_for_politeness():
    assert PULL_SCRIPT.exists(), "scripts/pull_captions.sh missing"
    text = PULL_SCRIPT.read_text()
    assert "--sleep-requests" in text, "politeness requires yt-dlp's --sleep-requests flag"
