"""Failing tests for T-008 — FMP earnings-transcript adapter.

Encodes tickets/T-008.md AC-1..AC-4. These tests are FROZEN after the Test
Agent hands off: do not edit this file to make an implementation pass — fix
`onrecord/ingest/fmp.py` instead. Written adversarially: assumes nothing
exists yet beyond the module-docstring stub.

Run with:
    uv run pytest tests/unit/ingest/test_fmp.py -v

======================================================================
API CONTRACT (not otherwise pinned by the ticket — fixed here and
authoritative for the Implementation Agent; same status as T-001's test
report documenting the registry schema).
======================================================================

``parse_transcript(payload: dict, ticker: str) -> list[Doc]`` (pure, no I/O)

- Reads ``payload["content"]`` (str), ``payload["quarter"]`` (int),
  ``payload["year"]`` (int), ``payload["date"]`` (str, ``"YYYY-MM-DD"`` or
  ``"YYYY-MM-DD HH:MM:SS"``).
- ``Doc.date`` is normalized to the ``"YYYY-MM-DD"`` portion only (matches
  the design spec's ``Doc`` example date format).
- A "speaker turn" is a line of ``content`` that starts with
  ``SpeakerName: turn text`` at column 0 (name = everything before the
  first ``": "``). Turns are otherwise separated by newlines.
- Consecutive turns by the *same* speaker name are merged into one Doc,
  whose text is the per-turn texts joined with a single space (in order).
- ``Doc.id`` = ``f"fmp:{ticker}:{year}q{quarter}:turn{n:03d}"``, 1-indexed
  and renumbered sequentially *after* merging (zero-padded to 3 digits).
- ``Doc.source_type == "earnings_call"``, ``Doc.venue_type == "coached"``,
  ``Doc.ticker == ticker``, ``Doc.jurisdiction is None`` (not applicable to
  earnings calls), ``Doc.speaker`` populated with the matched name.
- ``Doc.deep_link`` is always a non-empty string starting with
  ``"http://"`` or ``"https://"`` (exact URL scheme is the implementer's
  choice per the ticket's "FMP-cited URL or ticker IR page"; not otherwise
  pinned here).
- If ``content`` contains **no** recognizable ``"Name: text"`` markers at
  all, the *entire* (stripped) content becomes exactly **one** whole-
  transcript Doc (``turn001``) — never zero Docs for non-empty content.

``fetch_transcripts(ticker, quarters, api_key=None, transport=None) -> list[Doc]``

- ``quarters``: list of ``(year, quarter)`` int tuples, processed in the
  given order — each quarter run to completion (including its retry)
  before the next quarter starts.
- Effective key = ``api_key`` if given, else ``os.environ["FMP_API_KEY"]``.
  If neither is set (or the value is falsy/whitespace), the function logs
  **exactly one** clear log line naming ``FMP_API_KEY`` and returns ``[]``
  immediately — **no network call is attempted** and no exception is
  raised.
- ``transport`` is the dependency-injection point for tests: when given,
  the implementation's HTTP client must be built with that transport
  (e.g. ``httpx.Client(transport=transport)``) instead of touching the
  real network.
- Retry/backoff MUST sleep via a module-level ``import time`` +
  ``time.sleep(...)`` call (not ``from time import sleep``) so tests can
  monkeypatch ``time.sleep`` globally without incurring a real delay.
- On an HTTP 429 for a given quarter's request: sleep (backoff), retry
  **exactly once** more. If the retry also fails, log **exactly one**
  line containing ``"429"`` for that quarter, skip it (no exception), and
  continue with any remaining quarters.
- Logging MUST go through ``logger = logging.getLogger(__name__)`` (the
  standard idiom — logger name ``"onrecord.ingest.fmp"``) so tests can
  isolate the adapter's own log lines from httpx's own INFO-level
  request/response logging (which is not part of this contract and is
  *not* counted towards the "exactly one line" requirements below).
- A successful quarter's response body is a JSON array containing one
  transcript object shaped like ``parse_transcript``'s ``payload`` (the
  real FMP endpoint returns a list); the implementation unwraps element
  ``[0]`` and calls ``parse_transcript(obj, ticker)``.
- Return value is the concatenation, in quarters order, of the Docs from
  every quarter that succeeded (skipped quarters contribute nothing).

======================================================================
AMENDMENT (post-review, security REJECTED — see
.tdd-swarm/reports/T-008-review.md, findings C1/I1/I2). Extends the
contract above; the tests added below this line are new, the 8 tests
above are untouched/frozen as originally handed off.
======================================================================

- **Speaker-name heuristic (fixes I1).** A candidate ``"<prefix>: <rest>"``
  line is a **new speaker turn** only if ``<prefix>`` *looks like a name*:
  split on whitespace, ``<prefix>`` has **1-5 words**, and **every** word
  starts with an uppercase letter (``str.istitle()``-style; internal
  apostrophes/hyphens such as ``O'Brien`` or ``Jean-Pierre`` are allowed
  within a word). A line that matches ``"<prefix>: <rest>"`` but whose
  prefix fails this check (e.g. ``"Turning to guidance: ..."`` — the word
  ``"to"`` is lowercase) is **continuation text**: appended (space-joined)
  to the *immediately preceding* raw turn, whatever its speaker (or, if
  there is no preceding turn yet, treated as an unmarked/no-speaker line
  per the existing AC-4 fallback). It must never be emitted as its own Doc
  with the bogus prefix as ``speaker``.
- **Non-429 HTTP error handling (fixes C1/I2).** Any HTTP error status
  other than 429 (401, 403, 404, 500, ...) for a given quarter's request
  is handled exactly like a permanently-failing 429, **minus the
  retry**: a single attempt, no backoff/retry, log **exactly one** line
  for that quarter (message may reference the status code — not pinned
  further), skip it, and continue with the remaining quarters. **No
  exception of any kind escapes ``fetch_transcripts`` for an HTTP error
  status** (this includes ``httpx.HTTPStatusError`` — it must never be
  allowed to propagate, since its default ``str()`` embeds the full
  request URL, including the ``apikey`` query parameter, in plaintext).
- **No-key-leakage guarantee (security-critical, fixes C1).** The
  ``api_key``/effective key value must **never** appear, in any form,
  anywhere in this module's log output — not in the no-key path (already
  covered above), not in the 429 skip-and-log path, and not in the
  non-429 skip-and-log path. Tests assert this via a distinctive sentinel
  key value and ``sentinel_key not in caplog.text``.
"""

from __future__ import annotations

import json
import logging
import time
from pathlib import Path

import httpx
import pytest

from onrecord.ingest import fmp
from onrecord.types import Doc

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures" / "fmp"


# --------------------------------------------------------------------------
# Helpers (not tests)
# --------------------------------------------------------------------------


def _load_fixture(name: str) -> dict:
    path = FIXTURES / name
    assert path.exists(), f"missing fixture: {path}"
    with path.open() as fh:
        return json.load(fh)


def _callable_or_fail(name: str):
    """Return fmp.<name> if present, else a clean pytest.fail (not AttributeError).

    onrecord/ingest/fmp.py currently only has a module docstring — neither
    function exists yet. This converts that into a readable, non-traceback
    failure rather than letting an uncaught AttributeError blow up the test.
    """
    obj = getattr(fmp, name, None)
    if obj is None or not callable(obj):
        pytest.fail(
            f"onrecord.ingest.fmp.{name} is not implemented yet "
            f"(module has no callable named {name!r})"
        )
    return obj


def _call_or_fail(fn, *args, **kwargs):
    """Call fn, converting a NotImplementedError stub into a clean pytest.fail.

    Covers the case where the implementer has landed a signature stub that
    raises NotImplementedError — per the swarm's convention, that counts as
    "correct failure" for a not-yet-implemented adapter, surfaced cleanly
    rather than as a raw traceback.
    """
    try:
        return fn(*args, **kwargs)
    except NotImplementedError as exc:
        pytest.fail(f"{getattr(fn, '__name__', fn)} raised NotImplementedError: {exc}")


def _network_guard_transport() -> httpx.MockTransport:
    """A transport that fails loudly if any HTTP request is ever sent."""

    def handler(request: httpx.Request) -> httpx.Response:  # pragma: no cover - guard
        raise AssertionError(
            f"unexpected live network call in AC-2 test (no api key should mean no "
            f"request is ever sent): {request.method} {request.url}"
        )

    return httpx.MockTransport(handler)


# --------------------------------------------------------------------------
# AC-1 — fixture transcript JSON with 3 speakers over 6 turns -> 6 Docs
# (or fewer with consecutive same-speaker merge), speaker/quarter/date populated.
# --------------------------------------------------------------------------


def test_parse_transcript_basic_three_speakers_six_turns():
    # spec(T-008:AC-1)
    payload = _load_fixture("transcript_basic.json")
    parse_transcript = _callable_or_fail("parse_transcript")

    docs = _call_or_fail(parse_transcript, payload, "VST")

    assert isinstance(docs, list)
    assert len(docs) == 6, (
        f"expected 6 Docs (no consecutive-speaker repeats in fixture), got {len(docs)}"
    )
    assert all(isinstance(d, Doc) for d in docs)

    expected_speakers = [
        "Operator",
        "Jim Burke",
        "Kristopher Moldovan",
        "Operator",
        "Jim Burke",
        "Kristopher Moldovan",
    ]
    assert [d.speaker for d in docs] == expected_speakers

    for i, doc in enumerate(docs, start=1):
        assert doc.id == f"fmp:VST:2025q2:turn{i:03d}", doc.id
        assert doc.source_type == "earnings_call"
        assert doc.venue_type == "coached"
        assert doc.ticker == "VST"
        assert doc.jurisdiction is None
        assert doc.date == "2025-08-07", doc.date
        assert doc.deep_link.startswith(("http://", "https://")), doc.deep_link
        assert doc.text, "Doc.text must not be empty"

    assert docs[0].text.strip().startswith("Good morning, and welcome")
    assert "capital allocation" in docs[5].text


def test_parse_transcript_merges_consecutive_same_speaker_turns():
    # spec(T-008:AC-1)
    payload = _load_fixture("transcript_consecutive_speaker.json")
    parse_transcript = _callable_or_fail("parse_transcript")

    docs = _call_or_fail(parse_transcript, payload, "VST")

    assert len(docs) == 3, (
        f"4 raw turns with 1 consecutive same-speaker pair must merge to 3 Docs, got {len(docs)}"
    )
    assert [d.speaker for d in docs] == ["Operator", "Jim Burke", "Kristopher Moldovan"]
    assert [d.id for d in docs] == [
        "fmp:VST:2025q1:turn001",
        "fmp:VST:2025q1:turn002",
        "fmp:VST:2025q1:turn003",
    ]

    merged = docs[1]
    assert merged.speaker == "Jim Burke"
    expected_text = (
        "Thanks, operator, and good morning everyone. "
        "Before we get into the numbers, I want to spend a moment on the data "
        "center demand backdrop, which remains the single biggest driver of our "
        "long-term contracted growth story."
    )
    assert merged.text == expected_text, merged.text
    assert merged.date == "2025-05-08"
    assert merged.ticker == "VST"


# --------------------------------------------------------------------------
# AC-2 — FMP_API_KEY unset (env and/or param), live fetch -> [] with ONE
# clear log line, no exception, no network attempted.
# --------------------------------------------------------------------------


def test_fetch_transcripts_no_api_key_returns_empty_with_one_log_line(monkeypatch, caplog):
    # spec(T-008:AC-2)
    monkeypatch.delenv("FMP_API_KEY", raising=False)
    fetch_transcripts = _callable_or_fail("fetch_transcripts")

    with caplog.at_level(logging.INFO, logger="onrecord.ingest.fmp"):
        result = _call_or_fail(
            fetch_transcripts,
            "VST",
            [(2025, 2)],
            api_key=None,
            transport=_network_guard_transport(),
        )

    assert result == [], f"expected [] when no api key is available, got {result!r}"

    matches = [r for r in caplog.records if "FMP_API_KEY" in r.getMessage()]
    assert len(matches) == 1, (
        f"expected exactly ONE clear log line mentioning FMP_API_KEY, got {len(matches)}: "
        f"{[r.getMessage() for r in caplog.records]}"
    )


def test_fetch_transcripts_no_api_key_default_param_and_unset_env(monkeypatch, caplog):
    # spec(T-008:AC-2)
    monkeypatch.delenv("FMP_API_KEY", raising=False)
    fetch_transcripts = _callable_or_fail("fetch_transcripts")

    with caplog.at_level(logging.INFO, logger="onrecord.ingest.fmp"):
        # api_key omitted entirely -> must fall back to (unset) env, not raise.
        result = _call_or_fail(
            fetch_transcripts,
            "VST",
            [(2025, 2)],
            transport=_network_guard_transport(),
        )

    assert result == []
    matches = [r for r in caplog.records if "FMP_API_KEY" in r.getMessage()]
    assert len(matches) == 1, (
        f"expected exactly ONE clear log line mentioning FMP_API_KEY, got {len(matches)}: "
        f"{[r.getMessage() for r in caplog.records]}"
    )


# --------------------------------------------------------------------------
# AC-3 — 429 (mocked) -> one backoff retry then skip-and-log, no exception.
# --------------------------------------------------------------------------


def test_fetch_transcripts_429_retries_once_then_skips_and_logs(monkeypatch, caplog):
    # spec(T-008:AC-3)
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    fetch_transcripts = _callable_or_fail("fetch_transcripts")

    calls = {"n": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        calls["n"] += 1
        if calls["n"] <= 2:
            return httpx.Response(429, json={"error": "Too Many Requests"})
        raise AssertionError(
            f"expected at most 2 calls (1 initial + 1 backoff retry) for a "
            f"permanently-429 quarter, got a 3rd call: {request.method} {request.url}"
        )

    transport = httpx.MockTransport(handler)

    with caplog.at_level(logging.INFO, logger="onrecord.ingest.fmp"):
        result = _call_or_fail(
            fetch_transcripts,
            "VST",
            [(2025, 2)],
            api_key="fake-test-key",
            transport=transport,
        )

    assert result == [], f"a permanently-429 quarter must be skipped, not returned: {result!r}"
    assert calls["n"] == 2, f"expected exactly 2 HTTP calls (initial + 1 retry), got {calls['n']}"

    matches = [r for r in caplog.records if "429" in r.getMessage()]
    assert len(matches) == 1, (
        f"expected exactly ONE skip-and-log line mentioning 429, got {len(matches)}: "
        f"{[r.getMessage() for r in caplog.records]}"
    )


def test_fetch_transcripts_429_skip_does_not_block_other_quarters(monkeypatch, caplog):
    # spec(T-008:AC-3)
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    fetch_transcripts = _callable_or_fail("fetch_transcripts")
    parse_transcript = _callable_or_fail("parse_transcript")

    ok_payload = _load_fixture("transcript_basic.json")  # 2025 q2, VST
    expected_ok_docs = _call_or_fail(parse_transcript, ok_payload, "VST")

    calls = {"n": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        calls["n"] += 1
        if calls["n"] == 1:
            # First quarter in `quarters` order succeeds.
            return httpx.Response(200, json=[ok_payload])
        if calls["n"] in (2, 3):
            # Second quarter permanently 429s (initial + 1 retry).
            return httpx.Response(429, json={"error": "Too Many Requests"})
        raise AssertionError(f"unexpected 4th HTTP call: {request.method} {request.url}")

    transport = httpx.MockTransport(handler)

    with caplog.at_level(logging.INFO, logger="onrecord.ingest.fmp"):
        result = _call_or_fail(
            fetch_transcripts,
            "VST",
            [(2025, 2), (2025, 1)],
            api_key="fake-test-key",
            transport=transport,
        )

    assert result == expected_ok_docs, (
        "successful quarter's Docs must be returned unchanged; skipped quarter "
        "must contribute nothing"
    )
    assert calls["n"] == 3, f"expected 1 (ok quarter) + 2 (429 quarter) = 3 calls, got {calls['n']}"

    matches = [r for r in caplog.records if "429" in r.getMessage()]
    assert len(matches) == 1, (
        f"expected exactly ONE skip-and-log line for the failing quarter, got {len(matches)}: "
        f"{[r.getMessage() for r in caplog.records]}"
    )


# --------------------------------------------------------------------------
# AC-4 — content without recognizable speaker markers -> one whole-transcript
# Doc (never zero for non-empty content).
# --------------------------------------------------------------------------


def test_parse_transcript_no_speaker_markers_yields_single_whole_transcript_doc():
    # spec(T-008:AC-4)
    payload = _load_fixture("transcript_no_speaker_markers.json")
    parse_transcript = _callable_or_fail("parse_transcript")

    docs = _call_or_fail(parse_transcript, payload, "VST")

    assert len(docs) == 1, (
        f"content without speaker markers must yield exactly 1 Doc, got {len(docs)}"
    )
    doc = docs[0]
    assert isinstance(doc, Doc)
    assert doc.id == "fmp:VST:2024q3:turn001", doc.id
    assert doc.source_type == "earnings_call"
    assert doc.venue_type == "coached"
    assert doc.ticker == "VST"
    assert doc.jurisdiction is None
    assert doc.date == "2024-11-07", doc.date
    assert doc.text.strip() == payload["content"].strip()
    assert doc.deep_link.startswith(("http://", "https://")), doc.deep_link


def test_parse_transcript_never_returns_zero_docs_for_non_empty_markerless_content():
    # spec(T-008:AC-4)
    payload = {
        "symbol": "CEG",
        "quarter": 4,
        "year": 2024,
        "date": "2025-02-18",
        "content": "A short unattributed excerpt with no colon-prefixed speaker labels at all.",
    }
    parse_transcript = _callable_or_fail("parse_transcript")

    docs = _call_or_fail(parse_transcript, payload, "CEG")

    assert len(docs) == 1, (
        f"non-empty markerless content must never produce 0 Docs, got {len(docs)}"
    )
    assert docs[0].text.strip() == payload["content"]
    assert docs[0].id == "fmp:CEG:2024q4:turn001"
    assert docs[0].date == "2025-02-18"


# ==========================================================================
# AMENDMENT — added post security-review REJECTED
# (.tdd-swarm/reports/T-008-review.md: Critical C1, Important I1/I2).
# New tests only; the 8 tests above are untouched.
# ==========================================================================


# --------------------------------------------------------------------------
# AC-3 amendment — non-429 HTTP errors (401/403/500): skip-and-log, no
# exception escapes, remaining quarters still fetched, and — the
# security-critical assertion — the API key never appears anywhere in the
# logged output (fixes Critical C1 / Important I2).
# --------------------------------------------------------------------------


@pytest.mark.parametrize("status_code", [401, 403, 500])
def test_fetch_transcripts_non_429_error_skips_continues_no_key_leak(
    monkeypatch, caplog, status_code
):
    # spec(T-008:AC-3)
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    fetch_transcripts = _callable_or_fail("fetch_transcripts")
    parse_transcript = _callable_or_fail("parse_transcript")

    sentinel_key = "SENTINEL-KEY-XYZ"
    ok_payload = _load_fixture("transcript_basic.json")  # 2025 q2, VST
    expected_ok_docs = _call_or_fail(parse_transcript, ok_payload, "VST")

    calls = {"n": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        calls["n"] += 1
        if calls["n"] == 1:
            # First quarter errors — must NOT be retried (retry is 429-only).
            return httpx.Response(status_code, json={"error": "boom"})
        if calls["n"] == 2:
            # Second quarter must still be attempted (batch continues).
            return httpx.Response(200, json=[ok_payload])
        raise AssertionError(
            f"expected exactly 2 HTTP calls (1 errored quarter, no retry, + 1 "
            f"successful quarter), got a 3rd call: {request.method} {request.url}"
        )

    transport = httpx.MockTransport(handler)

    with caplog.at_level(logging.INFO, logger="onrecord.ingest.fmp"):
        result = _call_or_fail(
            fetch_transcripts,
            "VST",
            [(2025, 1), (2025, 2)],
            api_key=sentinel_key,
            transport=transport,
        )

    assert result == expected_ok_docs, (
        f"a non-429 ({status_code}) quarter must be skipped (contribute no Docs) "
        f"and the batch must still fetch the remaining quarter, got {result!r}"
    )
    assert calls["n"] == 2, (
        f"errored quarter must not be retried (retry is 429-only); expected "
        f"exactly 2 total HTTP calls, got {calls['n']}"
    )

    own_records = [r for r in caplog.records if r.name == "onrecord.ingest.fmp"]
    assert len(own_records) == 1, (
        f"expected exactly ONE skip-and-log line for the errored quarter, got "
        f"{len(own_records)}: {[r.getMessage() for r in caplog.records]}"
    )

    assert sentinel_key not in caplog.text, (
        f"API key must NEVER appear in adapter log output on a {status_code} "
        f"error path (this includes any exception str() a naive fix might log)"
    )


def test_fetch_transcripts_429_skip_never_leaks_api_key_in_logs(monkeypatch, caplog):
    # spec(T-008:AC-3)
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    fetch_transcripts = _callable_or_fail("fetch_transcripts")

    sentinel_key = "SENTINEL-KEY-XYZ"

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(429, json={"error": "Too Many Requests"})

    transport = httpx.MockTransport(handler)

    with caplog.at_level(logging.INFO, logger="onrecord.ingest.fmp"):
        result = _call_or_fail(
            fetch_transcripts,
            "VST",
            [(2025, 2)],
            api_key=sentinel_key,
            transport=transport,
        )

    assert result == []
    assert sentinel_key not in caplog.text, (
        "API key must NEVER appear in adapter log output on the 429 skip-and-log path either"
    )


# --------------------------------------------------------------------------
# AC-1 amendment — a colon inside a continuation line (no real speaker
# prefix) must merge into the preceding speaker's turn, never spawn a
# bogus speaker Doc (fixes Important I1).
# --------------------------------------------------------------------------


def test_parse_transcript_colon_in_continuation_line_merges_not_bogus_speaker():
    # spec(T-008:AC-1)
    payload = _load_fixture("transcript_colon_continuation.json")
    parse_transcript = _callable_or_fail("parse_transcript")

    docs = _call_or_fail(parse_transcript, payload, "NVDA")

    assert len(docs) == 3, (
        f"a colon inside a continuation line ('Turning to guidance: ...') must "
        f"not create a bogus 4th speaker turn; expected 3 Docs (Operator, "
        f"Jensen Huang [with the continuation merged in], Colette Kress), "
        f"got {len(docs)}: {[d.speaker for d in docs]}"
    )
    assert [d.speaker for d in docs] == ["Operator", "Jensen Huang", "Colette Kress"]
    assert [d.id for d in docs] == [
        "fmp:NVDA:2025q4:turn001",
        "fmp:NVDA:2025q4:turn002",
        "fmp:NVDA:2025q4:turn003",
    ]
    assert "Turning to guidance" not in [d.speaker for d in docs], (
        "the continuation line's pre-colon text must never be treated as a "
        "speaker name (fails the name heuristic: 'to' is not title-cased)"
    )

    jensen_doc = docs[1]
    assert jensen_doc.speaker == "Jensen Huang"
    expected_text = (
        "Thanks, everyone, for joining us today. "
        "Turning to guidance: our full-year outlook remains unchanged from last "
        "quarter, and demand for Blackwell continues to outstrip supply across "
        "every major cloud partner."
    )
    assert jensen_doc.text == expected_text, jensen_doc.text
    assert jensen_doc.date == "2025-02-26"
    assert jensen_doc.ticker == "NVDA"
