"""Failing tests for T-008 — FMP earnings-transcript adapter.

Encodes tickets/T-008.md AC-1..AC-4. These tests are FROZEN after the Test
Agent hands off: do not edit this file to make an implementation pass — fix
`onrecord/ingest/fmp.py` instead. Written adversarially: assumes nothing
exists yet beyond the module-docstring stub.

Run with:
    uv run pytest tests/unit/ingest/test_fmp.py -v

======================================================================
API CONTRACT (not otherwise pinned by the ticket — fixed here and
authoritative for the Implementation Agent; same status as T-001's test
report documenting the registry schema).
======================================================================

``parse_transcript(payload: dict, ticker: str) -> list[Doc]`` (pure, no I/O)

- Reads ``payload["content"]`` (str), ``payload["quarter"]`` (int),
  ``payload["year"]`` (int), ``payload["date"]`` (str, ``"YYYY-MM-DD"`` or
  ``"YYYY-MM-DD HH:MM:SS"``).
- ``Doc.date`` is normalized to the ``"YYYY-MM-DD"`` portion only (matches
  the design spec's ``Doc`` example date format).
- A "speaker turn" is a line of ``content`` that starts with
  ``SpeakerName: turn text`` at column 0 (name = everything before the
  first ``": "``). Turns are otherwise separated by newlines.
- Consecutive turns by the *same* speaker name are merged into one Doc,
  whose text is the per-turn texts joined with a single space (in order).
- ``Doc.id`` = ``f"fmp:{ticker}:{year}q{quarter}:turn{n:03d}"``, 1-indexed
  and renumbered sequentially *after* merging (zero-padded to 3 digits).
- ``Doc.source_type == "earnings_call"``, ``Doc.venue_type == "coached"``,
  ``Doc.ticker == ticker``, ``Doc.jurisdiction is None`` (not applicable to
  earnings calls), ``Doc.speaker`` populated with the matched name.
- ``Doc.deep_link`` is always a non-empty string starting with
  ``"http://"`` or ``"https://"`` (exact URL scheme is the implementer's
  choice per the ticket's "FMP-cited URL or ticker IR page"; not otherwise
  pinned here).
- If ``content`` contains **no** recognizable ``"Name: text"`` markers at
  all, the *entire* (stripped) content becomes exactly **one** whole-
  transcript Doc (``turn001``) — never zero Docs for non-empty content.

``fetch_transcripts(ticker, quarters, api_key=None, transport=None) -> list[Doc]``

- ``quarters``: list of ``(year, quarter)`` int tuples, processed in the
  given order — each quarter run to completion (including its retry)
  before the next quarter starts.
- Effective key = ``api_key`` if given, else ``os.environ["FMP_API_KEY"]``.
  If neither is set (or the value is falsy/whitespace), the function logs
  **exactly one** clear log line naming ``FMP_API_KEY`` and returns ``[]``
  immediately — **no network call is attempted** and no exception is
  raised.
- ``transport`` is the dependency-injection point for tests: when given,
  the implementation's HTTP client must be built with that transport
  (e.g. ``httpx.Client(transport=transport)``) instead of touching the
  real network.
- Retry/backoff MUST sleep via a module-level ``import time`` +
  ``time.sleep(...)`` call (not ``from time import sleep``) so tests can
  monkeypatch ``time.sleep`` globally without incurring a real delay.
- On an HTTP 429 for a given quarter's request: sleep (backoff), retry
  **exactly once** more. If the retry also fails, log **exactly one**
  line containing ``"429"`` for that quarter, skip it (no exception), and
  continue with any remaining quarters.
- Logging MUST go through ``logger = logging.getLogger(__name__)`` (the
  standard idiom — logger name ``"onrecord.ingest.fmp"``) so tests can
  isolate the adapter's own log lines from httpx's own INFO-level
  request/response logging (which is not part of this contract and is
  *not* counted towards the "exactly one line" requirements below).
- A successful quarter's response body is a JSON array containing one
  transcript object shaped like ``parse_transcript``'s ``payload`` (the
  real FMP endpoint returns a list); the implementation unwraps element
  ``[0]`` and calls ``parse_transcript(obj, ticker)``.
- Return value is the concatenation, in quarters order, of the Docs from
  every quarter that succeeded (skipped quarters contribute nothing).
"""

from __future__ import annotations

import json
import logging
import time
from pathlib import Path

import httpx
import pytest

from onrecord.ingest import fmp
from onrecord.types import Doc

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures" / "fmp"


# --------------------------------------------------------------------------
# Helpers (not tests)
# --------------------------------------------------------------------------


def _load_fixture(name: str) -> dict:
    path = FIXTURES / name
    assert path.exists(), f"missing fixture: {path}"
    with path.open() as fh:
        return json.load(fh)


def _callable_or_fail(name: str):
    """Return fmp.<name> if present, else a clean pytest.fail (not AttributeError).

    onrecord/ingest/fmp.py currently only has a module docstring — neither
    function exists yet. This converts that into a readable, non-traceback
    failure rather than letting an uncaught AttributeError blow up the test.
    """
    obj = getattr(fmp, name, None)
    if obj is None or not callable(obj):
        pytest.fail(
            f"onrecord.ingest.fmp.{name} is not implemented yet "
            f"(module has no callable named {name!r})"
        )
    return obj


def _call_or_fail(fn, *args, **kwargs):
    """Call fn, converting a NotImplementedError stub into a clean pytest.fail.

    Covers the case where the implementer has landed a signature stub that
    raises NotImplementedError — per the swarm's convention, that counts as
    "correct failure" for a not-yet-implemented adapter, surfaced cleanly
    rather than as a raw traceback.
    """
    try:
        return fn(*args, **kwargs)
    except NotImplementedError as exc:
        pytest.fail(f"{getattr(fn, '__name__', fn)} raised NotImplementedError: {exc}")


def _network_guard_transport() -> httpx.MockTransport:
    """A transport that fails loudly if any HTTP request is ever sent."""

    def handler(request: httpx.Request) -> httpx.Response:  # pragma: no cover - guard
        raise AssertionError(
            f"unexpected live network call in AC-2 test (no api key should mean no "
            f"request is ever sent): {request.method} {request.url}"
        )

    return httpx.MockTransport(handler)


# --------------------------------------------------------------------------
# AC-1 — fixture transcript JSON with 3 speakers over 6 turns -> 6 Docs
# (or fewer with consecutive same-speaker merge), speaker/quarter/date populated.
# --------------------------------------------------------------------------


def test_parse_transcript_basic_three_speakers_six_turns():
    # spec(T-008:AC-1)
    payload = _load_fixture("transcript_basic.json")
    parse_transcript = _callable_or_fail("parse_transcript")

    docs = _call_or_fail(parse_transcript, payload, "VST")

    assert isinstance(docs, list)
    assert len(docs) == 6, (
        f"expected 6 Docs (no consecutive-speaker repeats in fixture), got {len(docs)}"
    )
    assert all(isinstance(d, Doc) for d in docs)

    expected_speakers = [
        "Operator",
        "Jim Burke",
        "Kristopher Moldovan",
        "Operator",
        "Jim Burke",
        "Kristopher Moldovan",
    ]
    assert [d.speaker for d in docs] == expected_speakers

    for i, doc in enumerate(docs, start=1):
        assert doc.id == f"fmp:VST:2025q2:turn{i:03d}", doc.id
        assert doc.source_type == "earnings_call"
        assert doc.venue_type == "coached"
        assert doc.ticker == "VST"
        assert doc.jurisdiction is None
        assert doc.date == "2025-08-07", doc.date
        assert doc.deep_link.startswith(("http://", "https://")), doc.deep_link
        assert doc.text, "Doc.text must not be empty"

    assert docs[0].text.strip().startswith("Good morning, and welcome")
    assert "capital allocation" in docs[5].text


def test_parse_transcript_merges_consecutive_same_speaker_turns():
    # spec(T-008:AC-1)
    payload = _load_fixture("transcript_consecutive_speaker.json")
    parse_transcript = _callable_or_fail("parse_transcript")

    docs = _call_or_fail(parse_transcript, payload, "VST")

    assert len(docs) == 3, (
        f"4 raw turns with 1 consecutive same-speaker pair must merge to 3 Docs, got {len(docs)}"
    )
    assert [d.speaker for d in docs] == ["Operator", "Jim Burke", "Kristopher Moldovan"]
    assert [d.id for d in docs] == [
        "fmp:VST:2025q1:turn001",
        "fmp:VST:2025q1:turn002",
        "fmp:VST:2025q1:turn003",
    ]

    merged = docs[1]
    assert merged.speaker == "Jim Burke"
    expected_text = (
        "Thanks, operator, and good morning everyone. "
        "Before we get into the numbers, I want to spend a moment on the data "
        "center demand backdrop, which remains the single biggest driver of our "
        "long-term contracted growth story."
    )
    assert merged.text == expected_text, merged.text
    assert merged.date == "2025-05-08"
    assert merged.ticker == "VST"


# --------------------------------------------------------------------------
# AC-2 — FMP_API_KEY unset (env and/or param), live fetch -> [] with ONE
# clear log line, no exception, no network attempted.
# --------------------------------------------------------------------------


def test_fetch_transcripts_no_api_key_returns_empty_with_one_log_line(monkeypatch, caplog):
    # spec(T-008:AC-2)
    monkeypatch.delenv("FMP_API_KEY", raising=False)
    fetch_transcripts = _callable_or_fail("fetch_transcripts")

    with caplog.at_level(logging.INFO, logger="onrecord.ingest.fmp"):
        result = _call_or_fail(
            fetch_transcripts,
            "VST",
            [(2025, 2)],
            api_key=None,
            transport=_network_guard_transport(),
        )

    assert result == [], f"expected [] when no api key is available, got {result!r}"

    matches = [r for r in caplog.records if "FMP_API_KEY" in r.getMessage()]
    assert len(matches) == 1, (
        f"expected exactly ONE clear log line mentioning FMP_API_KEY, got {len(matches)}: "
        f"{[r.getMessage() for r in caplog.records]}"
    )


def test_fetch_transcripts_no_api_key_default_param_and_unset_env(monkeypatch, caplog):
    # spec(T-008:AC-2)
    monkeypatch.delenv("FMP_API_KEY", raising=False)
    fetch_transcripts = _callable_or_fail("fetch_transcripts")

    with caplog.at_level(logging.INFO, logger="onrecord.ingest.fmp"):
        # api_key omitted entirely -> must fall back to (unset) env, not raise.
        result = _call_or_fail(
            fetch_transcripts,
            "VST",
            [(2025, 2)],
            transport=_network_guard_transport(),
        )

    assert result == []
    matches = [r for r in caplog.records if "FMP_API_KEY" in r.getMessage()]
    assert len(matches) == 1, (
        f"expected exactly ONE clear log line mentioning FMP_API_KEY, got {len(matches)}: "
        f"{[r.getMessage() for r in caplog.records]}"
    )


# --------------------------------------------------------------------------
# AC-3 — 429 (mocked) -> one backoff retry then skip-and-log, no exception.
# --------------------------------------------------------------------------


def test_fetch_transcripts_429_retries_once_then_skips_and_logs(monkeypatch, caplog):
    # spec(T-008:AC-3)
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    fetch_transcripts = _callable_or_fail("fetch_transcripts")

    calls = {"n": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        calls["n"] += 1
        if calls["n"] <= 2:
            return httpx.Response(429, json={"error": "Too Many Requests"})
        raise AssertionError(
            f"expected at most 2 calls (1 initial + 1 backoff retry) for a "
            f"permanently-429 quarter, got a 3rd call: {request.method} {request.url}"
        )

    transport = httpx.MockTransport(handler)

    with caplog.at_level(logging.INFO, logger="onrecord.ingest.fmp"):
        result = _call_or_fail(
            fetch_transcripts,
            "VST",
            [(2025, 2)],
            api_key="fake-test-key",
            transport=transport,
        )

    assert result == [], f"a permanently-429 quarter must be skipped, not returned: {result!r}"
    assert calls["n"] == 2, f"expected exactly 2 HTTP calls (initial + 1 retry), got {calls['n']}"

    matches = [r for r in caplog.records if "429" in r.getMessage()]
    assert len(matches) == 1, (
        f"expected exactly ONE skip-and-log line mentioning 429, got {len(matches)}: "
        f"{[r.getMessage() for r in caplog.records]}"
    )


def test_fetch_transcripts_429_skip_does_not_block_other_quarters(monkeypatch, caplog):
    # spec(T-008:AC-3)
    monkeypatch.setattr(time, "sleep", lambda *_a, **_kw: None)
    fetch_transcripts = _callable_or_fail("fetch_transcripts")
    parse_transcript = _callable_or_fail("parse_transcript")

    ok_payload = _load_fixture("transcript_basic.json")  # 2025 q2, VST
    expected_ok_docs = _call_or_fail(parse_transcript, ok_payload, "VST")

    calls = {"n": 0}

    def handler(request: httpx.Request) -> httpx.Response:
        calls["n"] += 1
        if calls["n"] == 1:
            # First quarter in `quarters` order succeeds.
            return httpx.Response(200, json=[ok_payload])
        if calls["n"] in (2, 3):
            # Second quarter permanently 429s (initial + 1 retry).
            return httpx.Response(429, json={"error": "Too Many Requests"})
        raise AssertionError(f"unexpected 4th HTTP call: {request.method} {request.url}")

    transport = httpx.MockTransport(handler)

    with caplog.at_level(logging.INFO, logger="onrecord.ingest.fmp"):
        result = _call_or_fail(
            fetch_transcripts,
            "VST",
            [(2025, 2), (2025, 1)],
            api_key="fake-test-key",
            transport=transport,
        )

    assert result == expected_ok_docs, (
        "successful quarter's Docs must be returned unchanged; skipped quarter "
        "must contribute nothing"
    )
    assert calls["n"] == 3, f"expected 1 (ok quarter) + 2 (429 quarter) = 3 calls, got {calls['n']}"

    matches = [r for r in caplog.records if "429" in r.getMessage()]
    assert len(matches) == 1, (
        f"expected exactly ONE skip-and-log line for the failing quarter, got {len(matches)}: "
        f"{[r.getMessage() for r in caplog.records]}"
    )


# --------------------------------------------------------------------------
# AC-4 — content without recognizable speaker markers -> one whole-transcript
# Doc (never zero for non-empty content).
# --------------------------------------------------------------------------


def test_parse_transcript_no_speaker_markers_yields_single_whole_transcript_doc():
    # spec(T-008:AC-4)
    payload = _load_fixture("transcript_no_speaker_markers.json")
    parse_transcript = _callable_or_fail("parse_transcript")

    docs = _call_or_fail(parse_transcript, payload, "VST")

    assert len(docs) == 1, (
        f"content without speaker markers must yield exactly 1 Doc, got {len(docs)}"
    )
    doc = docs[0]
    assert isinstance(doc, Doc)
    assert doc.id == "fmp:VST:2024q3:turn001", doc.id
    assert doc.source_type == "earnings_call"
    assert doc.venue_type == "coached"
    assert doc.ticker == "VST"
    assert doc.jurisdiction is None
    assert doc.date == "2024-11-07", doc.date
    assert doc.text.strip() == payload["content"].strip()
    assert doc.deep_link.startswith(("http://", "https://")), doc.deep_link


def test_parse_transcript_never_returns_zero_docs_for_non_empty_markerless_content():
    # spec(T-008:AC-4)
    payload = {
        "symbol": "CEG",
        "quarter": 4,
        "year": 2024,
        "date": "2025-02-18",
        "content": "A short unattributed excerpt with no colon-prefixed speaker labels at all.",
    }
    parse_transcript = _callable_or_fail("parse_transcript")

    docs = _call_or_fail(parse_transcript, payload, "CEG")

    assert len(docs) == 1, (
        f"non-empty markerless content must never produce 0 Docs, got {len(docs)}"
    )
    assert docs[0].text.strip() == payload["content"]
    assert docs[0].id == "fmp:CEG:2024q4:turn001"
    assert docs[0].date == "2025-02-18"
